export interface FAQItem {
  question: string;
  answer: string;
}

export const ideal_weight_calculatorFaqs: FAQItem[] = [
  {
    question: "What is an ideal body weight?",
    answer:
      "Ideal body weight (IBW) is a historical reference estimate calculated primarily from height. Several different equations have been developed, including Devine, Robinson, Miller and Hamwi, and they can produce different answers for the same person. IBW should therefore be treated as a reference estimate rather than a universally correct target weight.",
  },
  {
    question: "What is the most accurate ideal body weight formula?",
    answer:
      "There is no single IBW formula that can be called universally most accurate for every person and every purpose. The published equations were developed using different methods and populations, and reviews show meaningful variation between them. This calculator displays five formulas so you can see the range rather than relying on one equation alone.",
  },
  {
    question: "How is ideal body weight calculated for men?",
    answer:
      "It depends on the formula. For example, the Devine male equation is 50 + 2.3 × the number of inches above 5 feet, with the result in kilograms. Robinson, Miller and Hamwi use different coefficients. The calculator calculates all supported formulas separately so their differences are visible.",
  },
  {
    question: "How is ideal body weight calculated for women?",
    answer:
      "Female IBW equations use coefficients that differ from the corresponding male equations. For example, the Devine female equation starts with 45.5 kg and adds 2.3 kg for each inch above 5 feet. Robinson, Miller and Hamwi use their own female coefficients.",
  },
  {
    question: "Why are my Devine, Robinson, Miller and Hamwi results different?",
    answer:
      "Each equation was developed differently and uses different coefficients. Published comparisons show that the estimated IBW can vary substantially depending on the formula selected. That is normal and is one reason a multi-formula calculator is more informative than presenting one historical equation as the only answer.",
  },
  {
    question: "What is the Lemmens ideal body weight formula?",
    answer:
      "The Lemmens equation is IBW = 22 × height(m)². It was proposed as a simple formula for both men and women, with the resulting value positioned approximately in the middle of values generated by several published IBW equations.",
  },
  {
    question: "What is the difference between ideal body weight and BMI?",
    answer:
      "IBW is a collection of historical reference equations, while BMI is a weight-to-height index: BMI = kg/m². WHO uses BMI categories for adult population-level classification. An IBW value and a BMI-derived weight range can therefore be different without either calculation being mathematically wrong.",
  },
  {
    question: "What is the normal BMI range for adults?",
    answer:
      "WHO classifies a BMI from 18.5 to 24.9 kg/m² as normal weight for adults. A BMI below 18.5 is classified as underweight, while 25.0–29.9 is pre-obesity/overweight and 30 or above is obesity.",
  },
  {
    question: "Does body-frame size change BMI?",
    answer:
      "No. Frame size may be used as an optional adjustment to some historical IBW calculations, but it does not change the mathematical BMI or the WHO BMI category thresholds. A larger skeletal frame should not be used to redefine a BMI of 25 as a normal BMI.",
  },
  {
    question: "Can muscular people have a weight above their calculated ideal body weight?",
    answer:
      "Yes. Historical IBW formulas are primarily height-based and do not directly measure muscle mass. A muscular person can weigh considerably more than an IBW estimate while having relatively low body fat. BMI has a similar limitation because it does not distinguish lean mass from fat mass.",
  },
  {
    question: "Is ideal body weight the same as my healthiest weight?",
    answer:
      "No. An IBW calculation is only a reference estimate. A personally appropriate weight can depend on body composition, medical conditions, age, activity level, nutritional status and other factors that a height-based equation cannot capture.",
  },
  {
    question: "Can I use this calculator for children?",
    answer:
      "The historical formulas can be calculated mathematically, but adult IBW and adult BMI interpretation should not simply be transferred to children. WHO uses age- and sex-specific growth references for people aged 0–19 rather than applying the adult BMI thresholds directly.",
  },
  {
    question: "Can ideal body weight be used for medication dosing?",
    answer:
      "An IBW equation may appear in some clinical or pharmacological calculations, but the correct dosing weight is medication-specific. Some drugs may use actual body weight, ideal body weight, adjusted body weight or another dosing convention. Medication doses should therefore be determined using the appropriate clinical protocol rather than this calculator alone.",
  },
  {
    question: "Should I try to reach my exact IBW result?",
    answer:
      "Not necessarily. The five equations can disagree by several pounds, and the result does not account for every aspect of health or body composition. It is better to use the calculator as a reference and consider your broader health context rather than treating the consensus value as a mandatory target.",
  },
  {
    question: "Why does this calculator show both IBW and a WHO healthy weight range?",
    answer:
      "They answer different questions. IBW formulas provide historical height-based reference estimates, while the WHO range converts adult BMI thresholds into an approximate weight range for a given height. Showing both helps users understand the difference between an IBW equation and a population-based BMI classification.",
  },
];
