import { CalculatorModuleDefinition } from "../../types";
import { calculateAutoLoanFormula } from "@/lib/calculator-engine/formulas/auto-loan";
import { AUTO_LOAN_FAQS } from "@/app/calculators/auto-loan-calculator/faq";

export const AUTO_LOAN_CALCULATOR: CalculatorModuleDefinition = {
  id: "auto-loan",
  title: "Auto Loan Calculator",
  slug: "auto-loan-calculator",
  category: "Finance",
  subcategory: "Auto",
  description:
    "Calculate monthly payments, net loan cost, interest, trade-in equity, negative equity rollover, state taxes, dealer fees, and vehicle affordability.",
  iconName: "Car",
  featured: true,
  tags: [
    "auto loan",
    "car payment calculator",
    "vehicle financing",
    "trade-in value",
    "negative equity",
    "sales tax",
    "car affordability",
  ],
  formulaDescription:
    "Loan Amount = Vehicle Price - Down Payment - Net Trade-In Equity + Negative Equity Rollover + Financed Taxes & Fees; Monthly Payment = Loan Amount × [r(1 + r)^n] / [(1 + r)^n - 1]",
  faqs: AUTO_LOAN_FAQS,
  inputs: [
    {
      name: "vehiclePrice",
      label: "Vehicle Price",
      type: "currency",
      defaultValue: 35000,
      unit: "$",
      min: 1000,
      max: 500000,
      step: 500,
      tooltip: "Sticker price or negotiated price of the vehicle",
    },
    {
      name: "downPayment",
      label: "Down Payment",
      type: "currency",
      defaultValue: 5000,
      unit: "$",
      min: 0,
      max: 200000,
      step: 250,
      tooltip: "Upfront cash paid towards the purchase",
    },
    {
      name: "tradeInValue",
      label: "Trade-In Value",
      type: "currency",
      defaultValue: 3000,
      unit: "$",
      min: 0,
      max: 100000,
      step: 250,
      tooltip: "Allowance value offered for your trade-in vehicle",
    },
    {
      name: "amountOwedOnTradeIn",
      label: "Amount Owed On Trade-In",
      type: "currency",
      defaultValue: 0,
      unit: "$",
      min: 0,
      max: 100000,
      step: 250,
      tooltip: "Remaining loan balance on your trade-in vehicle",
    },
    {
      name: "interestRate",
      label: "Interest Rate (APR)",
      type: "percentage",
      defaultValue: 5.9,
      unit: "%",
      min: 0,
      max: 30,
      step: 0.1,
      tooltip: "Annual interest rate on the auto loan",
    },
    {
      name: "loanTermMonths",
      label: "Loan Term",
      type: "slider",
      defaultValue: 60,
      unit: "months",
      min: 12,
      max: 96,
      step: 6,
      tooltip: "Duration of the auto loan in months",
    },
    {
      name: "salesTaxRate",
      label: "Sales Tax Rate",
      type: "percentage",
      defaultValue: 6.0,
      unit: "%",
      min: 0,
      max: 15,
      step: 0.1,
      tooltip: "Combined state and local sales tax rate percentage",
    },
    {
      name: "registrationFees",
      label: "Registration & Title Fees",
      type: "currency",
      defaultValue: 300,
      unit: "$",
      min: 0,
      max: 5000,
      step: 50,
      tooltip: "State motor vehicle registration and title transfer fees",
    },
    {
      name: "dealerFees",
      label: "Dealer Documentation Fees",
      type: "currency",
      defaultValue: 250,
      unit: "$",
      min: 0,
      max: 3000,
      step: 25,
      tooltip: "Dealer processing and documentation fee",
    },
  ],
  outputs: [
    {
      name: "monthlyPayment",
      label: "Monthly Payment",
      format: "currency",
      highlight: true,
      description: "Estimated monthly principal and interest loan payment",
    },
    {
      name: "loanAmount",
      label: "Total Loan Financed",
      format: "currency",
      description: "Net financed loan principal",
    },
    {
      name: "totalInterestPaid",
      label: "Total Interest Paid",
      format: "currency",
      description: "Total interest paid over the life of the loan",
    },
    {
      name: "totalSalesTax",
      label: "Total Sales Tax",
      format: "currency",
      description: "Calculated vehicle sales tax",
    },
    {
      name: "totalOutofPocketCost",
      label: "Total Out-of-Pocket Cost",
      format: "currency",
      description: "Combined total of down payment, fees, trade-in equity, and all loan payments",
    },
  ],
  calculate: (inputs) => {
    const res = calculateAutoLoanFormula({
      vehiclePrice: inputs.vehiclePrice !== undefined && inputs.vehiclePrice !== "" ? Number(inputs.vehiclePrice) : 35000,
      downPayment: inputs.downPayment !== undefined && inputs.downPayment !== "" ? Number(inputs.downPayment) : 5000,
      tradeInValue: inputs.tradeInValue !== undefined && inputs.tradeInValue !== "" ? Number(inputs.tradeInValue) : 3000,
      amountOwedOnTradeIn: inputs.amountOwedOnTradeIn !== undefined && inputs.amountOwedOnTradeIn !== "" ? Number(inputs.amountOwedOnTradeIn) : 0,
      salesTaxRate: inputs.salesTaxRate !== undefined && inputs.salesTaxRate !== "" ? Number(inputs.salesTaxRate) : 6,
      registrationFees: inputs.registrationFees !== undefined && inputs.registrationFees !== "" ? Number(inputs.registrationFees) : 300,
      dealerFees: inputs.dealerFees !== undefined && inputs.dealerFees !== "" ? Number(inputs.dealerFees) : 250,
      interestRate: inputs.interestRate !== undefined && inputs.interestRate !== "" ? Number(inputs.interestRate) : 5.9,
      loanTermMonths: inputs.loanTermMonths !== undefined && inputs.loanTermMonths !== "" ? Number(inputs.loanTermMonths) : 60,
    });
    return {
      monthlyPayment: res.monthlyPayment,
      loanAmount: res.loanAmount,
      totalInterestPaid: res.totalInterestPaid,
      totalSalesTax: res.totalSalesTax,
      totalFees: res.totalFees,
      totalPayment: res.totalPayment,
      totalOutofPocketCost: res.totalOutofPocketCost,
    };
  },
};

export default AUTO_LOAN_CALCULATOR;
