import { CalculatorModuleDefinition } from "../../types";
import { calculateMortgageFormula } from "@/lib/calculator-engine/formulas/mortgage";
import MortgageContentSection from "@/components/calculator/mortgage/MortgageContentSection";

export const MORTGAGE_CALCULATOR: CalculatorModuleDefinition = {
  id: "mortgage",
  title: "Mortgage Calculator",
  slug: "mortgage-calculator",
  category: "Finance",
  subcategory: "Mortgage and Real Estate",
  description: "Calculate monthly mortgage payments (P&I), property taxes, insurance, PMI, and HOA fees. Model extra principal payments, biweekly schedules, and view full amortization.",
  iconName: "Home",
  featured: true,
  tags: ["mortgage", "home loan", "interest", "real estate", "property tax", "pmi", "hoa", "amortization"],
  formulaDescription: "Monthly Payment = P × [r(1 + r)^n] / [(1 + r)^n - 1] + Property Tax + Insurance + PMI + HOA + (Other Costs / 12) + Extra Payments",
  ContentComponent: MortgageContentSection,
  faqs: [
    {
      question: "How is my monthly principal and interest payment calculated?",
      answer: "Your base payment is calculated using standard fixed-rate amortization: M = P × [r(1+r)^n] / [(1+r)^n - 1], where P is loan principal, r is the monthly note rate (annual rate / 12), and n is total monthly periods.",
    },
    {
      question: "What is the difference between PITI and Total Monthly Housing Outflow?",
      answer: "PITI represents Principal, Interest, Taxes, and Insurance. Total Monthly Housing Outflow is a broader figure that adds PMI, HOA dues, maintenance reserves, and elective extra principal payments.",
    },
    {
      question: "When can Private Mortgage Insurance (PMI) be removed?",
      answer: "Under the Homeowners Protection Act of 1998, borrowers may request PMI cancellation in writing at 80% LTV, while servicers must automatically terminate PMI at 78% LTV if payments are current.",
    },
    {
      question: "How do extra principal payments shorten my mortgage term?",
      answer: "Extra payments reduce your unpaid principal balance directly, lowering all future monthly interest calculations and extinguishing the remaining balance years ahead of schedule.",
    },
    {
      question: "How does a biweekly mortgage payment program save interest?",
      answer: "A biweekly schedule makes 26 half-payments per year (equivalent to 13 monthly payments). This extra annual payment applies directly to principal, compressing a 30-year term down to roughly 24 years.",
    },
  ],
  inputs: [
    {
      name: "homePrice",
      label: "Home Purchase Price",
      type: "currency",
      defaultValue: 400000,
      unit: "$",
      min: 10000,
      max: 10000000,
      step: 5000,
      tooltip: "The total purchase price of the property",
    },
    {
      name: "downPayment",
      label: "Down Payment",
      type: "currency",
      defaultValue: 80000,
      unit: "$",
      min: 0,
      max: 5000000,
      step: 1000,
      tooltip: "Initial upfront cash payment towards the property",
    },
    {
      name: "interestRate",
      label: "Interest Rate (p.a.)",
      type: "percentage",
      defaultValue: 6.5,
      unit: "%",
      min: 0.1,
      max: 25,
      step: 0.1,
      tooltip: "Annual mortgage interest rate",
    },
    {
      name: "loanTermYears",
      label: "Loan Term",
      type: "slider",
      defaultValue: 30,
      unit: "years",
      min: 5,
      max: 40,
      step: 1,
      tooltip: "Duration of the home loan in years",
    },
    {
      name: "propertyTax",
      label: "Property Taxes (Annual)",
      type: "currency",
      defaultValue: 4800,
      unit: "$",
      min: 0,
      max: 100000,
      step: 100,
      tooltip: "Estimated annual property tax",
    },
    {
      name: "homeInsurance",
      label: "Home Insurance (Annual)",
      type: "currency",
      defaultValue: 1500,
      unit: "$",
      min: 0,
      max: 50000,
      step: 100,
      tooltip: "Estimated annual homeowner insurance premium",
    },
    {
      name: "pmiRate",
      label: "PMI Rate (p.a.)",
      type: "percentage",
      defaultValue: 0.5,
      unit: "%",
      min: 0,
      max: 5,
      step: 0.1,
      tooltip: "Private Mortgage Insurance rate when down payment is less than 20%",
    },
    {
      name: "hoaFee",
      label: "HOA Fees (Monthly)",
      type: "currency",
      defaultValue: 0,
      unit: "$",
      min: 0,
      max: 5000,
      step: 25,
      tooltip: "Monthly Homeowners Association fees if applicable",
    },
    {
      name: "otherCosts",
      label: "Other Costs (Monthly)",
      type: "currency",
      defaultValue: 0,
      unit: "$",
      min: 0,
      max: 5000,
      step: 25,
      tooltip: "Other monthly costs (e.g. utilities, maintenance reserves)",
    },
    {
      name: "extraMonthlyPayment",
      label: "Extra Monthly Payment",
      type: "currency",
      defaultValue: 0,
      unit: "$",
      min: 0,
      max: 10000,
      step: 50,
      tooltip: "Additional monthly payment applied directly to loan principal",
    },
  ],
  outputs: [
    {
      name: "totalInitialMonthlyPayment",
      label: "Total Monthly Payment",
      format: "currency",
      highlight: true,
      description: "Includes Principal, Interest, Tax, Insurance, PMI, HOA & Extra Payment",
    },
    {
      name: "monthlyPrincipalAndInterest",
      label: "Principal & Interest",
      format: "currency",
      description: "Base monthly loan payment",
    },
    {
      name: "loanAmount",
      label: "Total Loan Amount",
      format: "currency",
      description: "Home price minus down payment",
    },
    {
      name: "totalInterestPaid",
      label: "Total Interest Paid",
      format: "currency",
      description: "Cumulative interest paid over loan lifespan",
    },
    {
      name: "totalCost",
      label: "Total Cost of Loan",
      format: "currency",
      description: "Sum of loan principal, interest, taxes, insurance, PMI, HOA, and other costs",
    },
    {
      name: "payoffDate",
      label: "Mortgage Payoff Date",
      format: "text",
      description: "Target payoff month and year",
    },
  ],
  calculate: (inputs) => {
    return calculateMortgageFormula({
      homePrice: Number(inputs.homePrice || 400000),
      downPayment: Number(inputs.downPayment || 80000),
      downPaymentType: inputs.downPaymentType || "amount",
      interestRate: Number(inputs.interestRate || 6.5),
      loanTermYears: Number(inputs.loanTermYears || 30),
      startMonth: Number(inputs.startMonth || new Date().getMonth() + 1),
      startYear: Number(inputs.startYear || new Date().getFullYear()),
      propertyTax: Number(inputs.propertyTax || 4800),
      propertyTaxType: inputs.propertyTaxType || "amount",
      homeInsurance: Number(inputs.homeInsurance || 1500),
      pmiRate: Number(inputs.pmiRate || 0.5),
      hoaFee: Number(inputs.hoaFee || 0),
      otherCosts: Number(inputs.otherCosts || 0),
      propertyTaxIncrease: Number(inputs.propertyTaxIncrease || 2.0),
      insuranceIncrease: Number(inputs.insuranceIncrease || 3.0),
      hoaIncrease: Number(inputs.hoaIncrease || 2.5),
      otherCostsIncrease: Number(inputs.otherCostsIncrease || 2.0),
      extraMonthlyPayment: Number(inputs.extraMonthlyPayment || 0),
      extraYearlyPayment: Number(inputs.extraYearlyPayment || 0),
      extraOneTimePayments: inputs.extraOneTimePayment
        ? [
            {
              id: "otp-1",
              amount: Number(inputs.extraOneTimePayment),
              month: Number(inputs.extraOneTimeMonth || 1),
              year: Number(inputs.extraOneTimeYear || new Date().getFullYear() + 1),
            },
          ]
        : [],
    });
  },
};

export default MORTGAGE_CALCULATOR;
