export interface FetalWeekInfo {
  week: number;
  sizeAnalogy: string;
  lengthCm: number;
  lengthInches: number;
  weightGrams: number;
  weightOunces: string;
  babyDevelopment: string;
  motherChanges: string;
  commonSymptoms: string[];
  keyAdvice: string;
}

export const FETAL_WEEKLY_DATA: Record<number, FetalWeekInfo> = {
  1: {
    week: 1,
    sizeAnalogy: "Pre-conception (Menstrual Phase)",
    lengthCm: 0,
    lengthInches: 0,
    weightGrams: 0,
    weightOunces: "N/A",
    babyDevelopment: "Pre-conception stage. Menstruation occurs and a new cohort of ovarian follicles matures. Fertilization has not yet occurred.",
    motherChanges: "Period occurs. Uterine lining sheds in preparation for new cycle.",
    commonSymptoms: ["Menstrual cramps", "Bloating", "Fatigue", "Mood changes"],
    keyAdvice: "Start taking 400-800 mcg of daily Folic Acid before conception.",
  },
  2: {
    week: 2,
    sizeAnalogy: "Pre-conception (Follicular Phase)",
    lengthCm: 0,
    lengthInches: 0,
    weightGrams: 0,
    weightOunces: "N/A",
    babyDevelopment: "Pre-conception stage. A dominant ovarian follicle matures and releases an egg (ovulation). Fertilization occurs at the end of Week 2.",
    motherChanges: "Estrogen surges. Cervical mucus becomes clear, stretchy, and egg-white consistency.",
    commonSymptoms: ["Increased libido", "Mild pelvic twinges (Mittelschmerz)", "Cervical mucus changes"],
    keyAdvice: "Optimal fertile window! Maintain healthy hydration and avoid alcohol.",
  },
  3: {
    week: 3,
    sizeAnalogy: "Vanilla Bean Seed",
    lengthCm: 0.3,
    lengthInches: 0.1,
    weightGrams: 0.1,
    weightOunces: "< 0.01 oz",
    babyDevelopment: "Fertilization forms a single-celled zygote, multiplying into a blastocyst travelling to uterus.",
    motherChanges: "Blastocyst begins implanting into nutrient-rich endometrial lining.",
    commonSymptoms: ["Mild implantation spotting", "Light cramping", "Heightened sense of smell"],
    keyAdvice: "Avoid NSAID pain relievers; opt for acetaminophen if needed after consulting your care provider.",
  },
  4: {
    week: 4,
    sizeAnalogy: "Poppy Seed",
    lengthCm: 0.4,
    lengthInches: 0.15,
    weightGrams: 0.5,
    weightOunces: "0.02 oz",
    babyDevelopment: "Embryic disc forms inner layer (organs) and outer layer (nervous system & brain precursor).",
    motherChanges: "hCG hormone production skyrockets. Home pregnancy test turns positive!",
    commonSymptoms: ["Missed period", "Tender breasts", "Mild fatigue", "Frequent urination"],
    keyAdvice: "Schedule your initial prenatal appointment with an OB-GYN or midwife.",
  },
  5: {
    week: 5,
    sizeAnalogy: "Sesame Seed",
    lengthCm: 0.5,
    lengthInches: 0.2,
    weightGrams: 0.8,
    weightOunces: "0.03 oz",
    babyDevelopment: "Neural tube begins developing (brain & spinal cord). Primitive heart vascular system forms.",
    motherChanges: "Progesterone surges. Uterus begins expanding.",
    commonSymptoms: ["Morning sickness / Nausea", "Extreme tiredness", "Breast enlargement"],
    keyAdvice: "Stay well hydrated and eat small, frequent nutrient-dense meals.",
  },
  6: {
    week: 6,
    sizeAnalogy: "Lentil",
    lengthCm: 0.6,
    lengthInches: 0.25,
    weightGrams: 1.0,
    weightOunces: "0.04 oz",
    babyDevelopment: "Heart starts beating at 100-160 BPM. Facial features, jaw, and tiny limb buds emerge.",
    motherChanges: "Blood volume increases. Sensation of fullness in lower abdomen.",
    commonSymptoms: ["Severe morning sickness", "Food aversions & cravings", "Mood swings"],
    keyAdvice: "Ginger tea and Vitamin B6 can help soothe pregnancy-related nausea.",
  },
  7: {
    week: 7,
    sizeAnalogy: "Blueberry",
    lengthCm: 1.3,
    lengthInches: 0.5,
    weightGrams: 1.5,
    weightOunces: "0.05 oz",
    babyDevelopment: "Brain forms hemispheres. Tiny hands and feet paddle buds emerge. Kidneys begin functioning.",
    motherChanges: "Cervical mucus forms protective mucous plug to seal uterus.",
    commonSymptoms: ["Increased salivation", "Acne breakouts", "Bloating & constipation"],
    keyAdvice: "Increase dietary fiber intake with fresh fruits, vegetables, and whole grains.",
  },
  8: {
    week: 8,
    sizeAnalogy: "Raspberry",
    lengthCm: 1.6,
    lengthInches: 0.63,
    weightGrams: 1.0,
    weightOunces: "0.04 oz",
    babyDevelopment: "Webbed fingers and toes develop. Eyelids, nose tip, and nerve pathways form.",
    motherChanges: "Uterus has grown to the size of a grapefruit.",
    commonSymptoms: ["Exhaustion", "Sensory sensitivity", "Mild pelvic heaviness"],
    keyAdvice: "First prenatal ultrasound scan window is approaching!",
  },
  9: {
    week: 9,
    sizeAnalogy: "Green Grape",
    lengthCm: 2.3,
    lengthInches: 0.9,
    weightGrams: 2.0,
    weightOunces: "0.07 oz",
    babyDevelopment: "Embryonic tail disappears. Heart valves form. Essential digestive organs rapidly expand.",
    motherChanges: "Waistline expands slightly. Blood pressure may drop slightly causing dizziness.",
    commonSymptoms: ["Dizziness when standing", "Headaches", "Heartburn"],
    keyAdvice: "Rise slowly from seated or lying positions to prevent postural lightheadedness.",
  },
  10: {
    week: 10,
    sizeAnalogy: "Kumquat",
    lengthCm: 3.1,
    lengthInches: 1.22,
    weightGrams: 4.0,
    weightOunces: "0.14 oz",
    babyDevelopment: "Official Fetal Period begins! Vital organs fully formed and starting to function together.",
    motherChanges: "Veins on breasts and stomach become more visible as blood circulation increases 50%.",
    commonSymptoms: ["Visible blue veins", "Round ligament discomfort", "Constipation"],
    keyAdvice: "NIPT screening window opens for early chromosomal assessment.",
  },
  11: {
    week: 11,
    sizeAnalogy: "Fig",
    lengthCm: 4.1,
    lengthInches: 1.61,
    weightGrams: 7.0,
    weightOunces: "0.25 oz",
    babyDevelopment: "Baby opens and closes hands. Tooth buds form beneath gums. External genitalia develop.",
    motherChanges: "Hair and nails grow thicker due to elevated estrogen levels.",
    commonSymptoms: ["Nausea begins improving", "Gas & bloating", "Increased skin glow"],
    keyAdvice: "First trimester screening ultrasound (Nuchal Translucency) window.",
  },
  12: {
    week: 12,
    sizeAnalogy: "Lime",
    lengthCm: 5.4,
    lengthInches: 2.13,
    weightGrams: 14.0,
    weightOunces: "0.49 oz",
    babyDevelopment: "Reflexes develop—baby squirms when touched on ultrasound! Bone marrow produces WBCs.",
    motherChanges: "Uterus rises above pelvic bone; pressure on bladder decreases slightly.",
    commonSymptoms: ["Decreased nausea", "Renewed energy", "Darkening line on abdomen (Linea Nigra)"],
    keyAdvice: "Great time to share the joyful news with loved ones!",
  },
  13: {
    week: 13,
    sizeAnalogy: "Pea Pod",
    lengthCm: 7.4,
    lengthInches: 2.91,
    weightGrams: 23.0,
    weightOunces: "0.81 oz",
    babyDevelopment: "Vocal cords form. Fingerprints unique to baby are engraved on fingertips.",
    motherChanges: "Final week of First Trimester! Risk of pregnancy loss drops dramatically.",
    commonSymptoms: ["Increased energy", "Mild breast growth", "Libido rebound"],
    keyAdvice: "Incorporate pelvic floor (Kegel) exercises into your daily routine.",
  },
  14: {
    week: 14,
    sizeAnalogy: "Lemon",
    lengthCm: 8.7,
    lengthInches: 3.43,
    weightGrams: 43.0,
    weightOunces: "1.52 oz",
    babyDevelopment: "Second Trimester Begins! Baby makes facial expressions (squinting, frowning) and swallows amniotic fluid.",
    motherChanges: "Pregnancy bump starts showing nicely.",
    commonSymptoms: ["Increased appetite", "Round ligament stretching pain", "Stuffy nose (pregnancy rhinitis)"],
    keyAdvice: "Invest in comfortable maternity clothing and supportive bras.",
  },
  15: {
    week: 15,
    sizeAnalogy: "Apple",
    lengthCm: 10.1,
    lengthInches: 3.98,
    weightGrams: 70.0,
    weightOunces: "2.47 oz",
    babyDevelopment: "Sensory organs activate. Light can be sensed through closed eyelids. Bones harden (ossification).",
    motherChanges: "Brain fog or 'pregnancy brain' may be noticed.",
    commonSymptoms: ["Bleeding gums when brushing", "Increased discharge", "Shortness of breath on exertion"],
    keyAdvice: "Use a soft toothbrush and schedule a routine dental checkup.",
  },
  16: {
    week: 16,
    sizeAnalogy: "Avocado",
    lengthCm: 11.6,
    lengthInches: 4.57,
    weightGrams: 100.0,
    weightOunces: "3.53 oz",
    babyDevelopment: "Eyes make slow movements. Heart pumps 25 quarts of blood per day. Neck muscle strength allows head upright.",
    motherChanges: "Uterus is halfway between pubic bone and belly button.",
    commonSymptoms: ["Backaches", "Glowing skin", "Forgetfulness"],
    keyAdvice: "Start sleeping on your side with a supportive pillow between your knees.",
  },
  17: {
    week: 17,
    sizeAnalogy: "Pomegranate",
    lengthCm: 13.0,
    lengthInches: 5.12,
    weightGrams: 140.0,
    weightOunces: "4.94 oz",
    babyDevelopment: "Adipose brown fat develops beneath skin for temperature insulation. Skeleton turns from soft cartilage to firm bone.",
    motherChanges: "Center of gravity shifts forward. Appetite expands significantly.",
    commonSymptoms: ["Increased body heat & sweating", "Mild ankle swelling", "Vivid dreams"],
    keyAdvice: "Wear supportive low-heeled footwear to cushion joint strain.",
  },
  18: {
    week: 18,
    sizeAnalogy: "Artichoke",
    lengthCm: 14.2,
    lengthInches: 5.59,
    weightGrams: 190.0,
    weightOunces: "6.70 oz",
    babyDevelopment: "Auditory system matures—baby can hear mother's heartbeat, voice, and tummy gurgles!",
    motherChanges: "Quickening! You may feel gentle butterly flutters in lower belly.",
    commonSymptoms: ["Fluttering movements", "Low blood pressure", "Leg cramps"],
    keyAdvice: "Talk, sing, and play gentle music to bond with your developing baby.",
  },
  19: {
    week: 19,
    sizeAnalogy: "Mango",
    lengthCm: 15.3,
    lengthInches: 6.02,
    weightGrams: 240.0,
    weightOunces: "8.47 oz",
    babyDevelopment: "Vernix caseosa (protective white waxy coating) covers skin to protect against amniotic fluid.",
    motherChanges: "Skin pigmentation changes (melasma/chloasma mask of pregnancy) may appear.",
    commonSymptoms: ["Hip joint soreness", "Abdominal skin itching", "Dry eyes"],
    keyAdvice: "Apply gentle mineral sunscreen and moisturize stretching belly skin.",
  },
  20: {
    week: 20,
    sizeAnalogy: "Banana",
    lengthCm: 25.6,
    lengthInches: 10.08,
    weightGrams: 300.0,
    weightOunces: "10.58 oz",
    babyDevelopment: "Halfway point! Baby swallows amniotic fluid actively, practicing digestive tract processing.",
    motherChanges: "Top of uterus reaches belly button. Mid-pregnancy anatomy scan week!",
    commonSymptoms: ["Clear baby movements", "Heartburn", "Mild edema"],
    keyAdvice: "Celebrate reaching the 20-week half milestone!",
  },
  21: {
    week: 21,
    sizeAnalogy: "Carrot",
    lengthCm: 26.7,
    lengthInches: 10.51,
    weightGrams: 360.0,
    weightOunces: "12.70 oz",
    babyDevelopment: "Bone marrow takes over RBC production. Taste buds develop on tongue.",
    motherChanges: "Braxton Hicks practice contractions may start occasionally.",
    commonSymptoms: ["Braxton Hicks tightness", "Stretch marks appearing", "Varicose veins"],
    keyAdvice: "Stay hydrated and elevate feet when resting.",
  },
  22: {
    week: 22,
    sizeAnalogy: "Papaya",
    lengthCm: 27.8,
    lengthInches: 10.94,
    weightGrams: 430.0,
    weightOunces: "15.17 oz",
    babyDevelopment: "Tactile senses active—baby touches face, umbilical cord, and explores uterine surroundings.",
    motherChanges: "Increased blood circulation can boost skin oiliness.",
    commonSymptoms: ["Protruding belly button", "Foot size growth", "Increased libido"],
    keyAdvice: "Wear comfortable compression socks if experiencing leg swelling.",
  },
  23: {
    week: 23,
    sizeAnalogy: "Eggplant",
    lengthCm: 28.9,
    lengthInches: 11.38,
    weightGrams: 501.0,
    weightOunces: "1.10 lbs",
    babyDevelopment: "Lungs develop blood vessels for air breathing preparation. Hearing picks up external sounds clearly.",
    motherChanges: "Weight gain accelerates steadily (~1 lb/week).",
    commonSymptoms: ["Swollen ankles/feet", "Snoring", "Restless leg sensation"],
    keyAdvice: "Avoid lying flat on back; sleep on left side to optimize placental blood flow.",
  },
  24: {
    week: 24,
    sizeAnalogy: "Cantaloupe",
    lengthCm: 30.0,
    lengthInches: 11.81,
    weightGrams: 600.0,
    weightOunces: "1.32 lbs",
    babyDevelopment: "Viability Milestone! Surfactant production begins in lung alveoli.",
    motherChanges: "Uterus reaches 2 inches above belly button.",
    commonSymptoms: ["Itchy skin", "Dry eyes", "Glucose test prep"],
    keyAdvice: "Schedule your 1-hour Gestational Diabetes Screening test.",
  },
  25: {
    week: 25,
    sizeAnalogy: "Cauliflower",
    lengthCm: 34.6,
    lengthInches: 13.62,
    weightGrams: 660.0,
    weightOunces: "1.46 lbs",
    babyDevelopment: "Capillaries form beneath skin, giving baby a healthy pinkish complexion. Nostrils open.",
    motherChanges: "Hair loss decreases; locks appear thick and shiny.",
    commonSymptoms: ["Hemorrhoids", "Restless sleep", "Carpal tunnel tingling"],
    keyAdvice: "Perform gentle wrist stretches and eat high-fiber foods.",
  },
  26: {
    week: 26,
    sizeAnalogy: "Acorn Squash",
    lengthCm: 35.6,
    lengthInches: 14.02,
    weightGrams: 760.0,
    weightOunces: "1.68 lbs",
    babyDevelopment: "Eyes open for the first time! Retinal nerves respond to bright light sources against abdomen.",
    motherChanges: "Rib cage expands to accommodate rising uterus.",
    commonSymptoms: ["Rib pain", "Insomnia", "Mild pelvic pressure"],
    keyAdvice: "Practice calming breathing techniques and prenatal yoga.",
  },
  27: {
    week: 27,
    sizeAnalogy: "Head of Lettuce",
    lengthCm: 36.6,
    lengthInches: 14.41,
    weightGrams: 875.0,
    weightOunces: "1.93 lbs",
    babyDevelopment: "Final week of Second Trimester! Brain wave activity matches REM sleep cycles—baby is dreaming!",
    motherChanges: "Rh factor antibody blood test window if Rh-negative.",
    commonSymptoms: ["Leg cramps at night", "Shortness of breath", "Back strain"],
    keyAdvice: "Ensure adequate calcium and magnesium intake for muscle health.",
  },
  28: {
    week: 28,
    sizeAnalogy: "Eggplant / Large Mango",
    lengthCm: 37.6,
    lengthInches: 14.80,
    weightGrams: 1000.0,
    weightOunces: "2.20 lbs",
    babyDevelopment: "Third Trimester Begins! Baby blinks, turns head, and stores body fat reserves.",
    motherChanges: "Prenatal visits increase to bi-weekly intervals.",
    commonSymptoms: ["Sciatica discomfort", "Tight abdomen", "Braxton Hicks"],
    keyAdvice: "Start tracking daily fetal kick counts (10 movements in 2 hours).",
  },
  29: {
    week: 29,
    sizeAnalogy: "Butternut Squash",
    lengthCm: 38.6,
    lengthInches: 15.20,
    weightGrams: 1150.0,
    weightOunces: "2.54 lbs",
    babyDevelopment: "Muscles and lungs continue maturing. Head grows to accommodate rapidly developing brain.",
    motherChanges: "Increased pressure on diaphragm and stomach.",
    commonSymptoms: ["Heartburn & acid reflux", "Frequent urination returning", "Fatigue"],
    keyAdvice: "Eat smaller meals and avoid reclining immediately after eating.",
  },
  30: {
    week: 30,
    sizeAnalogy: "Cabbage",
    lengthCm: 39.9,
    lengthInches: 15.71,
    weightGrams: 1319.0,
    weightOunces: "2.91 lbs",
    babyDevelopment: "Amniotic fluid peaks as baby grows to fill uterine space.",
    motherChanges: "Ligaments loosen under relaxin hormone, causing pelvic waddling gait.",
    commonSymptoms: ["Moodiness", "Shortness of breath", "Swollen feet"],
    keyAdvice: "Keep feet elevated and take frequent short walking breaks.",
  },
  31: {
    week: 31,
    sizeAnalogy: "Coconut",
    lengthCm: 41.1,
    lengthInches: 16.18,
    weightGrams: 1502.0,
    weightOunces: "3.31 lbs",
    babyDevelopment: "Baby processes information, tracks light, and perceives all five sensory inputs.",
    motherChanges: "Colostrum (early milk) may leak from breasts.",
    commonSymptoms: ["Breast leaking", "Braxton Hicks", "Back pain"],
    keyAdvice: "Use nursing pads in your bra if colostrum leaking occurs.",
  },
  32: {
    week: 32,
    sizeAnalogy: "Jicama",
    lengthCm: 42.4,
    lengthInches: 16.69,
    weightGrams: 1702.0,
    weightOunces: "3.75 lbs",
    babyDevelopment: "Toenails & fingernails fully grown. Lanugo fine body hair starts shedding.",
    motherChanges: "Blood volume is 40-50% higher than pre-pregnancy baseline.",
    commonSymptoms: ["Pelvic heaviness", "Constipation", "Lightheadedness"],
    keyAdvice: "Finalize your hospital bag packing list and birth plan preferences.",
  },
  33: {
    week: 33,
    sizeAnalogy: "Pineapple",
    lengthCm: 43.7,
    lengthInches: 17.20,
    weightGrams: 1918.0,
    weightOunces: "4.23 lbs",
    babyDevelopment: "Immune system antibodies transfer from mother to baby. Skull bones remain soft & flexible.",
    motherChanges: "Amniotic fluid volume stabilizes, letting you feel sharp elbow/knee jabs.",
    commonSymptoms: ["Overheating", "Insomnia", "Clumsiness"],
    keyAdvice: "Install and verify your infant car seat with a certified inspector.",
  },
  34: {
    week: 34,
    sizeAnalogy: "Cantaloupe / Honeydew",
    lengthCm: 45.0,
    lengthInches: 17.72,
    weightGrams: 2146.0,
    weightOunces: "4.73 lbs",
    babyDevelopment: "Central nervous system & lungs reach advanced maturity.",
    motherChanges: "Fatigue returns similarly to First Trimester.",
    commonSymptoms: ["Tiredness", "Vision dryness", "Pelvic pressure"],
    keyAdvice: "Discuss group B strep (GBS) swab testing with your provider.",
  },
  35: {
    week: 35,
    sizeAnalogy: "Honeydew Melon",
    lengthCm: 46.2,
    lengthInches: 18.19,
    weightGrams: 2383.0,
    weightOunces: "5.25 lbs",
    babyDevelopment: "Kidneys fully developed; liver begins processing waste products.",
    motherChanges: "Uterus reaches underneath rib cage.",
    commonSymptoms: ["Severe pelvic pressure", "Frequent night urination", "Acid reflux"],
    keyAdvice: "Learn early signs of true labor vs. Braxton Hicks contractions.",
  },
  36: {
    week: 36,
    sizeAnalogy: "Romaine Lettuce",
    lengthCm: 47.4,
    lengthInches: 18.66,
    weightGrams: 2622.0,
    weightOunces: "5.78 lbs",
    babyDevelopment: "Baby gains ~0.5 lb per week. Most babies settle into head-down (vertex) position.",
    motherChanges: "Lightening! Baby drops deeper into pelvis, making breathing easier.",
    commonSymptoms: ["Increased pelvic pressure", "Easier breathing", "Urinary frequency"],
    keyAdvice: "Weekly prenatal visits begin from Week 36 onward until delivery.",
  },
  37: {
    week: 37,
    sizeAnalogy: "Swiss Chard",
    lengthCm: 48.6,
    lengthInches: 19.13,
    weightGrams: 2859.0,
    weightOunces: "6.30 lbs",
    babyDevelopment: "Early Term Milestone! Baby is fully formed and ready to breathe outside womb.",
    motherChanges: "Cervix begins effacing (thinning) and dilating.",
    commonSymptoms: ["Mucus plug loss", "Increased vaginal discharge", "Diarrhea (body prepping)"],
    keyAdvice: "Keep hospital bag in car and ensure partner emergency contacts are ready.",
  },
  38: {
    week: 38,
    sizeAnalogy: "Winter Squash",
    lengthCm: 49.8,
    lengthInches: 19.61,
    weightGrams: 3083.0,
    weightOunces: "6.80 lbs",
    babyDevelopment: "Organ systems ready for birth. Vocal cords strong for first cry.",
    motherChanges: "Breasts produce rich colostrum ready for immediate nursing.",
    commonSymptoms: ["Bloody show / mucus plug", "Strong contractions", "Swollen ankles"],
    keyAdvice: "Time contractions: 5 minutes apart, 1 minute long, for 1 hour (5-1-1 rule).",
  },
  39: {
    week: 39,
    sizeAnalogy: "Watermelon",
    lengthCm: 50.7,
    lengthInches: 19.96,
    weightGrams: 3288.0,
    weightOunces: "7.25 lbs",
    babyDevelopment: "Full Term Milestone! Optimal brain and lung development achieved.",
    motherChanges: "Pelvis expands to maximum readiness for delivery.",
    commonSymptoms: ["Impatience", "Frequent contractions", "Nest building instinct"],
    keyAdvice: "Rest and stay calm; your body knows how to give birth!",
  },
  40: {
    week: 40,
    sizeAnalogy: "Small Pumpkin",
    lengthCm: 51.2,
    lengthInches: 20.16,
    weightGrams: 3462.0,
    weightOunces: "7.63 lbs",
    babyDevelopment: "Estimated Due Date Week! 15% of babies arrive this week.",
    motherChanges: "Cervix dilated and effaced.",
    commonSymptoms: ["Contractions", "Water breaking (amniotic rupture)", "Back labor"],
    keyAdvice: "Contact your labor & delivery triage unit when regular contractions begin.",
  },
  41: {
    week: 41,
    sizeAnalogy: "Large Pumpkin",
    lengthCm: 51.7,
    lengthInches: 20.35,
    weightGrams: 3597.0,
    weightOunces: "7.93 lbs",
    babyDevelopment: "Late Term. Skin may be slightly drier as vernix sheds completely.",
    motherChanges: "Provider performs non-stress test (NST) and amniotic fluid check.",
    commonSymptoms: ["Heaviness", "Anxiety", "Strong Braxton Hicks"],
    keyAdvice: "Discuss gentle induction options with your OB-GYN or midwife.",
  },
  42: {
    week: 42,
    sizeAnalogy: "Watermelon / Jackfruit",
    lengthCm: 52.0,
    lengthInches: 20.47,
    weightGrams: 3685.0,
    weightOunces: "8.12 lbs",
    babyDevelopment: "Post-Term. Baby is fully mature; placental efficiency monitored closely.",
    motherChanges: "Medical induction scheduled to ensure safest delivery outcome.",
    commonSymptoms: ["Fatigue", "Frequent contractions"],
    keyAdvice: "Trust your care team as they guide your delivery journey safely.",
  },
};
