import { CagrFormulaInput, CagrFormulaResult } from "@/lib/calculator-engine/formulas/cagr";
import { CalculatorReportData } from "@/components/report/types";
import { formatCurrency } from "@/lib/calculator-engine/formatters";

export function generateCagrReportData(
  inputs: CagrFormulaInput,
  results: CagrFormulaResult
): CalculatorReportData {
  const now = new Date();
  const generatedDate = now.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  const generatedTime = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const keyMetrics = [
    {
      label: "COMPOUND ANNUAL GROWTH RATE (CAGR)",
      value: `${results.cagrPercent}%`,
      colorTheme: "blue" as const,
    },
    {
      label: "TOTAL ABSOLUTE RETURN",
      value: `${results.absoluteReturnPercent}%`,
      colorTheme: "emerald" as const,
    },
    {
      label: "TOTAL DOLLAR PROFIT",
      value: formatCurrency(results.totalProfit),
      colorTheme: "purple" as const,
    },
    {
      label: "WEALTH MULTIPLIER",
      value: `${results.wealthMultiplier}x`,
      colorTheme: "amber" as const,
    },
  ];

  const inputItems = [
    {
      label: "Calculation Mode",
      value: (inputs.cagrType || "standard").toUpperCase(),
    },
    {
      label: "Initial Investment Capital (PV)",
      value: formatCurrency(results.initialValue),
    },
    {
      label: "Final Investment Value (FV)",
      value: formatCurrency(results.finalValue),
    },
    {
      label: "Investment Tenure",
      value: `${results.years} Years`,
    },
    {
      label: "Inflation Rate Assumption",
      value: `${inputs.inflationRate || 4}% / year`,
    },
    {
      label: "Capital Gains Tax Slab",
      value: `${inputs.taxRate || 15}%`,
    },
  ];

  const outputItems = [
    {
      label: "Compound Annual Growth Rate (CAGR)",
      value: `${results.cagrPercent}%`,
      highlight: true,
    },
    {
      label: "Total Absolute Return",
      value: `${results.absoluteReturnPercent}%`,
    },
    {
      label: "Net Capital Profit / Gain",
      value: formatCurrency(results.totalProfit),
      highlight: true,
    },
    {
      label: "Inflation-Adjusted Real CAGR",
      value: `${results.realCagrPercent}%`,
    },
    {
      label: "Real Purchasing Power (Inflation-Adjusted)",
      value: formatCurrency(results.realEndingValue),
    },
    {
      label: "Post-Tax Net Final Value",
      value: formatCurrency(results.postTaxFinalValue),
    },
    {
      label: "Portfolio Performance Rating",
      value: `${results.healthRating} (${results.cagrHealthScore}/100)`,
    },
  ];

  // Schedule Table Preview (First 5 Years)
  const scheduleRows = results.annualSchedule.slice(0, 5).map((row) => ({
    year: `Year ${row.year}`,
    start: formatCurrency(row.startingValue),
    growth: formatCurrency(row.annualGrowth),
    ending: formatCurrency(row.endingValue),
    realEnding: formatCurrency(row.realEndingValue),
    returnPct: `${row.cumulativeReturnPercent}%`,
  }));

  const tableData = {
    title: "3. 5-YEAR COMPOUNDED GROWTH TRAJECTORY PREVIEW",
    headers: [
      { key: "year", label: "Year", align: "left" as const },
      { key: "start", label: "Starting Capital", align: "right" as const },
      { key: "growth", label: "Annual Growth ($)", align: "right" as const },
      { key: "ending", label: "Nominal Ending Value", align: "right" as const },
      { key: "realEnding", label: "Real Value (Purchasing Power)", align: "right" as const },
      { key: "returnPct", label: "Cumulative Return", align: "right" as const },
    ],
    rows: scheduleRows,
  };

  return {
    meta: {
      calculatorName: "Compound Annual Growth Rate (CAGR) Performance Report",
      reportTitle: "CAGR & COMPOUND INVESTMENT AUDIT REPORT",
      generatedDate,
      generatedTime,
    },
    keyMetrics,
    sections: [
      {
        title: "1. INVESTMENT PARAMETERS & ASSUMPTIONS",
        items: inputItems,
      },
      {
        title: "2. ANNUALIZED PERFORMANCE SUMMARY",
        items: outputItems,
      },
    ],
    table: tableData,
    notes: [
      "This financial audit report is generated by CalcPlatform's CAGR Engine.",
      "CAGR represents the smoothed annual rate of growth required for an investment to grow from its initial value to its final value over a specified time frame.",
      "Inflation adjustments evaluate real purchasing power, and capital gains tax deductions reflect estimated net post-tax wealth.",
    ],
  };
}
