import { FdFormulaInput, FdFormulaResult } from "@/lib/calculator-engine/formulas/fd";
import { CalculatorReportData } from "@/components/report/types";
import { formatCurrency } from "@/lib/calculator-engine/formatters";

export function generateFdReportData(
  inputs: FdFormulaInput,
  results: FdFormulaResult
): CalculatorReportData {
  const now = new Date();
  const generatedDate = now.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  const generatedTime = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const isSenior = !!inputs.isSeniorCitizen;
  const isNonCumulative = inputs.fdType === "non-cumulative";

  const keyMetrics = [
    {
      label: "TOTAL MATURITY VALUE",
      value: formatCurrency(results.maturityAmount),
      colorTheme: "blue" as const,
    },
    {
      label: "TOTAL PRINCIPAL DEPOSIT",
      value: formatCurrency(results.depositAmount),
      colorTheme: "purple" as const,
    },
    {
      label: "ESTIMATED INTEREST EARNED",
      value: formatCurrency(results.totalInterestEarned),
      colorTheme: "emerald" as const,
    },
    {
      label: "EFFECTIVE APY YIELD",
      value: `${results.effectiveApy}%`,
      colorTheme: "amber" as const,
    },
  ];

  const inputItems = [
    {
      label: "Fixed Deposit Type",
      value: (inputs.fdType || "cumulative").toUpperCase(),
    },
    {
      label: "Principal Deposit Amount",
      value: formatCurrency(inputs.depositAmount || 10000),
    },
    {
      label: "Base Interest Rate (p.a.)",
      value: `${results.interestRate}% ${isSenior ? "(Includes +0.50% Senior Citizen Bonus)" : ""}`,
    },
    {
      label: "Investment Tenure",
      value: `${inputs.tenureYears || 5} Years`,
    },
    {
      label: "Compounding Frequency",
      value: (inputs.compoundingFrequency || "quarterly").toUpperCase(),
    },
    {
      label: "Senior Citizen Status",
      value: isSenior ? "YES (+0.50% Applied)" : "Standard Investor",
    },
    {
      label: "TDS / Tax Drag Assumption",
      value: `${inputs.taxRate || 10}%`,
    },
  ];

  const outputItems = [
    {
      label: "Gross Maturity Value",
      value: formatCurrency(results.maturityAmount),
      highlight: true,
    },
    {
      label: "Principal Deposited",
      value: formatCurrency(results.depositAmount),
    },
    {
      label: "Total Net Interest Earned",
      value: formatCurrency(results.totalInterestEarned),
      highlight: true,
    },
    ...(isNonCumulative
      ? [
          {
            label: "Periodic Payout Stream",
            value: `${formatCurrency(results.periodicPayoutAmount)} / payout`,
          },
        ]
      : []),
    {
      label: "Real Purchasing Power (Inflation-Adjusted)",
      value: formatCurrency(results.inflationAdjustedValue),
    },
    {
      label: "Post-Tax Net Maturity Value",
      value: formatCurrency(results.postTaxMaturityAmount),
    },
    {
      label: "Total Estimated TDS / Tax Obligation",
      value: formatCurrency(results.totalTaxPaid),
    },
    {
      label: "FD Safety & Health Score",
      value: `${results.healthRating} (${results.fdHealthScore}/100)`,
    },
  ];

  // Schedule Table Preview (First 5 Years)
  const scheduleRows = results.annualSchedule.slice(0, 5).map((row) => ({
    year: `Year ${row.year}`,
    starting: formatCurrency(row.startingBalance),
    interest: formatCurrency(row.cumulativeInterest),
    ending: formatCurrency(row.endingBalance),
    realEnding: formatCurrency(row.realEndingBalance),
  }));

  const tableData = {
    title: "3. 5-YEAR FIXED DEPOSIT GROWTH PREVIEW",
    headers: [
      { key: "year", label: "Year", align: "left" as const },
      { key: "starting", label: "Starting Balance", align: "right" as const },
      { key: "interest", label: "Cumulative Interest", align: "right" as const },
      { key: "ending", label: "Ending Balance", align: "right" as const },
      { key: "realEnding", label: "Inflation-Adjusted", align: "right" as const },
    ],
    rows: scheduleRows,
  };

  return {
    meta: {
      calculatorName: "Fixed Deposit (FD) Maturity & Interest Report",
      reportTitle: "FIXED DEPOSIT (FD) FINANCIAL AUDIT REPORT",
      generatedDate,
      generatedTime,
    },
    keyMetrics,
    sections: [
      {
        title: "1. DEPOSIT PARAMETERS & APPLIED RATES",
        items: inputItems,
      },
      {
        title: "2. MATURITY PROJECTION SUMMARY",
        items: outputItems,
      },
    ],
    table: tableData,
    notes: [
      "This financial audit report is generated by CalcPlatform's Fixed Deposit Engine.",
      "Calculations use quarterly compounding interest equations: A = P(1 + r/n)^(nt).",
      "Interest rates are subject to individual commercial bank terms, RBI policy rates, and tax deduction thresholds (TDS under Section 194A).",
    ],
  };
}
