import { CalculatorDefinition, CalculationResult } from "@/lib/calculator-engine/types";
import { CalculatorReportData } from "@/components/report/types";

export function generateGenericReportData(
  definition: Omit<CalculatorDefinition, "calculate">,
  inputs: Record<string, any>,
  result: CalculationResult
): CalculatorReportData {
  const now = new Date();
  const generatedDate = now.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  const generatedTime = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const safeInputs = inputs || {};
  const safeFormatted = result?.formatted || {};
  const inputDefs = definition?.inputs || [];
  const outputDefs = definition?.outputs || [];

  const inputItems = inputDefs.map((inDef) => ({
    label: inDef.label,
    value: `${safeInputs[inDef.name] ?? inDef.defaultValue ?? ""} ${inDef.unit || ""}`.trim(),
  }));

  const outputItems = outputDefs.map((outDef) => ({
    label: outDef.label,
    value: `${safeFormatted[outDef.name] || "0"} ${outDef.unit || ""}`.trim(),
    highlight: !!outDef.highlight,
  }));

  const keyMetrics = outputDefs.slice(0, 4).map((outDef) => ({
    label: outDef.label,
    value: `${safeFormatted[outDef.name] || "0"} ${outDef.unit || ""}`.trim(),
  }));

  const title = definition?.title || "Calculator";

  return {
    meta: {
      calculatorName: title,
      reportTitle: `${title.toUpperCase()} ANALYSIS REPORT`,
      generatedDate,
      generatedTime,
    },
    keyMetrics,
    sections: [
      {
        title: "CALCULATOR INPUT PARAMETERS",
        items: inputItems,
      },
      {
        title: "CALCULATED RESULTS SUMMARY",
        items: outputItems,
      },
    ],
    notes: [
      `Generated by CalcPlatform ${title} engine.`,
      "Results are calculated based on standard formulas for estimation purposes.",
    ],
  };
}
