import { RdFormulaInput, RdFormulaResult } from "@/lib/calculator-engine/formulas/rd";
import { CalculatorReportData } from "@/components/report/types";
import { formatCurrency } from "@/lib/calculator-engine/formatters";

export function generateRdReportData(
  inputs: RdFormulaInput,
  results: RdFormulaResult
): CalculatorReportData {
  const now = new Date();
  const generatedDate = now.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  const generatedTime = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const isSenior = !!inputs.isSeniorCitizen;
  const isStepUp = inputs.rdType === "stepup";

  const keyMetrics = [
    {
      label: "TOTAL MATURITY VALUE",
      value: formatCurrency(results.maturityAmount),
      colorTheme: "blue" as const,
    },
    {
      label: "TOTAL INVESTED CAPITAL",
      value: formatCurrency(results.totalInvested),
      colorTheme: "purple" as const,
    },
    {
      label: "ESTIMATED INTEREST EARNED",
      value: formatCurrency(results.totalInterestEarned),
      colorTheme: "emerald" as const,
    },
    {
      label: "EFFECTIVE APY YIELD",
      value: `${results.effectiveApy}%`,
      colorTheme: "amber" as const,
    },
  ];

  const inputItems = [
    {
      label: "Recurring Deposit Type",
      value: (inputs.rdType || "regular").toUpperCase(),
    },
    {
      label: "Monthly Deposit Amount",
      value: `${formatCurrency(inputs.monthlyDeposit || 500)} / month`,
    },
    {
      label: "Base Interest Rate (p.a.)",
      value: `${results.interestRate}% ${isSenior ? "(Includes +0.50% Senior Citizen Bonus)" : ""}`,
    },
    {
      label: "Investment Tenure",
      value: `${(inputs.tenureMonths || 24) / 12} Years (${inputs.tenureMonths || 24} Months)`,
    },
    ...(isStepUp
      ? [
          {
            label: "Annual Step-Up Rate",
            value: `${inputs.stepUpRate || 0}% / year`,
          },
        ]
      : []),
    {
      label: "Senior Citizen Status",
      value: isSenior ? "YES (+0.50% Applied)" : "Standard Saver",
    },
    {
      label: "TDS / Tax Drag Assumption",
      value: `${inputs.taxRate || 10}%`,
    },
  ];

  const outputItems = [
    {
      label: "Gross Maturity Value",
      value: formatCurrency(results.maturityAmount),
      highlight: true,
    },
    {
      label: "Total Invested Principal",
      value: formatCurrency(results.totalInvested),
    },
    {
      label: "Net Interest Earned",
      value: formatCurrency(results.totalInterestEarned),
      highlight: true,
    },
    {
      label: "Real Purchasing Power (Inflation-Adjusted)",
      value: formatCurrency(results.inflationAdjustedValue),
    },
    {
      label: "Post-Tax Net Maturity Value",
      value: formatCurrency(results.postTaxMaturityAmount),
    },
    {
      label: "Total Estimated TDS / Tax Obligation",
      value: formatCurrency(results.totalTaxPaid),
    },
    {
      label: "RD Portfolio Health Rating",
      value: `${results.healthRating} (${results.rdHealthScore}/100)`,
    },
  ];

  // Schedule Table Preview (First 5 Years)
  const scheduleRows = results.annualSchedule.slice(0, 5).map((row) => ({
    year: `Year ${row.year}`,
    invested: formatCurrency(row.cumulativeContributions),
    interest: formatCurrency(row.cumulativeInterest),
    ending: formatCurrency(row.endingBalance),
    realEnding: formatCurrency(row.realEndingBalance),
  }));

  const tableData = {
    title: "3. 5-YEAR RECURRING DEPOSIT GROWTH PREVIEW",
    headers: [
      { key: "year", label: "Year", align: "left" as const },
      { key: "invested", label: "Invested Capital", align: "right" as const },
      { key: "interest", label: "Cumulative Interest", align: "right" as const },
      { key: "ending", label: "Ending Balance", align: "right" as const },
      { key: "realEnding", label: "Inflation-Adjusted", align: "right" as const },
    ],
    rows: scheduleRows,
  };

  return {
    meta: {
      calculatorName: "Recurring Deposit (RD) Maturity & Interest Report",
      reportTitle: "RECURRING DEPOSIT (RD) FINANCIAL AUDIT REPORT",
      generatedDate,
      generatedTime,
    },
    keyMetrics,
    sections: [
      {
        title: "1. RECURRING DEPOSIT PARAMETERS & RATES",
        items: inputItems,
      },
      {
        title: "2. MATURITY PROJECTION SUMMARY",
        items: outputItems,
      },
    ],
    table: tableData,
    notes: [
      "This financial audit report is generated by CalcPlatform's Recurring Deposit Engine.",
      "Calculations use quarterly compounding interest equations applied to monthly installment cash flow streams.",
      "Interest rates are subject to individual commercial bank terms, RBI policy rates, and tax deduction thresholds (TDS under Section 194A).",
    ],
  };
}
