import { RoiFormulaInput, RoiFormulaResult } from "@/lib/calculator-engine/formulas/roi";
import { CalculatorReportData } from "@/components/report/types";
import { formatCurrency } from "@/lib/calculator-engine/formatters";

export function generateRoiReportData(
  inputs: RoiFormulaInput,
  results: RoiFormulaResult
): CalculatorReportData {
  const now = new Date();
  const generatedDate = now.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  const generatedTime = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const keyMetrics = [
    {
      label: "TOTAL RETURN ON INVESTMENT (ROI)",
      value: `${results.roiPercent}%`,
      colorTheme: "blue" as const,
    },
    {
      label: "ANNUALIZED ROI",
      value: `${results.annualizedRoiPercent}%`,
      colorTheme: "emerald" as const,
    },
    {
      label: "NET DOLLAR PROFIT / GAIN",
      value: formatCurrency(results.netProfit),
      colorTheme: "purple" as const,
    },
    {
      label: "WEALTH MULTIPLIER",
      value: `${results.wealthMultiplier}x`,
      colorTheme: "amber" as const,
    },
  ];

  const inputItems = [
    {
      label: "Calculation Mode",
      value: (inputs.roiType || "standard").toUpperCase(),
    },
    {
      label: "Amount Invested (Initial Capital / PV)",
      value: formatCurrency(results.amountInvested),
    },
    {
      label: "Amount Returned (Final Value / FV)",
      value: formatCurrency(results.amountReturned),
    },
    {
      label: "Investment Tenure",
      value: `${results.years} Years (${inputs.timeMode === "dates" ? `From ${inputs.fromDate} To ${inputs.toDate}` : "Length in Years"})`,
    },
    {
      label: "Inflation Rate Assumption",
      value: `${inputs.inflationRate || 4}% / year`,
    },
    {
      label: "Capital Gains Tax Rate",
      value: `${inputs.taxRate || 15}%`,
    },
  ];

  const outputItems = [
    {
      label: "Total Return on Investment (ROI)",
      value: `${results.roiPercent}%`,
      highlight: true,
    },
    {
      label: "Annualized ROI (Geometric Compound)",
      value: `${results.annualizedRoiPercent}%`,
      highlight: true,
    },
    {
      label: "Net Dollar Gain / Profit",
      value: formatCurrency(results.netProfit),
      highlight: true,
    },
    {
      label: "Inflation-Adjusted Real Annualized ROI",
      value: `${results.realAnnualizedRoiPercent}%`,
    },
    {
      label: "Real Purchasing Power (Inflation-Adjusted)",
      value: formatCurrency(results.realEndingValue),
    },
    {
      label: "Post-Tax Net Final Value",
      value: formatCurrency(results.postTaxFinalValue),
    },
    {
      label: "Investment Health Rating",
      value: `${results.healthRating} (${results.roiHealthScore}/100)`,
    },
  ];

  // Schedule Table Preview (First 5 Years)
  const scheduleRows = results.annualSchedule.slice(0, 5).map((row: any) => ({
    year: `Year ${row.year}`,
    start: formatCurrency(row.startingValue),
    growth: formatCurrency(row.annualGrowth),
    ending: formatCurrency(row.endingValue),
    realEnding: formatCurrency(row.realEndingValue),
    roiPct: `${row.cumulativeRoiPercent}%`,
  }));

  const tableData = {
    title: "3. 5-YEAR COMPOUNDED GROWTH TRAJECTORY PREVIEW",
    headers: [
      { key: "year", label: "Year", align: "left" as const },
      { key: "start", label: "Starting Capital", align: "right" as const },
      { key: "growth", label: "Annual Growth ($)", align: "right" as const },
      { key: "ending", label: "Nominal Ending Value", align: "right" as const },
      { key: "realEnding", label: "Real Value (Purchasing Power)", align: "right" as const },
      { key: "roiPct", label: "Cumulative ROI", align: "right" as const },
    ],
    rows: scheduleRows,
  };

  return {
    meta: {
      calculatorName: "Return on Investment (ROI) Performance Report",
      reportTitle: "RETURN ON INVESTMENT (ROI) FINANCIAL AUDIT REPORT",
      generatedDate,
      generatedTime,
    },
    keyMetrics,
    sections: [
      {
        title: "1. INVESTMENT PARAMETERS & ASSUMPTIONS",
        items: inputItems,
      },
      {
        title: "2. ANNUALIZED PERFORMANCE & PROFITABILITY SUMMARY",
        items: outputItems,
      },
    ],
    table: tableData,
    notes: [
      "This financial audit report is generated by CalcPlatform's ROI Engine.",
      "ROI measures net capital efficiency relative to initial investment cost. Annualized ROI normalizes growth over time using geometric compounding.",
      "Inflation adjustments evaluate real purchasing power, and capital gains tax deductions reflect estimated net post-tax returns.",
    ],
  };
}
