import { SipFormulaInput, SipFormulaResult } from "@/lib/calculator-engine/formulas/sip";
import { CalculatorReportData } from "@/components/report/types";
import { formatCurrency } from "@/lib/calculator-engine/formatters";

export function generateSipReportData(
  inputs: SipFormulaInput,
  results: SipFormulaResult
): CalculatorReportData {
  const now = new Date();
  const generatedDate = now.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  const generatedTime = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const isLumpsum = inputs.investmentType === "lumpsum";
  const isStepUp = inputs.investmentType === "stepup";

  const keyMetrics = [
    {
      label: "TOTAL MATURITY VALUE",
      value: formatCurrency(results.totalMaturityValue),
      colorTheme: "blue" as const,
    },
    {
      label: "TOTAL INVESTED CAPITAL",
      value: formatCurrency(results.totalInvested),
      colorTheme: "purple" as const,
    },
    {
      label: "ESTIMATED WEALTH RETURNS",
      value: formatCurrency(results.estimatedReturns),
      colorTheme: "emerald" as const,
    },
    {
      label: "WEALTH MULTIPLIER",
      value: `${results.wealthMultiplier}x`,
      colorTheme: "amber" as const,
    },
  ];

  const inputItems = [
    {
      label: "Investment Mode",
      value: (inputs.investmentType || "sip").toUpperCase(),
    },
    {
      label: isLumpsum ? "Lumpsum Deposit" : "Monthly Investment (SIP)",
      value: formatCurrency(isLumpsum ? inputs.lumpsumAmount || 10000 : inputs.monthlyInvestment || 500),
    },
    {
      label: "Expected Return Rate (p.a.)",
      value: `${inputs.expectedReturnRate || 12}%`,
    },
    {
      label: "Investment Tenure",
      value: `${inputs.timePeriodYears || 10} Years`,
    },
    ...(isStepUp
      ? [
          {
            label: "Annual Step-Up Rate",
            value: `${inputs.stepUpRate || 0}% / year`,
          },
        ]
      : []),
    {
      label: "Inflation Rate Assumption",
      value: `${inputs.inflationRate || 4}%`,
    },
    {
      label: "Estimated Tax Drag",
      value: `${inputs.taxRate || 10}% on capital gains`,
    },
  ];

  const outputItems = [
    {
      label: "Gross Maturity Corpus",
      value: formatCurrency(results.totalMaturityValue),
      highlight: true,
    },
    {
      label: "Total Invested Principal",
      value: formatCurrency(results.totalInvested),
    },
    {
      label: "Net Wealth Created (Gains)",
      value: formatCurrency(results.estimatedReturns),
      highlight: true,
    },
    {
      label: "Real Purchasing Power (Inflation-Adjusted)",
      value: formatCurrency(results.inflationAdjustedValue),
    },
    {
      label: "Post-Tax Net Maturity Value",
      value: formatCurrency(results.postTaxMaturityValue),
    },
    {
      label: "Total Estimated Tax Obligation",
      value: formatCurrency(results.totalTaxPaid),
    },
    {
      label: "Portfolio Health Rating",
      value: `${results.healthRating} (${results.sipHealthScore}/100)`,
    },
  ];

  // Schedule Table Preview (First 5 Years)
  const scheduleRows = results.annualSchedule.slice(0, 5).map((row) => ({
    year: `Year ${row.year}`,
    invested: formatCurrency(row.cumulativeContributions),
    interest: formatCurrency(row.cumulativeInterest),
    ending: formatCurrency(row.endingBalance),
    realEnding: formatCurrency(row.realEndingBalance),
  }));

  const tableData = {
    title: "3. 5-YEAR GROWTH TRAJECTORY PREVIEW",
    headers: [
      { key: "year", label: "Year", align: "left" as const },
      { key: "invested", label: "Invested Capital", align: "right" as const },
      { key: "interest", label: "Interest Earned", align: "right" as const },
      { key: "ending", label: "Ending Balance", align: "right" as const },
      { key: "realEnding", label: "Inflation-Adjusted", align: "right" as const },
    ],
    rows: scheduleRows,
  };

  return {
    meta: {
      calculatorName: "Systematic Investment Plan (SIP) & Wealth Growth Report",
      reportTitle: "SIP & MUTUAL FUND WEALTH PROJECTION REPORT",
      generatedDate,
      generatedTime,
    },
    keyMetrics,
    sections: [
      {
        title: "1. INVESTMENT PARAMETERS & ASSUMPTIONS",
        items: inputItems,
      },
      {
        title: "2. WEALTH PROJECTION SUMMARY",
        items: outputItems,
      },
    ],
    table: tableData,
    notes: [
      "This financial audit report is generated by CalcPlatform's SIP & Wealth Engine.",
      "Calculations use monthly compounding models based on compound interest equations: M = P × [((1+i)^n - 1) / i] × (1+i).",
      "Actual mutual fund market returns fluctuate based on NAV performance, asset allocation, and underlying securities.",
    ],
  };
}
