import { CalculatorModuleDefinition } from "@/calculators/types";
import { calculateBacCalculator } from "./calculator";
import { bacFaqs } from "./faq";

export const bac_calculatorConfig: CalculatorModuleDefinition = {
  id: "bac-calculator",
  slug: "bac-calculator",
  title: "Blood Alcohol Concentration (BAC) Calculator",
  description:
    "Estimate blood alcohol concentration (BAC) from drinks, alcohol strength, body weight and elapsed time. Compare Widmark, Seidl and Watson models and view modeled BAC elimination.",
  category: "health",
  subcategory: "Nutrition & Health",
  iconName: "Activity",
  tags: [
    "bac",
    "blood alcohol",
    "widmark",
    "sobriety",
    "dui limit",
    "alcohol elimination",
    "alcohol calories",
    "drinking calculator",
  ],
  relatedCalculators: [
    "calorie-calculator",
    "body-fat-calculator",
    "lean-body-mass-calculator",
    "ideal-weight-calculator",
    "tdee-calculator",
    "bmi-calculator",
    "body-surface-area-calculator",
  ],
  modes: [
    { id: "widmark-standard", name: "Widmark Standard", description: "Classic Widmark BAC & elimination formula" },
    { id: "driving-sobriety", name: "Driving Sobriety", description: "Legal DUI limits & time to 0.08% / 0.05%" },
    { id: "drink-counter", name: "Session Drink Logger", description: "Multi-drink alcohol mass & peak BAC timing" },
    { id: "elimination-timeline", name: "Elimination Curve", description: "Hour-by-hour sobriety timeline & chart" },
    { id: "gender-weight-matrix", name: "Gender & Weight Matrix", description: "Body weight alcohol sensitivity matrix" },
    { id: "seidl-anthropometric", name: "Seidl Anthropometric", description: "Height & weight adjusted distribution (Seidl 1990)" },
    { id: "watson-tbw", name: "Watson TBW Formula", description: "Total body water clinical distribution equation" },
    { id: "calories-metabolism", name: "Alcohol Calories", description: "Alcohol calorie & carb metabolism counter" },
    { id: "drink-comparison", name: "Drink Type Comparison", description: "Standard drinks vs craft beer, wine, & shots" },
    { id: "custom-toxicology", name: "Custom Evaluation", description: "Custom elimination rate (beta) assessment" },
  ],
  inputs: [
    {
      id: "gender",
      name: "gender",
      label: "Gender",
      type: "select",
      defaultValue: "male",
      options: [
        { label: "Male", value: "male" },
        { label: "Female", value: "female" },
      ],
    },
    {
      id: "weightLbs",
      name: "weightLbs",
      label: "Body Weight (lbs)",
      type: "number",
      defaultValue: 165,
      min: 50,
      max: 500,
      step: 1,
    },
    {
      id: "timeSinceFirstDrinkHours",
      name: "timeSinceFirstDrinkHours",
      label: "Time Since First Drink (Hours)",
      type: "number",
      defaultValue: 2,
      min: 0,
      max: 48,
      step: 0.5,
    },
  ],
  outputs: [
    { id: "currentBacPercent", name: "currentBacPercent", label: "Estimated BAC (%)", type: "number" },
    { id: "peakBacPercent", name: "peakBacPercent", label: "Peak BAC (%)", type: "number" },
    { id: "hoursUntilSober000", name: "hoursUntilSober000", label: "Hours to 0.00% Modeled BAC", type: "number" },
    { id: "hoursUntilLegalLimit008", name: "hoursUntilLegalLimit008", label: "Hours to 0.08% Reference Limit", type: "number" },
  ],
  faqs: bacFaqs.map((f) => ({ question: f.question, answer: f.answer })),
  calculate: (inputs: Record<string, any>) => calculateBacCalculator(inputs as any) as any,
};
