"use client";

import React from "react";
import Link from "next/link";
import {
  TrendingUp,
  Calculator as CalcIcon,
  PieChart,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  Percent,
  Zap,
  Clock,
  DollarSign,
  Scale,
  Award,
  Layers,
  BookOpen,
} from "lucide-react";

export function InterestContent() {
  return (
    <article className="prose dark:prose-invert max-w-none space-y-10 text-zinc-700 dark:text-zinc-300 leading-relaxed text-sm">
      {/* ==========================================
          SECTION 1: OVERVIEW & CORE CONCEPTS
         ========================================== */}
      <section className="space-y-4 bg-white dark:bg-zinc-900 p-6 sm:p-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
        <h2 className="text-xl sm:text-2xl font-black text-blue-600 dark:text-blue-400 flex items-center gap-2 pb-2">
          <TrendingUp className="h-6 w-6 text-blue-600" /> Interest Calculator – Calculate Simple & Compound Interest
        </h2>

        <p className="text-base font-medium text-zinc-800 dark:text-zinc-200 leading-relaxed">
          Interest is easy to describe but surprisingly easy to calculate incorrectly once time, compounding frequency, recurring contributions, taxes, and inflation enter the picture. A balance earning 5% for five years is not necessarily treated the same way as a balance earning 5% with monthly or daily compounding, and an investment that receives regular contributions cannot be analyzed correctly by applying a single percentage to the original deposit. This interest calculator brings those pieces together so you can calculate the future value of money under different interest assumptions and understand exactly where the final balance comes from. Depending on the model you choose, the calculator can account for an initial investment, annual or monthly additions, the compounding frequency, the investment period, tax effects, and inflation-adjusted purchasing power.
        </p>

        <p>
          At the center of the calculation is the difference between principal and interest. Principal is the money initially invested or deposited, while interest is the additional amount generated by the balance according to the stated rate and compounding rules. With simple interest, the interest is calculated from the original principal. With compound interest, previously earned interest becomes part of the balance used for future interest calculations. The Consumer Financial Protection Bureau (CFPB) describes compound interest as earning interest both on the money saved and on the interest earned along the way. That distinction becomes increasingly important over longer periods because each compounding period can increase the base on which later interest is calculated.
        </p>

        <p>
          This is why two accounts can advertise the same nominal annual rate yet produce slightly different ending balances when their compounding schedules differ. Annual, semi-annual, quarterly, monthly, weekly, and daily compounding apply interest at different intervals. Continuous compounding uses an exponential model rather than a finite number of compounding periods. Investor.gov's compound-interest calculator likewise treats the interest rate, compounding frequency, initial investment, contribution amount, and investment period as separate inputs because each changes the resulting projection.
        </p>

        <p>
          Recurring contributions introduce another layer. An investor contributing $500 every month is not making one $6,000 deposit at the very end of the year; each contribution has its own time in the account and therefore its own opportunity to earn interest. The timing of those contributions matters. A contribution made at the beginning of a period generally has one additional opportunity to compound compared with the same contribution made at the end of that period. A useful way to explore that difference is to compare the results in this calculator with the <Link href="/calculators/compound-interest-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Compound Interest Calculator</Link>, while the <Link href="/calculators/savings-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Savings Calculator</Link> is useful when the primary question is how regular saving can build toward a target.
        </p>

        <p>
          The calculator also separates nominal growth from purchasing power. A projected balance may increase substantially in dollar terms while inflation reduces what that balance can buy in the future. Investor.gov defines purchasing power in terms of the goods and services that a given amount of money can purchase after accounting for inflation. This makes an inflation-adjusted value useful when a long-term projection needs to be interpreted in today's purchasing-power terms rather than simply reported as a larger future dollar amount.
        </p>

        <p>
          For borrowers, savers, students, investors, and anyone comparing financial scenarios, the purpose of an interest calculation is therefore not merely to produce a final number. A useful result should reveal how the number was produced: how much principal was supplied, how much interest accumulated, how compounding affected growth, how contributions changed the trajectory, and how taxes or inflation can alter the economic meaning of the final balance. This page is designed around that complete calculation rather than a single headline figure.
        </p>

        <p className="text-xs text-zinc-500 dark:text-zinc-400 pt-2 border-t border-zinc-100 dark:border-zinc-800">
          For connected borrowing calculations, see the <Link href="/calculators/loan-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Loan Calculator</Link> or <Link href="/calculators/payment-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Payment Calculator</Link>. For a rate-focused calculation, the <Link href="/calculators/interest-rate-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Interest Rate Calculator</Link> can be useful, while the <Link href="/calculators/future-value-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Future Value Calculator</Link> focuses specifically on what a current amount can become under defined growth assumptions.
        </p>
      </section>

      {/* ==========================================
          SECTION 2: HOW SIMPLE INTEREST WORKS
         ========================================== */}
      <section className="space-y-4 bg-white dark:bg-zinc-900 p-6 sm:p-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
        <h2 className="text-xl sm:text-2xl font-black text-blue-600 dark:text-blue-400 flex items-center gap-2 pb-2">
          <BookOpen className="h-6 w-6 text-blue-600" /> How Simple Interest Works
        </h2>

        <p>
          Simple interest is the most straightforward interest model because the interest is calculated only from the original principal rather than continually adding earlier interest back into the amount that earns subsequent interest. The standard simple-interest equation is:
        </p>

        <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-center font-mono font-bold text-base text-zinc-900 dark:text-zinc-100">
          I = P &times; r &times; t
        </div>

        <p>
          where <em>I</em> is total interest, <em>P</em> is principal, <em>r</em> is the annual interest rate expressed as a decimal, and <em>t</em> is the time in years. The final amount is then:
        </p>

        <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-center font-mono font-bold text-base text-zinc-900 dark:text-zinc-100">
          A = P + I &emsp;&iff;&emsp; A = P(1 + rt)
        </div>

        <p>
          Consider a $10,000 deposit earning 5% simple interest for five years. The annual rate as a decimal is 0.05, so the accumulated interest is:
        </p>

        <div className="p-3 bg-blue-50 dark:bg-blue-950/40 rounded-lg text-blue-700 dark:text-blue-300 font-mono text-xs font-bold">
          $10,000 &times; 0.05 &times; 5 = $2,500 &emsp;&rarr;&emsp; Ending Balance = $10,000 + $2,500 = $12,500
        </div>

        <p>
          The important feature is that each year contributes the same $500 of interest because the calculation continues to use the original $10,000 principal. The interest earned in Year 1 does not become additional principal for Year 2. This makes simple interest easy to understand and useful for teaching the relationship among principal, rate, and time, but it is not an appropriate model for every real financial product. Whether an account, loan, or other arrangement uses simple or compound interest depends on its actual terms.
        </p>

        <p>
          The rate must also be expressed consistently with the time period. If the annual rate is 5%, the calculation above uses five years. If a calculation uses months, the time period must be converted appropriately or the periodic rate must be used. A common error is combining an annual rate with a number of months as though the units were interchangeable. For example, multiplying 5% by 60 without first expressing 60 months as five years produces a meaningless result.
        </p>

        <p>
          Another useful distinction is between a rate and an amount of interest. A 5% rate is not itself $500 until it is applied to a $10,000 principal. Likewise, $500 of interest does not necessarily imply a 5% return unless the principal and time period are known. The calculator therefore keeps principal, rate, and duration as separate inputs before combining them.
        </p>

        <p>
          Simple interest can also be useful as a benchmark for understanding the effect of compounding. Suppose a $10,000 investment earns 5% for five years. Under simple interest, it grows to $12,500. Under annual compound interest, the same assumptions produce:
        </p>

        <div className="p-3 bg-emerald-50 dark:bg-emerald-950/40 rounded-lg text-emerald-700 dark:text-emerald-300 font-mono text-xs font-bold">
          $10,000 &times; 1.05⁵ = $12,762.82
        </div>

        <p>
          The $262.82 difference is the result of interest itself earning additional interest. This is precisely the mechanism CFPB illustrates when explaining compound interest: the second period's interest is calculated on a balance that already includes earlier interest.
        </p>

        <p>
          Simple interest also provides a valuable zero-rate test. When <em>r</em> = 0, the equation becomes <code>A = P</code> because no interest is generated. A properly implemented calculator should therefore return the original principal rather than producing an undefined result or numerical error.
        </p>

        <p>
          For negative rates, the mathematical equation can also be evaluated, but whether a negative rate represents a meaningful real-world product depends on context. An interest calculator should not silently convert negative input into a positive rate. If negative rates are permitted by the implementation, the resulting reduction should remain mathematically transparent.
        </p>

        <p>
          The biggest advantage of understanding simple interest is conceptual clarity. It gives you a clean baseline against which more sophisticated models can be compared. Once you understand that the original principal remains the interest base, the fundamental difference between simple and compound interest becomes much easier to see. That difference matters more as the investment horizon becomes longer, the rate becomes larger, or the compounding frequency becomes more frequent. Explore simple interest derivations on our <Link href="/calculators/simple-interest-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Simple Interest Calculator</Link>.
        </p>
      </section>

      {/* ==========================================
          SECTION 3: COMPOUND INTEREST & FREQUENCIES
         ========================================== */}
      <section className="space-y-4 bg-white dark:bg-zinc-900 p-6 sm:p-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
        <h2 className="text-xl sm:text-2xl font-black text-blue-600 dark:text-blue-400 flex items-center gap-2 pb-2">
          <Zap className="h-6 w-6 text-blue-600" /> How Compound Interest and Compounding Frequency Change Growth
        </h2>

        <p>
          Compound interest changes the calculation because interest earned in one period can become part of the balance used to calculate interest in later periods. For a lump-sum investment with a nominal annual rate <em>r</em>, compounding <em>n</em> times per year for <em>t</em> years, the standard compound-growth formula is:
        </p>

        <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-center font-mono font-bold text-base text-zinc-900 dark:text-zinc-100">
          A = P(1 + r/n)^(nt)
        </div>

        <p>
          where <em>P</em> is the initial principal, <em>r</em> is the annual nominal rate as a decimal, <em>n</em> is the number of compounding periods per year, and <em>t</em> is the number of years.
        </p>

        <p>
          Suppose $20,000 is invested at 5% for five years. With annual compounding:
        </p>

        <div className="p-3 bg-blue-50 dark:bg-blue-950/40 rounded-lg text-blue-700 dark:text-blue-300 font-mono text-xs font-bold">
          A = $20,000 &times; (1 + 0.05)⁵ = $25,525.63
        </div>

        <p>
          With more frequent compounding, the same nominal rate can produce a somewhat larger balance because interest is added to the account more often. Monthly compounding uses <em>n</em> = 12; daily compounding commonly uses <em>n</em> = 365 in standard calculations; continuous compounding uses:
        </p>

        <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-center font-mono font-bold text-base text-zinc-900 dark:text-zinc-100">
          A = Pe^(rt)
        </div>

        <p>
          rather than the finite-period formula.
        </p>

        <p>
          The important point is that nominal interest rate and effective growth are not always the same thing. A stated annual rate tells you the nominal percentage, but the actual annual growth produced by more frequent compounding can be higher. Increasing compounding frequency does not magically change the stated nominal rate; it changes how often accumulated interest is incorporated into the balance.
        </p>

        <p>
          The Consumer Financial Protection Bureau explicitly notes that increasing compounding frequency, increasing the interest rate, and adding to principal are ways savings can grow faster. Investor.gov similarly provides compounding frequency as a core variable in its compound-interest calculator.
        </p>

        <p>
          This calculator's frequency comparison is therefore useful for understanding an important practical question: How much does the compounding schedule actually matter? Over a short period, the difference between annual and daily compounding may be relatively small. Over a long period, the difference can become more noticeable because each additional compounding opportunity can generate additional interest.
        </p>

        <p>
          There is an important qualification, however. More frequent compounding does not automatically mean a better financial product in every real-world situation. Two products may have different stated rates, fees, withdrawal restrictions, minimum balances, or other terms. Comparing only the compounding frequency can therefore be misleading when evaluating actual products. The calculator is most useful for isolating the mathematical effect of frequency under otherwise identical assumptions.
        </p>

        <p>
          The same framework also explains why long investment horizons amplify relatively small differences in rates. A one-percentage-point difference might look modest when expressed as a single year's rate, but the effect is applied repeatedly over many compounding periods. Conversely, reducing the investment horizon can substantially reduce the accumulated benefit of compounding.
        </p>

        <p>
          Zero rate is another useful invariant. If <em>r</em> = 0, then <code>A = P(1 + 0/n)^(nt) = P</code> regardless of whether compounding occurs annually, monthly, weekly, or daily. Every frequency should therefore converge to the same result when the rate is zero. Continuous compounding uses Euler's constant <em>e</em> &approx; 2.71828 to represent the mathematical limit as compounding becomes continuously frequent.
        </p>
      </section>

      {/* ==========================================
          SECTION 4: RECURRING CONTRIBUTIONS & TIMING
         ========================================== */}
      <section className="space-y-4 bg-white dark:bg-zinc-900 p-6 sm:p-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
        <h2 className="text-xl sm:text-2xl font-black text-blue-600 dark:text-blue-400 flex items-center gap-2 pb-2">
          <Clock className="h-6 w-6 text-blue-600" /> Recurring Contributions: Why Timing and Frequency Matter
        </h2>

        <p>
          An initial lump sum tells only part of the growth story. Many savers and investors build balances gradually by making recurring contributions. A person who starts with $20,000 and adds $500 every month is exposed to a very different growth pattern than someone who starts with $20,000 and never contributes again. Each additional deposit creates another amount of principal that can potentially earn interest.
        </p>

        <p>
          For a recurring contribution made at the end of each period, the future value of the contribution stream is commonly represented by the ordinary-annuity formula:
        </p>

        <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-center font-mono font-bold text-base text-zinc-900 dark:text-zinc-100">
          FV = PMT &times; [((1 + i)^N &minus; 1) / i]
        </div>

        <p>
          where <em>PMT</em> is the periodic contribution, <em>i</em> is the periodic interest rate, and <em>N</em> is the number of contribution periods. If the contribution is made at the beginning of each period instead, the contribution stream receives one additional period of growth:
        </p>

        <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-center font-mono font-bold text-base text-zinc-900 dark:text-zinc-100">
          FV = PMT &times; [((1 + i)^N &minus; 1) / i] &times; (1 + i)
        </div>

        <p>
          The difference between beginning and ending contributions is therefore not cosmetic. It changes the amount of time each deposit remains invested.
        </p>

        <p>
          Suppose $500 is contributed monthly. The first $500 may remain invested for nearly the entire period, depending on the convention, while the final $500 may have very little time to earn interest. That means it is incorrect to treat all contributions as though the entire year's contribution existed in the account from the beginning. The calculator should instead apply the contribution according to its timing convention.
        </p>

        <p>
          This is especially important when the interface allows both annual and monthly contributions. An annual contribution of $6,000 and a monthly contribution of $500 are numerically equal in total dollars over one year, but they are not necessarily mathematically identical under a compounding model. If the $6,000 is deposited at one particular point in time while the $500 deposits occur throughout the year, the deposits have different durations in the account.
        </p>

        <p>
          The total principal in a recurring-contribution model should be kept conceptually separate from interest earned. If an account starts with $20,000 and receives $5,000 per year for five years, the total contributed capital is:
        </p>

        <div className="p-3 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg font-mono text-xs font-bold">
          $20,000 + ($5,000 &times; 5) = $45,000 &emsp;|&emsp; Interest = $54,535.20 &minus; $45,000 = $9,535.20
        </div>

        <p>
          For broader investment-return analysis, explore the <Link href="/calculators/roi-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">ROI Calculator</Link>, or examine retirement accumulation on the <Link href="/calculators/retirement-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Retirement Calculator</Link>.
        </p>
      </section>

      {/* ==========================================
          SECTION 5: TAX, INFLATION & REAL GROWTH
         ========================================== */}
      <section className="space-y-4 bg-white dark:bg-zinc-900 p-6 sm:p-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
        <h2 className="text-xl sm:text-2xl font-black text-blue-600 dark:text-blue-400 flex items-center gap-2 pb-2">
          <Scale className="h-6 w-6 text-blue-600" /> Tax, Inflation and the Difference Between Nominal and Real Growth
        </h2>

        <p>
          A future balance expressed in dollars is not necessarily equivalent to the same amount of purchasing power today. Two additional concepts become important in long-term calculations: tax drag and inflation. Tax can reduce the amount of investment growth that remains after taxes, while inflation can reduce what the resulting dollars can purchase.
        </p>

        <p>
          The interest calculator's tax adjustment should therefore be interpreted as a modeling assumption, not as a universal tax calculation. The actual tax treatment of interest depends on the type of account, investment, taxpayer, jurisdiction, and other circumstances. In the United States, for example, interest income can be taxable, and the IRS explains that interest is generally treated as ordinary income in applicable taxable situations. Certain investment income may also be affected by additional federal rules, including the Net Investment Income Tax for taxpayers who meet its requirements.
        </p>

        <p>
          Suppose a hypothetical investment earns 8% and the calculator applies a 25% tax assumption directly to the modeled interest. A simplified after-tax rate might be represented as:
        </p>

        <div className="p-3 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg font-mono text-xs font-bold">
          8% &times; (1 &minus; 25%) = 6%
        </div>

        <p>
          Inflation introduces a different issue. Suppose an investment grows from $100,000 to $200,000 over a long period. The nominal balance has doubled, but the purchasing power of $200,000 in the future may be substantially lower than $200,000 today. Investor.gov defines purchasing power specifically by reference to the effect of inflation. A common way of converting a future nominal amount into today's purchasing-power terms is:
        </p>

        <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-center font-mono font-bold text-base text-zinc-900 dark:text-zinc-100">
          Real Value = Nominal Future Value / (1 + Inflation Rate)^t
        </div>

        <p>
          For historical purchasing-power analysis, use the <Link href="/calculators/inflation-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Inflation Calculator</Link>. For tax-advantaged account comparisons, examine the <Link href="/calculators/roth-ira-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Roth IRA Calculator</Link>.
        </p>
      </section>

      {/* ==========================================
          SECTION 6: RULE OF 72 & EXACT DOUBLING TIME
         ========================================== */}
      <section className="space-y-4 bg-white dark:bg-zinc-900 p-6 sm:p-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
        <h2 className="text-xl sm:text-2xl font-black text-blue-600 dark:text-blue-400 flex items-center gap-2 pb-2">
          <Percent className="h-6 w-6 text-blue-600" /> Rule of 72, Exact Doubling Time and What the Numbers Really Mean
        </h2>

        <p>
          The Rule of 72 is one of the simplest ways to estimate how long it may take an amount of money to double under a constant rate of return. The shortcut is:
        </p>

        <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 text-center font-mono font-bold text-base text-zinc-900 dark:text-zinc-100">
          Doubling Time &approx; 72 / Rate (%)
        </div>

        <p>
          At an assumed 5% annual return: <code>72 / 5 = 14.4 years</code>. The Rule of 72 is intentionally an approximation. Investor.gov describes it as a way to estimate how long an investment may take to double and gives the same basic 72 divided by rate approach.
        </p>

        <p>
          The exact mathematical doubling time under annual compounding is derived from:
        </p>

        <div className="p-3 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg font-mono text-xs">
          2P = P(1+r)^t &emsp;&rarr;&emsp; 2 = (1+r)^t &emsp;&rarr;&emsp; <strong>t = ln(2) / ln(1+r)</strong>
        </div>

        <p>
          At 5%, the exact value is approximately: <code>t = ln(2) / ln(1.05) &approx; 14.21 years</code>. The Rule of 72 gives approximately 14.4 years, while the logarithmic equation gives approximately 14.21 years.
        </p>

        <p>
          The relationship can also be used in reverse. If you have a target doubling period, you can estimate the required rate: <code>Rate &approx; 72 / Desired Years</code>. For a mathematically detailed present-value analysis, see the <Link href="/calculators/present-value-calculator" className="text-blue-600 dark:text-blue-400 font-semibold hover:underline">Present Value Calculator</Link>.
        </p>
      </section>

      {/* ==========================================
          SECTION 7: HOW TO READ RESULTS
         ========================================== */}
      <section className="space-y-4 bg-white dark:bg-zinc-900 p-6 sm:p-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
        <h2 className="text-xl sm:text-2xl font-black text-blue-600 dark:text-blue-400 flex items-center gap-2 pb-2">
          <PieChart className="h-6 w-6 text-blue-600" /> How to Read the Interest Calculator Results
        </h2>

        <p>
          A final balance is useful, but it should never be the only number you look at. A good interest calculation tells a story about where the ending balance came from. Start with total principal, which represents the money supplied to the account through the initial investment and recurring contributions. Then examine total interest, which represents the modeled growth generated by the assumed rate and compounding methodology.
        </p>

        <p>
          For example, imagine an investment starts with $20,000 and receives $5,000 at the beginning of every year for five years at an assumed 5% annual rate. Under a beginning-of-period contribution model, the total principal supplied is $45,000. The ending balance under that model is approximately $54,535.20. The difference is $9,535.20 in modeled interest. The result becomes far easier to interpret when the calculator separates principal from interest rather than displaying only $54,535.20.
        </p>

        <p>
          A schedule provides another layer of transparency. If Year 1 starts with $20,000 and a $5,000 contribution is made at the beginning of the period, the amount exposed to the 5% annual rate becomes $25,000. Five percent of that is $1,250, producing an ending balance of $26,250. In Year 2, another $5,000 contribution increases the amount before interest to $31,250, producing $1,562.50 of interest. The schedule makes the compounding process visible instead of hiding it inside a single formula.
        </p>
      </section>

      {/* ==========================================
          SECTION 8: FORMULA REFERENCE & WORKED EXAMPLE
         ========================================== */}
      <section className="space-y-4 bg-white dark:bg-zinc-900 p-6 sm:p-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xs">
        <h2 className="text-xl sm:text-2xl font-black text-blue-600 dark:text-blue-400 flex items-center gap-2 pb-2">
          <CalcIcon className="h-6 w-6 text-blue-600" /> Interest Calculator Formula Reference & Worked Example
        </h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs font-mono">
          <div className="p-3 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg">
            <span className="font-bold text-zinc-900 dark:text-zinc-100 block font-sans">Simple Interest:</span>
            <code>I = P &times; r &times; t</code><br />
            <code>A = P(1 + rt)</code>
          </div>

          <div className="p-3 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg">
            <span className="font-bold text-zinc-900 dark:text-zinc-100 block font-sans">Compound Interest:</span>
            <code>A = P(1 + r/n)^(nt)</code><br />
            <code>Continuous: A = P &times; e^(rt)</code>
          </div>

          <div className="p-3 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg">
            <span className="font-bold text-zinc-900 dark:text-zinc-100 block font-sans">End-of-Period Contributions:</span>
            <code>FV = P(1+r)^n + PMT[((1+r)^n&minus;1)/r]</code>
          </div>

          <div className="p-3 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg">
            <span className="font-bold text-zinc-900 dark:text-zinc-100 block font-sans">Beginning-of-Period Contributions:</span>
            <code>FV = P(1+r)^n + PMT[((1+r)^n&minus;1)/r](1+r)</code>
          </div>
        </div>

        <h3 className="text-sm font-bold text-zinc-900 dark:text-zinc-100 pt-3">
          Worked Example: $20,000 at 5% With $5,000 Annual Contributions
        </h3>

        <div className="overflow-x-auto my-2">
          <table className="w-full text-xs text-left">
            <thead className="bg-zinc-100 dark:bg-zinc-800 font-bold text-zinc-800 dark:text-zinc-200 border-b border-zinc-200 dark:border-zinc-700">
              <tr>
                <th className="p-2.5">Year</th>
                <th className="p-2.5">Starting Balance</th>
                <th className="p-2.5">Eligible Balance (+Contrib)</th>
                <th className="p-2.5">Interest Earned (5%)</th>
                <th className="p-2.5">Ending Balance</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-zinc-200 dark:divide-zinc-800 font-sans tabular-nums">
              <tr className="hover:bg-zinc-50 dark:hover:bg-zinc-800/50">
                <td className="p-2.5 font-bold">Year 1</td>
                <td className="p-2.5">$20,000.00</td>
                <td className="p-2.5">$25,000.00</td>
                <td className="p-2.5 text-emerald-600 font-semibold">+$1,250.00</td>
                <td className="p-2.5 font-bold">$26,250.00</td>
              </tr>
              <tr className="hover:bg-zinc-50 dark:hover:bg-zinc-800/50">
                <td className="p-2.5 font-bold">Year 2</td>
                <td className="p-2.5">$26,250.00</td>
                <td className="p-2.5">$31,250.00</td>
                <td className="p-2.5 text-emerald-600 font-semibold">+$1,562.50</td>
                <td className="p-2.5 font-bold">$32,812.50</td>
              </tr>
              <tr className="hover:bg-zinc-50 dark:hover:bg-zinc-800/50">
                <td className="p-2.5 font-bold">Year 3</td>
                <td className="p-2.5">$32,812.50</td>
                <td className="p-2.5">$37,812.50</td>
                <td className="p-2.5 text-emerald-600 font-semibold">+$1,890.63</td>
                <td className="p-2.5 font-bold">$39,703.13</td>
              </tr>
              <tr className="hover:bg-zinc-50 dark:hover:bg-zinc-800/50">
                <td className="p-2.5 font-bold">Year 4</td>
                <td className="p-2.5">$39,703.13</td>
                <td className="p-2.5">$44,703.13</td>
                <td className="p-2.5 text-emerald-600 font-semibold">+$2,235.16</td>
                <td className="p-2.5 font-bold">$46,938.28</td>
              </tr>
              <tr className="hover:bg-zinc-50 dark:hover:bg-zinc-800/50">
                <td className="p-2.5 font-bold">Year 5</td>
                <td className="p-2.5">$46,938.28</td>
                <td className="p-2.5">$51,938.28</td>
                <td className="p-2.5 text-emerald-600 font-semibold">+$2,596.91</td>
                <td className="p-2.5 font-bold text-blue-600">$54,535.20</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="p-3 bg-zinc-50 dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg text-xs space-y-1">
          <div><strong>Final Modeled Balance:</strong> $54,535.20</div>
          <div><strong>Total Principal Supplied:</strong> $45,000.00 ($20,000 initial + $25,000 contributions)</div>
          <div><strong>Total Modeled Interest:</strong> $9,535.20 ($5,525.63 initial + $4,009.56 contributions)</div>
        </div>

        <p className="text-xs text-zinc-500 pt-2 border-t border-zinc-100 dark:border-zinc-800">
          <strong>Research Sources & Reference Guidelines:</strong> Core explanations reference the Consumer Financial Protection Bureau (CFPB) and U.S. Securities and Exchange Commission (Investor.gov) educational materials on compound interest, compounding frequency, purchasing power, volatility risk, and the Rule of 72, with Internal Revenue Service (IRS) guidelines referenced for ordinary interest income tax treatment.
        </p>
      </section>
    </article>
  );
}
