"use client";

import React from "react";

export function AverageReturnContent() {
  return (
    <div className="space-y-10 text-black dark:text-slate-100 font-medium leading-relaxed">
      {/* 1. INTRODUCTION */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-extrabold text-black dark:text-slate-100 tracking-tight">
          1. Understanding Portfolio Returns: Core Foundations &amp; Performance Tracking
        </h2>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          In quantitative finance and wealth management, an <strong>investment return</strong> measures the financial gain or loss generated by an asset or portfolio over a specified time horizon. While simple percentage gains are easy to compute for a static lump-sum holding, real-world retail and institutional portfolios undergo ongoing monthly deposits, dividend distributions, capital redemptions, and shifting market valuations.
        </p>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          Because cash flow timing fundamentally alters compounding wealth, relying on standard arithmetic averages produces misleading conclusions. To evaluate investment performance with mathematical precision, analysts distinguish between <strong>Time-Weighted Rate of Return (TWRR)</strong>, <strong>Money-Weighted Rate of Return (MWRR / XIRR)</strong>, and <strong>Cumulative Return</strong>.
        </p>
      </section>

      {/* 2. TIME-WEIGHTED VS. MONEY-WEIGHTED */}
      <section className="space-y-4">
        <h2 className="text-xl sm:text-2xl font-extrabold text-black dark:text-slate-100 tracking-tight">
          2. Time-Weighted Return (TWRR) vs. Money-Weighted Return (MWRR / XIRR)
        </h2>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          The two primary methodologies for calculating annualized returns address fundamentally different performance questions:
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-medium">
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-2">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              1. Time-Weighted Rate of Return (TWRR)
            </h3>
            <p className="text-black dark:text-slate-100">
              <strong>Time-Weighted Return</strong> measures the pure compound growth of the underlying securities by isolating and removing the distorting effects of cash inflows and outflows. It calculates the geometric mean of segmented sub-period returns:
            </p>
            <div className="p-2.5 bg-white dark:bg-slate-900 rounded border border-slate-200 dark:border-slate-800 font-mono font-bold text-center text-black dark:text-slate-100">
              R_geom = [ &prod;(1 + R_i)^(t_i) ]^(1 / &sum; t_i) - 1
            </div>
            <p className="text-black dark:text-slate-100">
              <strong>Primary Application:</strong> Industry gold standard for evaluating fund managers, mutual funds, and ETFs, where the manager has no control over when investors deposit or withdraw capital.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-2">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              2. Money-Weighted Rate of Return (MWRR / XIRR)
            </h3>
            <p className="text-black dark:text-slate-100">
              <strong>Money-Weighted Return (XIRR)</strong> solves for the exact internal rate of return (IRR) that equates the present value of all cash inflows and outflows to the final ending portfolio balance:
            </p>
            <div className="p-2.5 bg-white dark:bg-slate-900 rounded border border-slate-200 dark:border-slate-800 font-mono font-bold text-center text-black dark:text-slate-100">
              0 = -Start - &sum; [ CF_k / (1 + r)^(d_k / 365) ] + [ End / (1 + r)^(T / 365) ]
            </div>
            <p className="text-black dark:text-slate-100">
              <strong>Primary Application:</strong> Measures the personal performance experienced by an individual investor, capturing the timing impact of when capital was added or withdrawn.
            </p>
          </div>
        </div>
      </section>

      {/* 3. ARITHMETIC VS GEOMETRIC MEAN */}
      <section className="space-y-4">
        <h2 className="text-xl sm:text-2xl font-extrabold text-black dark:text-slate-100 tracking-tight">
          3. Arithmetic Average vs. Geometric Compound Average
        </h2>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          A dangerous mathematical pitfall in investment analysis is using the <strong>Arithmetic Mean</strong> to project multi-year portfolio growth. An arithmetic average simply sums single-period returns and divides by the period count:
        </p>
        <div className="p-3 bg-white dark:bg-slate-900 rounded-lg border border-slate-200 dark:border-slate-800 font-mono text-xs font-bold text-center text-black dark:text-slate-100">
          Arithmetic Average = ( R_1 + R_2 + ... + R_n ) / n
        </div>
        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-2 text-xs">
          <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
            The Mathematical Trap: The Asymmetry of Percentage Gains and Losses
          </h3>
          <p className="text-black dark:text-slate-100">
            Consider an investor who starts with <strong>$100,000</strong>. In Year 1, the portfolio surges by <strong>+50%</strong> (ending at $150,000). In Year 2, the portfolio crashes by <strong>-50%</strong> (ending at $75,000).
          </p>
          <ul className="list-disc pl-5 space-y-1 text-black dark:text-slate-100">
            <li><strong>Arithmetic Average Return:</strong> (+50% - 50%) / 2 = <strong>0.00% per year</strong></li>
            <li><strong>Actual Portfolio Result:</strong> Starting $100,000 &rarr; Ending $75,000 = <strong>-$25,000 Net Loss (-25.0% Cumulative)</strong></li>
            <li><strong>Annualized Geometric Return (CAGR):</strong> &radic;(0.75) - 1 = <strong>-13.40% per year</strong></li>
          </ul>
          <p className="text-black dark:text-slate-100 font-bold">
            The arithmetic mean showed zero change, while the investor lost a quarter of their entire life savings!
          </p>
        </div>
      </section>

      {/* 4. CUMULATIVE RETURN VS ACCOUNTING RATE OF RETURN */}
      <section className="space-y-4">
        <h2 className="text-xl sm:text-2xl font-extrabold text-black dark:text-slate-100 tracking-tight">
          4. Cumulative Return vs. Accounting Rate of Return (ARR)
        </h2>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          <strong>Cumulative Return</strong> represents the absolute aggregate percentage gain or loss generated over an entire investment holding timeframe, irrespective of how many days, months, or years elapsed:
        </p>
        <div className="p-3 bg-white dark:bg-slate-900 rounded-lg border border-slate-200 dark:border-slate-800 font-mono text-xs font-bold text-center text-black dark:text-slate-100">
          Cumulative Return = ( Ending Value - Total Net Capital Invested ) / Total Net Capital Invested &times; 100
        </div>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          By contrast, the <strong>Accounting Rate of Return (ARR)</strong> calculates simple annual cash generation divided by invested capital. Because ARR ignores the time value of money, compounding interest, and cash flow timing, it is suitable solely for corporate capital budgeting and should never be used as a standalone metric for liquid investment portfolios.
        </p>
      </section>

      {/* 5. BEHAVIORAL INVESTOR TIMING DRAG */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-extrabold text-black dark:text-slate-100 tracking-tight">
          5. The Hidden Cost of Investor Timing Drag (The Behavior Gap)
        </h2>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          Independent research studies (such as Morningstar&apos;s <em>Mind the Gap</em> report) demonstrate that the average retail investor underperforms the very mutual funds and ETFs they own by <strong>1.5% to 2.0% per year</strong>.
        </p>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          This disparity occurs because investors inject large cash deposits into funds after substantial run-ups (buying at market peaks) and panic-sell or halt contributions during market corrections (selling at troughs). This behavioral flaw causes an individual&apos;s personal <strong>Money-Weighted Return (XIRR)</strong> to lag behind the fund&apos;s published <strong>Time-Weighted Return (TWRR)</strong>.
        </p>
      </section>

      {/* 6. RISK-ADJUSTED METRICS */}
      <section className="space-y-4">
        <h2 className="text-xl sm:text-2xl font-extrabold text-black dark:text-slate-100 tracking-tight">
          6. Risk-Adjusted Performance: Volatility, Sharpe, Sortino &amp; Max Drawdown
        </h2>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          High average returns are meaningless without accounting for the volatility and downside risk endured to achieve them:
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-medium">
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              1. Sharpe Ratio
            </h3>
            <p className="text-black dark:text-slate-100">
              Measures excess return earned per unit of total risk (standard deviation):
            </p>
            <div className="font-mono font-bold text-center text-blue-700 dark:text-blue-400">
              Sharpe = ( Mean Portfolio Return - Risk-Free Rate ) / &sigma;
            </div>
            <p className="text-black dark:text-slate-100">
              A Sharpe ratio &gt; 1.0 is good, &gt; 2.0 is very good, and &gt; 3.0 is exceptional.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              2. Sortino Ratio &amp; Max Drawdown
            </h3>
            <p className="text-black dark:text-slate-100">
              <strong>Sortino Ratio:</strong> Penalizes only harmful downside volatility below the hurdle rate, ignoring upside volatility.
            </p>
            <p className="text-black dark:text-slate-100">
              <strong>Maximum Drawdown (MDD):</strong> Measures the maximum peak-to-trough percentage loss experienced before a new peak is achieved.
            </p>
          </div>
        </div>
      </section>

      {/* 7. WORKED STEP-BY-STEP MATHEMATICAL EXAMPLES */}
      <section className="space-y-4">
        <h2 className="text-xl sm:text-2xl font-extrabold text-black dark:text-slate-100 tracking-tight">
          7. Worked Step-by-Step Mathematical Examples
        </h2>

        {/* Example 1 */}
        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-2 text-xs">
          <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
            Example 1: Multi-Period Time-Weighted Holding Log
          </h3>
          <p className="text-black dark:text-slate-100">
            An investment experiences +10% over 1 yr 2 mos (1.167 yrs), -2% over 5 mos (0.417 yrs), and +15% over 2 yrs 3 mos (2.250 yrs).
          </p>
          <div className="space-y-1 font-mono text-black dark:text-slate-100 bg-white dark:bg-slate-900 p-3 rounded-lg border border-slate-200 dark:border-slate-800">
            <div>1. Total Time = 1.1667 + 0.4167 + 2.2500 = 3.8333 Years</div>
            <div>2. Cumulative Growth Multiplier = (1 + 0.10) &times; (1 - 0.02) &times; (1 + 0.15) = 1.10 &times; 0.98 &times; 1.15 = 1.2397x</div>
            <div>3. Total Cumulative Return = (1.2397 - 1) &times; 100 = 23.970%</div>
            <div>4. Annualized Geometric Return (TWRR) = (1.2397)^(1 / 3.8333) - 1 = 5.765% per year</div>
            <div>5. Arithmetic Average = (10 - 2 + 15) / 3 = 7.667% per period (Annualized Arithmetic: 6.000%/yr)</div>
          </div>
        </div>

        {/* Example 2 */}
        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-2 text-xs">
          <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
            Example 2: Cash Flow Money-Weighted Return (XIRR)
          </h3>
          <p className="text-black dark:text-slate-100">
            Starting $5,600 on 01/01/2023. Deposit $5,000 on 01/15/2024. Withdraw $1,500 on 06/01/2024. Deposit $3,800 on 01/18/2025. Final ending balance $18,000 on 08/17/2026.
          </p>
          <div className="space-y-1 font-mono text-black dark:text-slate-100 bg-white dark:bg-slate-900 p-3 rounded-lg border border-slate-200 dark:border-slate-800">
            <div>1. Total Contributions = $5,000 + $3,800 = $8,800.00 | Total Withdrawals = $1,500.00</div>
            <div>2. Net Capital Invested = $5,600 + $8,800 - $1,500 = $12,900.00</div>
            <div>3. Net Dollar Gain = $18,000.00 - $12,900.00 = +$5,100.00</div>
            <div>4. Total Duration = 1,324 Days (3.627 Years)</div>
            <div>5. Solved Money-Weighted Rate of Return (MWRR / XIRR) = 12.505% per year</div>
            <div>6. Simple Accounting Rate of Return (ARR) = ($5,100 / $12,900) / 3.627 = 10.897% per year</div>
          </div>
        </div>
      </section>

      {/* 8. SUMMARY */}
      <section className="space-y-3 pt-2 border-t border-slate-200 dark:border-slate-800">
        <h2 className="text-xl sm:text-2xl font-extrabold text-black dark:text-slate-100 tracking-tight">
          8. Educational Summary
        </h2>
        <p className="text-sm leading-relaxed text-black dark:text-slate-100">
          Calculating portfolio returns accurately requires selecting the appropriate methodology for your analytical objective. Use <strong>Time-Weighted Return (TWRR)</strong> to assess investment selection skill independent of cash flows, and <strong>Money-Weighted Return (XIRR)</strong> to measure your personal net dollar accumulation. Always complement return figures with risk-adjusted metrics like the Sharpe ratio and maximum drawdown to ensure robust financial decision-making.
        </p>
      </section>

      {/* 9. FREQUENTLY ASKED QUESTIONS (12 FAQS) */}
      <section className="space-y-4 pt-6 border-t border-slate-200 dark:border-slate-800">
        <h2 className="text-xl sm:text-2xl font-extrabold text-black dark:text-slate-100 tracking-tight">
          Frequently Asked Questions (FAQ)
        </h2>
        <div className="space-y-3 text-xs leading-relaxed text-black dark:text-slate-100">
          {/* FAQ 1 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              1. What is the difference between average annual return and cumulative return?
            </h3>
            <p className="text-black dark:text-slate-100">
              <strong>Cumulative return</strong> measures total aggregate percentage growth from start to finish regardless of how long the holding period lasted. <strong>Average annual return</strong> normalizes that cumulative gain into a compound annual growth rate (CAGR) per 365-day year.
            </p>
          </div>

          {/* FAQ 2 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              2. Why do professional fund managers report Time-Weighted Return instead of Money-Weighted Return?
            </h3>
            <p className="text-black dark:text-slate-100">
              Time-Weighted Return (TWRR) eliminates the distortion caused by external investor cash deposits and redemptions. Because fund managers cannot control when clients add or pull money from the fund, TWRR isolates pure asset allocation and stock picking skill.
            </p>
          </div>

          {/* FAQ 3 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              3. What is XIRR and how does it calculate returns for irregular deposit dates?
            </h3>
            <p className="text-black dark:text-slate-100">
              XIRR (Extended Internal Rate of Return) is a numerical root-finding algorithm that calculates the annualized discount rate setting the Net Present Value (NPV) of irregular cash flow dates and amounts exactly equal to zero.
            </p>
          </div>

          {/* FAQ 4 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              4. Why can a portfolio have a positive arithmetic average return while losing real money?
            </h3>
            <p className="text-black dark:text-slate-100">
              Because percentage losses require significantly larger percentage gains to break even. For example, a +50% gain followed by a -50% loss yields a +0% arithmetic average, but results in an actual 25% loss of starting principal.
            </p>
          </div>

          {/* FAQ 5 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              5. What is the Accounting Rate of Return (ARR) and when should it be used?
            </h3>
            <p className="text-black dark:text-slate-100">
              The Accounting Rate of Return (ARR) measures average annual cash generation divided by invested capital. It ignores compounding and the time value of money, making it useful solely for corporate capital budgeting appraisals rather than portfolio management.
            </p>
          </div>

          {/* FAQ 6 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              6. How do mid-year cash deposits and withdrawals impact my personal average return?
            </h3>
            <p className="text-black dark:text-slate-100">
              Mid-year deposits increase your invested capital base. If the market rallies after your deposit, your money-weighted return rises; if the market declines after a large deposit, your money-weighted return drops significantly more than the underlying fund&apos;s return.
            </p>
          </div>

          {/* FAQ 7 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              7. What is investor timing drag and why does it cause investors to underperform funds?
            </h3>
            <p className="text-black dark:text-slate-100">
              Timing drag occurs when investors buy heavily near market tops and panic-sell during market bottoms. This behavioral mismatch causes individual investors to earn 1.5% to 2.0% less per year than the funds they own.
            </p>
          </div>

          {/* FAQ 8 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              8. How do I convert a multi-year cumulative return into an annualized compound rate?
            </h3>
            <p className="text-black dark:text-slate-100">
              Use the geometric compound formula: Annualized Return = (1 + Cumulative Return)^(1 / Years) - 1. For example, a 50% cumulative gain over 3 years equals (1.50)^(1/3) - 1 = 14.47% per year.
            </p>
          </div>

          {/* FAQ 9 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              9. What is the Sharpe Ratio and what is considered a good Sharpe score?
            </h3>
            <p className="text-black dark:text-slate-100">
              The Sharpe Ratio measures excess return above the risk-free rate per unit of standard deviation. A score above 1.0 is considered good, above 2.0 is very good, and above 3.0 is exceptional.
            </p>
          </div>

          {/* FAQ 10 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              10. How does the Sortino Ratio differ from the Sharpe Ratio?
            </h3>
            <p className="text-black dark:text-slate-100">
              While the Sharpe Ratio penalizes both upside and downside volatility, the Sortino Ratio only penalizes negative returns falling below the target hurdle rate, providing a clearer gauge of harmful downside risk.
            </p>
          </div>

          {/* FAQ 11 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              11. What is Maximum Drawdown (MDD) and why is it crucial for risk management?
            </h3>
            <p className="text-black dark:text-slate-100">
              Maximum Drawdown measures the largest historical percentage drop from peak wealth to lowest trough before reaching a new high. It indicates the worst-case capital loss an investor would have endured during market downturns.
            </p>
          </div>

          {/* FAQ 12 */}
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-300 dark:border-slate-700 space-y-1.5">
            <h3 className="font-extrabold text-sm text-black dark:text-slate-100">
              12. How does inflation affect my real annualized portfolio return?
            </h3>
            <p className="text-black dark:text-slate-100">
              Inflation erodes purchasing power over time. Your real annualized return is calculated using the Fisher equation: Real Return = (1 + Nominal Return) / (1 + Inflation Rate) - 1. A 10% nominal return with 3% inflation yields a real return of approximately 6.80% per year.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

export default AverageReturnContent;
