"use client";

import React from "react";

export function GDPContent() {
  const faqs = [
    {
      question: "1. What is Gross Domestic Product (GDP)?",
      answer:
        "Gross Domestic Product (GDP) is the monetary market value of all finished goods and services produced within a nation's geographical borders during a specific time period (typically quarterly or annually). It serves as the primary comprehensive scorecard of a country's economic health and size.",
    },
    {
      question: "2. What is the difference between Nominal GDP and Real GDP?",
      answer:
        "Nominal GDP evaluates economic output using current raw market prices without adjusting for inflation. Real GDP adjusts for price changes by evaluating output using constant base-year prices via the GDP Deflator, reflecting true physical growth in goods and services produced.",
    },
    {
      question: "3. What is the Expenditure Approach formula for GDP?",
      answer:
        "The Expenditure Approach calculates GDP by summing total spending: GDP = C + I + G + (X - M), where C = Personal Consumption Expenditures, I = Gross Private Domestic Investment, G = Government Consumption & Gross Investment, X = Exports, and M = Imports.",
    },
    {
      question: "4. What is the Resource Cost - Income Approach to GDP?",
      answer:
        "The Income Approach measures the total factor earnings generated in production: National Income = Employee Compensation + Proprietors' Income + Rental Income + Corporate Profits + Net Interest Income. Adding indirect business taxes, capital depreciation, and net foreign factor income equals GDP.",
    },
    {
      question: "5. Why are intermediate goods excluded from GDP calculations?",
      answer:
        "To prevent 'double counting.' If the value of steel purchased by an automaker and the final value of the completed car were both counted, the steel would be counted twice. Only final goods sold to the end user (or the value added at each intermediate stage) are included.",
    },
    {
      question: "6. What is GDP Per Capita and why is it important?",
      answer:
        "GDP per capita is calculated by dividing a nation's total GDP by its total resident population (GDP ÷ Population). It serves as a standard international proxy for average individual economic productivity and material living standards.",
    },
    {
      question: "7. What is Purchasing Power Parity (PPP)?",
      answer:
        "Purchasing Power Parity (PPP) adjusts nominal GDP figures by equalizing the purchasing power of different currencies based on a standardized basket of consumer goods. PPP accounts for local cost-of-living differences that market exchange rates overlook.",
    },
    {
      question: "8. What is the GDP Deflator?",
      answer:
        "The GDP Deflator is a broad measure of price inflation across all domestically produced goods and services in an economy: GDP Deflator = (Nominal GDP ÷ Real GDP) × 100. Unlike the Consumer Price Index (CPI), it includes investment goods and government purchases.",
    },
    {
      question: "9. What critical economic activities are excluded from GDP?",
      answer:
        "GDP excludes non-market household labor (cooking, child-rearing), unpaid volunteer work, shadow/informal cash transactions, illegal black-market sales, transfer payments (social security, pensions), and environmental degradation or natural resource depletion.",
    },
    {
      question: "10. What is the difference between GDP and GNP (Gross National Product)?",
      answer:
        "GDP measures all production occurring strictly within a country's physical borders regardless of citizenship. GNP (Gross National Product) measures all production generated by a country's citizens and domestic enterprises, including income earned abroad.",
    },
    {
      question: "11. What defines an economic recession in terms of GDP?",
      answer:
        "A widely cited rule of thumb defines an economic recession as two consecutive quarters of negative real GDP growth. In the United States, the National Bureau of Economic Research (NBER) officially designates recessions based on a broader decline in employment, income, and production.",
    },
    {
      question: "12. What is Net Exports (X - M) and what does a trade deficit mean for GDP?",
      answer:
        "Net Exports equals total gross exports minus total gross imports. When a nation imports more goods and services than it exports (M > X), Net Exports is negative, creating a trade deficit that acts as a subtraction from aggregate domestic GDP.",
    },
  ];

  return (
    <div className="space-y-3 text-black dark:text-zinc-100 font-sans leading-relaxed">
      {/* SECTION 1: WHAT IS GDP & ECONOMIC MEASUREMENT */}
      <div className="border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-slate-900 p-3.5 shadow-xs space-y-2.5">
        <h2 className="text-sm font-extrabold text-black dark:text-zinc-100">
          What is Gross Domestic Product? Macroeconomic Measurement Principles
        </h2>
        <p className="text-xs text-black dark:text-zinc-200">
          Gross Domestic Product (GDP) is defined by the OECD and IMF as an aggregate measure of production equal to the sum of gross values added of all resident institutional units engaged in production, plus any taxes and minus any subsidies on products:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2 pt-1">
          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold text-[11px] uppercase text-black dark:text-zinc-100 block">Personal Consumption (C)</span>
            <p className="text-[11px] text-black dark:text-zinc-300">
              Household spending on durable goods (cars, appliances), non-durable goods (food, fuel), and services (healthcare, rent).
            </p>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold text-[11px] uppercase text-black dark:text-zinc-100 block">Gross Investment (I)</span>
            <p className="text-[11px] text-black dark:text-zinc-300">
              Business capital outlays on machinery, industrial factories, software technology, commercial real estate, and inventory changes.
            </p>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold text-[11px] uppercase text-black dark:text-zinc-100 block">Government Spending (G)</span>
            <p className="text-[11px] text-black dark:text-zinc-300">
              Federal, state, and local expenditures on public infrastructure, defense procurement, education, and civil service payrolls.
            </p>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold text-[11px] uppercase text-black dark:text-zinc-100 block">Net Exports (X - M)</span>
            <p className="text-[11px] text-black dark:text-zinc-300">
              Total gross exports shipped abroad minus total foreign imports consumed domestically.
            </p>
          </div>
        </div>
      </div>

      {/* SECTION 2: THREE METHODS TO MEASURE GDP */}
      <div className="border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-slate-900 p-3.5 shadow-xs space-y-2.5">
        <h2 className="text-sm font-extrabold text-black dark:text-zinc-100">
          The Three Fundamental Methods of National Income Accounting
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-2 font-mono text-[11px]">
          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold font-sans text-xs text-black dark:text-zinc-100 block">1. Expenditure Approach</span>
            <div>GDP = C + I + G + (X - M)</div>
            <div className="text-[10px] text-slate-500 font-sans">Sums aggregate final spending across all economic sectors.</div>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold font-sans text-xs text-black dark:text-zinc-100 block">2. Income Approach</span>
            <div>GDP = Wages + Profits + Rent + Interest + Taxes + Depr</div>
            <div className="text-[10px] text-slate-500 font-sans">Sums all factor payments earned in domestic production.</div>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold font-sans text-xs text-black dark:text-zinc-100 block">3. Production (Value-Added)</span>
            <div>GDP = Gross Output - Intermediate Inputs + Taxes</div>
            <div className="text-[10px] text-slate-500 font-sans">Sums net value added by every industrial manufacturing stage.</div>
          </div>
        </div>
      </div>

      {/* SECTION 3: WORKED MATHEMATICAL CASE STUDIES */}
      <div className="border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-slate-900 p-3.5 shadow-xs space-y-2.5">
        <h2 className="text-sm font-extrabold text-black dark:text-zinc-100">
          Worked Macroeconomic Case Study (Expenditure & Deflator Calculation)
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
          <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h3 className="font-bold text-xs uppercase text-black dark:text-zinc-100">Expenditure Accounting</h3>
            <div className="font-mono text-[11px] text-black dark:text-zinc-300 space-y-0.5">
              <div>• Consumption (C) = $19,100 Billion (66.4%)</div>
              <div>• Gross Investment (I) = $5,100 Billion (17.7%)</div>
              <div>• Government Spending (G) = $4,850 Billion (16.9%)</div>
              <div>• Net Exports (X - M) = $3,150B - $3,820B = -$670 Billion (-2.3%)</div>
              <div>• Total Nominal GDP = <strong>$28,380.00 Billion ($28.38 Trillion)</strong></div>
              <div>• Per Capita (335M Pop) = <strong>$84,716 / person</strong></div>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h3 className="font-bold text-xs uppercase text-black dark:text-zinc-100">Real GDP vs. Inflation Deflator</h3>
            <div className="font-mono text-[11px] text-black dark:text-zinc-300 space-y-0.5">
              <div>• Nominal GDP = $28,380 Billion</div>
              <div>• GDP Deflator Index = 124.5 (24.5% cumulative price inflation)</div>
              <div>• Real GDP = ($28,380 ÷ 124.5) × 100 = <strong>$22,795.18 Billion</strong></div>
              <div>• Inflation Drag = $5,584.82 Billion</div>
            </div>
          </div>
        </div>
      </div>

      {/* SECTION 4: 12 FAQS ALWAYS OPEN CARDS */}
      <div className="border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-slate-900 p-3.5 shadow-xs space-y-2.5">
        <h2 className="text-sm font-extrabold text-black dark:text-zinc-100">
          Frequently Asked Questions (12 Key GDP & Macroeconomic FAQs)
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="border border-slate-200 dark:border-slate-800 rounded-lg p-2.5 bg-slate-50 dark:bg-slate-800/50 space-y-1"
            >
              <h3 className="font-bold text-xs text-black dark:text-zinc-100">
                {faq.question}
              </h3>
              <p className="text-[11px] text-black dark:text-zinc-300 leading-relaxed">
                {faq.answer}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
