"use client";

import React, { useState } from "react";
import Link from "next/link";
import { HelpCircle, ChevronDown, BookOpen, ShieldCheck, TrendingUp, BarChart3, Globe, DollarSign } from "lucide-react";

export function GDPContent() {
  // All 18 FAQs open by default (unfolded)
  const [openFaqIndices, setOpenFaqIndices] = useState<Set<number>>(
    new Set(Array.from({ length: 18 }, (_, i) => i))
  );

  const toggleFaq = (index: number) => {
    setOpenFaqIndices((prev) => {
      const next = new Set(prev);
      if (next.has(index)) {
        next.delete(index);
      } else {
        next.add(index);
      }
      return next;
    });
  };

  const faqs = [
    {
      question: "What is GDP?",
      answer:
        "GDP is the market value of final goods and services produced within an economy over a specified period. It is a measure of economic production, not a complete measure of welfare.",
    },
    {
      question: "What is the formula for GDP?",
      answer:
        "The expenditure identity is: GDP = C + I + G + (X - M) where C is consumption, I is investment, G is government consumption and investment, X is exports and M is imports.",
    },
    {
      question: "Why are imports subtracted from GDP?",
      answer:
        "Imports are subtracted in the expenditure approach so that spending on foreign-produced goods and services is not mistakenly counted as domestic production.",
    },
    {
      question: "What is net exports?",
      answer:
        "Net exports are: NX = X - M. A positive value means exports exceed imports (trade surplus). A negative value means imports exceed exports (trade deficit).",
    },
    {
      question: "What are the three approaches to GDP?",
      answer:
        "The three broad approaches are the expenditure approach, income approach and production approach. They examine the same economic activity from spending, income and production perspectives.",
    },
    {
      question: "What is GVA?",
      answer:
        "Gross value added measures the value generated by production after subtracting intermediate inputs from gross output. In a simplified production calculation: GVA = Gross Output - Intermediate Inputs. GDP then incorporates the relevant product-tax adjustment.",
    },
    {
      question: "What is the difference between nominal GDP and real GDP?",
      answer:
        "Nominal GDP uses current prices. Real GDP attempts to measure changes in production volume after adjusting for price changes.",
    },
    {
      question: "How is real GDP calculated from the GDP deflator?",
      answer:
        "When the GDP deflator uses a base of 100: Real GDP = (Nominal GDP / GDP Deflator) * 100. This calculator applies that index-based relationship.",
    },
    {
      question: "What is GDP growth?",
      answer:
        "GDP growth measures the percentage change in GDP between periods: ((GDP_current - GDP_previous) / GDP_previous) * 100. A negative result indicates that GDP decreased relative to the comparison period.",
    },
    {
      question: "What is CAGR for GDP?",
      answer:
        "CAGR is the constant annual compound rate connecting an initial GDP value and a final GDP value over a specified number of years: CAGR = (GDP_final / GDP_initial)^(1/t) - 1. It is useful for summarizing multi-year compound growth.",
    },
    {
      question: "What is GDP per capita?",
      answer:
        "GDP per capita is total GDP divided by population. It represents average economic output per person, not average salary or household income.",
    },
    {
      question: "Is GDP per capita the same as income per person?",
      answer:
        "No. GDP per capita measures output per person. It does not measure wages, disposable income, wealth or the distribution of income.",
    },
    {
      question: "What is the difference between GDP and GNI?",
      answer:
        "GDP measures production within an economy's territory. GNI measures income accruing to residents, including relevant income received from abroad and paid to the rest of the world.",
    },
    {
      question: "What is PPP GDP?",
      answer:
        "PPP GDP is GDP valued using purchasing-power-parity conversion factors, which account for differences in price levels between economies. It is useful for certain international comparisons but is not the same as GDP converted using market exchange rates.",
    },
    {
      question: "Does two consecutive quarters of falling GDP officially mean the United States is in recession?",
      answer:
        "Not automatically. Two consecutive quarters of declining real GDP are a common rule of thumb, but the NBER's Business Cycle Dating Committee uses a broader assessment of economy-wide activity and does not apply a fixed two-quarter rule.",
    },
    {
      question: "Does the income tier in this calculator represent an official World Bank classification?",
      answer:
        "No. The calculator's tier is explicitly illustrative and based on GDP per capita. The World Bank's official income classification uses GNI per capita converted with the Atlas method and updates the thresholds annually.",
    },
    {
      question: "What are the current World Bank income thresholds?",
      answer:
        "For the current FY2027 classification, the World Bank reports low income at $1,175 or less, lower-middle income at $1,176–$4,635, upper-middle income at $4,636–$14,375 and high income above $14,375, based on 2025 GNI per capita using the Atlas method. These thresholds are not the same methodology used by this calculator's illustrative GDP-per-capita tier.",
    },
    {
      question: "Can GDP increase while people's living standards do not improve?",
      answer:
        "Yes. GDP can rise while population growth, inflation, inequality, housing costs or other factors change the experience of households. GDP is an aggregate production measure and should be interpreted alongside other economic and social indicators.",
    },
  ];

  return (
    <article className="space-y-8 text-slate-800 dark:text-slate-200 leading-relaxed text-sm sm:text-base">
      {/* SECTION 1 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          What Is GDP?
        </h2>
        <p>
          Gross domestic product, or GDP, measures the market value of final goods and services produced within an economy over a specified period.
        </p>
        <p>
          GDP is used to summarize the scale of economic activity. It can also be used to study changes in output over time, compare economic structures, and calculate per-capita measures.
        </p>
        <p>
          A crucial qualification is that GDP is a measure of economic production, not a complete measure of social welfare. It does not by itself describe income distribution, unpaid household work, environmental quality, leisure, health, or many other dimensions of living standards.
        </p>
        <p>
          Official statistical agencies can estimate GDP in several complementary ways. The U.S. Bureau of Economic Analysis describes three broad approaches: the expenditures approach, income approach, and production approach.
        </p>
        <p>
          This calculator brings those approaches and several related calculations together in one interface.
        </p>
      </section>

      {/* SECTION 2 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          The GDP Formula: C + I + G + (X − M)
        </h2>
        <p>The best-known GDP identity is the expenditure approach:</p>
        <div className="p-3 sm:p-4 rounded-xl bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-800 font-mono text-center font-bold text-blue-900 dark:text-blue-100 text-base sm:text-lg">
          GDP = C + I + G + (X − M)
        </div>
        <p>where:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>C</strong> = personal consumption expenditures</li>
          <li><strong>I</strong> = gross private domestic investment</li>
          <li><strong>G</strong> = government consumption and investment</li>
          <li><strong>X</strong> = exports of goods and services</li>
          <li><strong>M</strong> = imports of goods and services</li>
        </ul>
        <p>The difference:</p>
        <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center font-bold text-sm">
          NX = X − M
        </div>
        <p>is net exports.</p>
        <p>
          The Bureau of Economic Analysis describes the expenditure approach as the sum of spending on final goods and services by households, businesses, government and foreign purchasers, with imports subtracted so that foreign production is not counted as domestic production.
        </p>
      </section>

      {/* SECTION 3 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          How to Calculate GDP Using the Expenditure Approach
        </h2>
        <p>Suppose an economy has:</p>
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 text-center font-mono text-xs sm:text-sm font-bold my-2">
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">C = $19,100 B</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">I = $5,100 B</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">G = $4,850 B</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">X = $3,150 B</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">M = $3,820 B</div>
        </div>
        <p>with all values measured in billions of dollars.</p>
        <p>First calculate net exports:</p>
        <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm space-y-1">
          <div>NX = X − M</div>
          <div>NX = 3,150 − 3,820</div>
          <div className="font-bold text-emerald-600 dark:text-emerald-400">NX = −670 billion</div>
        </div>
        <p>The economy therefore has a $670 billion net trade deficit in this example.</p>
        <p>Now calculate GDP:</p>
        <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm space-y-1">
          <div>GDP = 19,100 + 5,100 + 4,850 + (3,150 − 3,820)</div>
          <div className="text-base font-extrabold text-blue-600 dark:text-blue-400">GDP = 28,380 billion</div>
        </div>
        <p>The calculator&apos;s verified golden case produces exactly this result.</p>
        <p>
          The important point is that imports are subtracted from domestic expenditure, not because imports are inherently economically negative, but because GDP is intended to measure domestic production.
        </p>
      </section>

      {/* SECTION 4 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Understanding Consumption, Investment, Government Spending and Net Exports
        </h2>
        <div className="space-y-4">
          <div>
            <h3 className="text-base font-bold text-blue-600 dark:text-blue-400 mb-1">Consumption</h3>
            <p>
              Consumption represents household spending on goods and services. Examples include food, clothing, housing-related consumption, transportation services, healthcare, and recreation. The precise statistical classification of consumption is broader and more detailed in official national accounts than the simplified calculator input.
            </p>
          </div>
          <div>
            <h3 className="text-base font-bold text-blue-600 dark:text-blue-400 mb-1">Investment</h3>
            <p>
              Investment in the GDP identity refers to economic investment, not buying financial assets such as shares on a stock exchange. It includes categories such as business fixed investment, residential investment and changes in inventories within national-accounting frameworks.
            </p>
          </div>
          <div>
            <h3 className="text-base font-bold text-blue-600 dark:text-blue-400 mb-1">Government spending</h3>
            <p>
              The expenditure approach includes government consumption and investment. A common mistake is to assume that every government payment increases GDP directly. Transfer payments such as certain social benefits are not themselves purchases of currently produced goods or services.
            </p>
          </div>
          <div>
            <h3 className="text-base font-bold text-blue-600 dark:text-blue-400 mb-1">Net exports</h3>
            <p>
              Net exports are NX = X − M. When X &gt; M, net exports are positive (surplus). When X &lt; M, net exports are negative (deficit). A negative net export contribution does not mean GDP itself is necessarily falling. It simply means imports exceed exports in the expenditure identity.
            </p>
          </div>
        </div>
      </section>

      {/* SECTION 5 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GDP Sector Shares
        </h2>
        <p>This calculator also breaks the expenditure result into component shares.</p>
        <p>For a positive GDP:</p>
        <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          Component Share = (Component / GDP) × 100
        </div>
        <p>For the example above:</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2.5 font-mono text-xs">
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="text-[10px] text-slate-500 font-sans block uppercase font-bold">Consumption</span>
            <span className="text-sm font-bold text-blue-600 dark:text-blue-400">(19,100 / 28,380) × 100 ≈ 67.30%</span>
          </div>
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="text-[10px] text-slate-500 font-sans block uppercase font-bold">Investment</span>
            <span className="text-sm font-bold text-amber-600 dark:text-amber-400">(5,100 / 28,380) × 100 ≈ 17.97%</span>
          </div>
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="text-[10px] text-slate-500 font-sans block uppercase font-bold">Government</span>
            <span className="text-sm font-bold text-purple-600 dark:text-purple-400">(4,850 / 28,380) × 100 ≈ 17.09%</span>
          </div>
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="text-[10px] text-slate-500 font-sans block uppercase font-bold">Net Exports</span>
            <span className="text-sm font-bold text-emerald-600 dark:text-emerald-400">(−670 / 28,380) × 100 ≈ −2.36%</span>
          </div>
        </div>
        <p>These shares sum to approximately 100% because:</p>
        <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          C + I + G + NX = GDP
        </div>
        <p>
          The calculator now also distinguishes the gross export and gross import shares from net exports rather than incorrectly treating them as the same quantity.
        </p>
      </section>

      {/* SECTION 6 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Why Net Exports Can Have a Negative Share
        </h2>
        <p>A negative net-export percentage can look unusual at first.</p>
        <p>Suppose X = $3,150 B and M = $3,820 B. Then NX = −$670 B, so NX / GDP &lt; 0. The negative percentage simply indicates that imports exceeded exports.</p>
        <p>
          It should not be interpreted as a negative amount of physical production or as proof that the entire economy is contracting.
        </p>
      </section>

      {/* SECTION 7 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          The Three Main Ways to Measure GDP
        </h2>
        <p>GDP can be examined from three complementary perspectives:</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs sm:text-sm">
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 space-y-1.5">
            <div className="font-extrabold text-blue-600 dark:text-blue-400 uppercase text-xs">1. Expenditure Approach</div>
            <div className="font-semibold text-slate-900 dark:text-slate-100">What is purchased</div>
            <p className="text-xs text-slate-600 dark:text-slate-400">
              Sums household consumption, business investments, government purchases, and net foreign exports: C + I + G + (X − M).
            </p>
          </div>
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 space-y-1.5">
            <div className="font-extrabold text-amber-600 dark:text-amber-400 uppercase text-xs">2. Income Approach</div>
            <div className="font-semibold text-slate-900 dark:text-slate-100">Who earns the income</div>
            <p className="text-xs text-slate-600 dark:text-slate-400">
              Sums all factor earnings: wages, corporate profits, rental income, net interest, indirect business taxes, and depreciation.
            </p>
          </div>
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 space-y-1.5">
            <div className="font-extrabold text-emerald-600 dark:text-emerald-400 uppercase text-xs">3. Production Approach</div>
            <div className="font-semibold text-slate-900 dark:text-slate-100">What is produced</div>
            <p className="text-xs text-slate-600 dark:text-slate-400">
              Calculates Gross Value Added (GVA = Gross Output − Intermediate Inputs) plus net product taxes across industries.
            </p>
          </div>
        </div>
        <p>
          The three approaches are conceptually different ways of looking at the same economic activity. In complete national accounts, the approaches are reconciled so that they measure the same aggregate production from different perspectives. BEA explicitly describes expenditure, income and production as alternative ways of measuring GDP.
        </p>
      </section>

      {/* SECTION 8 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Income Approach to GDP
        </h2>
        <p>The income approach looks at income generated through production.</p>
        <p>
          The exact composition used by official statistical agencies is more detailed than a single textbook equation. BEA describes its income approach in terms including compensation of employees, taxes on production and imports less subsidies, net operating surplus and consumption of fixed capital.
        </p>
        <p>This calculator provides an income/resource-cost model using entered components such as:</p>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-mono font-medium">
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded border">Employee Compensation</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded border">Proprietors&apos; Income</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded border">Rental Income</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded border">Corporate Profits</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded border">Net Interest</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded border">Indirect Taxes</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded border">Depreciation</div>
          <div className="p-2 bg-slate-50 dark:bg-slate-800/80 rounded border">Net Foreign Income</div>
        </div>
        <p>For the calculator&apos;s example:</p>
        <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm">
          14,500 + 2,100 + 950 + 3,400 + 1,100 + 1,850 + 4,200 − 120 = <span className="font-bold text-blue-600 dark:text-blue-400">27,980 billion</span>
        </div>
        <p>
          The result is a calculation using the components entered into this tool. It should not be interpreted as a complete substitute for an official national-accounts dataset. That distinction is important because national statistical agencies use detailed classifications, balancing procedures and source data that are not represented by a handful of user-entered fields.
        </p>
      </section>

      {/* SECTION 9 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GNP, GNI and GDP Are Different Concepts
        </h2>
        <p>
          GDP measures production within domestic territory. GNI measures income accruing to the nation&apos;s residents, including relevant income flows from abroad and to the rest of the world.
        </p>
        <p>Conceptually:</p>
        <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          GNI = GDP + net primary income from abroad
        </div>
        <p>
          The terminology and exact accounting treatment depend on the national-accounting framework being used. This distinction becomes especially important when interpreting an income-based calculation or international income classifications. Do not automatically treat GDP and GNI as interchangeable.
        </p>
      </section>

      {/* SECTION 10 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Production Approach and Gross Value Added
        </h2>
        <p>The production approach asks: How much value was added during production?</p>
        <p>A simplified relationship is:</p>
        <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          GVA = Gross Output − Intermediate Inputs
        </div>
        <p>
          Gross value added, or GVA, represents the value added by producers after subtracting intermediate goods and services used in production.
        </p>
        <p>The calculator then adds the specified net product taxes to derive its GDP contribution:</p>
        <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          GDP = GVA + net product taxes
        </div>
        <p><strong>Example:</strong></p>
        <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm space-y-1">
          <div>Gross output: 52,000 billion</div>
          <div>Intermediate inputs: 26,000 billion</div>
          <div>GVA = 52,000 − 26,000 = <strong className="text-emerald-600 dark:text-emerald-400">26,000 billion</strong></div>
          <div>With net product taxes of 2,380 billion:</div>
          <div>26,000 + 2,380 = <strong className="text-blue-600 dark:text-blue-400">28,380 billion</strong></div>
        </div>
        <p>The calculator&apos;s production golden case confirms these values.</p>
      </section>

      {/* SECTION 11 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GVA vs GDP
        </h2>
        <p>GVA and GDP are related but not identical. A simplified distinction is:</p>
        <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          GDP ≈ GVA + taxes on products less subsidies
        </div>
        <p>
          Thus, GVA describes value added by industries while GDP is the broader final production measure after the relevant product-tax adjustment.
        </p>
        <p>
          The exact national-accounts treatment is more detailed than this simplified classroom relationship, so the calculator should be interpreted as an educational/analytical model rather than a replacement for an official statistical production table.
        </p>
      </section>

      {/* SECTION 12 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Nominal GDP vs Real GDP
        </h2>
        <p>Nominal GDP is valued at current prices.</p>
        <p>
          Real GDP attempts to isolate changes in the volume of production by removing the effect of price changes. For example, if nominal GDP increases 8% but prices have also increased substantially, the actual increase in production volume may be much smaller.
        </p>
        <p>This is why economists distinguish between nominal GDP and real GDP.</p>
      </section>

      {/* SECTION 13 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GDP Deflator
        </h2>
        <p>The GDP deflator is a price index associated with the goods and services included in GDP.</p>
        <p>A simplified index relationship is:</p>
        <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          GDP Deflator = (Nominal GDP / Real GDP) × 100
        </div>
        <p>Rearranging:</p>
        <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          Real GDP = (Nominal GDP / GDP Deflator) × 100
        </div>
        <p>when the deflator is expressed with a base-year value of 100.</p>
        <p><strong>Example:</strong></p>
        <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm space-y-1">
          <div>Nominal GDP: 28,380 billion</div>
          <div>GDP deflator: 124.5</div>
          <div>Real GDP = (28,380 / 124.5) × 100 ≈ <strong className="text-emerald-600 dark:text-emerald-400">22,795.18 billion</strong></div>
        </div>
        <p>The calculator verifies this result.</p>
        <p className="text-xs text-slate-600 dark:text-slate-400 italic">
          Important qualification: This is an index-based calculation using the entered GDP deflator. It should not automatically be treated as the same thing as an official statistical agency&apos;s published chain-dollar real GDP series. Official real GDP methodologies can use chain-weighting and detailed price and quantity information rather than a simple one-input deflator calculation.
        </p>
        {/* Contextual internal link 1: Inflation Calculator */}
        <p>
          To explore price changes from the perspective of purchasing power, the{" "}
          <Link href="/calculators/inflation-calculator" className="text-blue-600 dark:text-blue-400 font-semibold underline hover:text-blue-700">
            Inflation Calculator
          </Link>{" "}
          provides a complementary calculation.
        </p>
      </section>

      {/* SECTION 14 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          How to Interpret a GDP Deflator Above 100
        </h2>
        <p>Suppose the GDP deflator is 124.5 with 100 as the reference-period index.</p>
        <p>
          The index indicates that the relevant price level is approximately 24.5% above the base reference level. That is not automatically the same as saying “Inflation is 24.5%.”
        </p>
        <p>
          An index level and an inflation rate describe different things. An inflation rate refers to the change in a price index over a specified period, whereas a deflator level compares prices with its base/reference period.
        </p>
      </section>

      {/* SECTION 15 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GDP Growth Rate
        </h2>
        <p>The simple growth rate from one period to another is:</p>
        <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          Growth = ((GDP_current − GDP_previous) / GDP_previous) × 100
        </div>
        <p>Suppose GDP_previous = 27,360 and GDP_current = 28,380. Then:</p>
        <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm space-y-1">
          <div>Growth = ((28,380 − 27,360) / 27,360) × 100 ≈ <strong className="text-emerald-600 dark:text-emerald-400">3.73%</strong></div>
          <div>Net Expansion: 28,380 − 27,360 = <strong className="text-blue-600 dark:text-blue-400">1,020 billion</strong></div>
        </div>
        <p>Both values are verified by the calculator&apos;s golden tests.</p>
      </section>

      {/* SECTION 16 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GDP Growth vs CAGR
        </h2>
        <p>For one period, a standard growth rate is usually sufficient.</p>
        <p>For a multi-year interval, the calculator can use compound annual growth:</p>
        <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          CAGR = (GDP_final / GDP_initial)^(1/t) − 1
        </div>
        <p>where t is the number of years.</p>
        <p><strong>Example:</strong> Suppose GDP rises from 100 to 121 over 2 years. Then:</p>
        <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm">
          CAGR = (121 / 100)^(1/2) − 1 = <strong className="text-blue-600 dark:text-blue-400">10%</strong>
        </div>
        <p>
          CAGR answers a different question from a simple year-over-year growth rate: it gives the constant annual compound rate that would mathematically connect the starting and ending values.
        </p>
        {/* Contextual internal link 2: CAGR Calculator */}
        <p>
          For a broader multi-year growth calculation, the{" "}
          <Link href="/calculators/cagr-calculator" className="text-blue-600 dark:text-blue-400 font-semibold underline hover:text-blue-700">
            CAGR Calculator
          </Link>{" "}
          can be used to cross-check compound annual growth.
        </p>
      </section>

      {/* SECTION 17 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GDP Per Capita
        </h2>
        <p>GDP per capita divides total GDP by the population used in the calculation:</p>
        <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-center text-xs sm:text-sm font-bold">
          GDP per capita = GDP / Population
        </div>
        <p>The unit conversion must be handled correctly. For example:</p>
        <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm space-y-1">
          <div>GDP = 28.38 trillion dollars (28.38 × 10¹²)</div>
          <div>Population = 335 million (335 × 10⁶)</div>
          <div>GDP per capita = (28.38 × 10¹²) / (335 × 10⁶) = <strong className="text-emerald-600 dark:text-emerald-400">$84,716.42 per person</strong></div>
        </div>
        <p>The calculator&apos;s verified output is $84,716.42 per person.</p>
        <p>The calculator also expresses the annual value as a simple monthly equivalent:</p>
        <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm">
          $84,716.42 / 12 ≈ <strong className="text-blue-600 dark:text-blue-400">$7,059.70 / month</strong>
        </div>
        <p>This is only a mathematical division of annual GDP per capita; it is not a person&apos;s actual monthly income.</p>
      </section>

      {/* SECTION 18 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GDP Per Capita Is Not the Same as Average Income
        </h2>
        <p>This distinction is critical.</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs sm:text-sm font-mono my-2">
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700">
            <span className="font-bold text-blue-600 dark:text-blue-400 block font-sans mb-1">GDP per capita:</span>
            economic output / population
          </div>
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700">
            <span className="font-bold text-amber-600 dark:text-amber-400 block font-sans mb-1">Does not mean:</span>
            household income / person
          </div>
        </div>
        <p>Nor does it show how output or income is distributed among households.</p>
        <p>Two countries can have the same GDP per capita while having very different income distributions, wages, housing costs, public services, wealth distributions, inequality levels, and standards of living.</p>
        <p>GDP per capita is therefore best interpreted as a broad output-per-person indicator, not as a direct measure of an individual&apos;s earnings.</p>
      </section>

      {/* SECTION 19 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GDP Per Capita and Living Standards
        </h2>
        <p>GDP per capita can be useful for international comparisons, but it has important limitations.</p>
        <p>It does not directly measure inequality, unpaid work, environmental damage, leisure, health outcomes, household wealth, personal financial security, or the quality of institutions.</p>
        <p>The World Bank itself notes limitations of aggregate per-capita measures when explaining its income-group methodology. That is why economic analysis usually combines GDP data with other indicators rather than treating GDP per capita as a complete measure of welfare.</p>
      </section>

      {/* SECTION 20 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          GDP, PPP and International Comparison
        </h2>
        <p>
          Purchasing power parity, or PPP, is used to compare economic quantities while accounting for differences in price levels between economies. The underlying idea is different from simply converting currencies using a market exchange rate.
        </p>
        <p>
          The IMF describes PPP-valued GDP as nominal GDP converted using PPP exchange rates, producing amounts expressed in international dollars. This can be useful when comparing the relative size of economies or output across countries.
        </p>
        <p>
          However, GDP at market exchange rates and GDP at purchasing-power-parity values answer different comparison questions. Do not mix them without identifying the valuation basis.
        </p>
        {/* Contextual internal link 3: Currency Calculator */}
        <p>
          When GDP values are reported in different currencies, the{" "}
          <Link href="/calculators/currency-calculator" className="text-blue-600 dark:text-blue-400 font-semibold underline hover:text-blue-700">
            Currency Calculator
          </Link>{" "}
          can help with the arithmetic conversion before comparing the figures.
        </p>
      </section>

      {/* SECTION 21 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Why the World Bank Classification Is Different
        </h2>
        <p>The calculator&apos;s income-tier result is deliberately labeled illustrative.</p>
        <p>
          The World Bank&apos;s official income classifications are based on GNI per capita in U.S. dollars using the Atlas method, not simply nominal GDP per capita. The World Bank also updates the classifications annually.
        </p>
        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 text-xs sm:text-sm space-y-1.5 font-mono">
          <div className="font-bold text-slate-900 dark:text-slate-100 font-sans mb-1">World Bank FY2027 Classification Thresholds (2025 Atlas GNI/capita):</div>
          <div>Low income: $1,175 or less</div>
          <div>Lower-middle income: $1,176 – $4,635</div>
          <div>Upper-middle income: $4,636 – $14,375</div>
          <div>High income: above $14,375</div>
        </div>
        <p>
          These thresholds are based on 2025 GNI per capita using the Atlas method. The tiers shown by this calculator are therefore an illustrative GDP-per-capita comparison, not an official World Bank country classification. That distinction remains visible on the page.
        </p>
      </section>

      {/* SECTION 22 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          What Is the Atlas Method?
        </h2>
        <p>
          The World Bank uses the Atlas method to convert GNI per capita into current U.S. dollars for its income-group methodology. Rather than relying on a single year&apos;s market exchange rate, the method smooths exchange-rate fluctuations using a three-year moving-average conversion factor adjusted for inflation.
        </p>
        <p>
          This is why simply taking GDP / Population in current dollars does not reproduce the World Bank&apos;s official income classification.
        </p>
      </section>

      {/* SECTION 23 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Why GDP Can Grow While People Do Not Feel Richer
        </h2>
        <p>GDP is an aggregate production measure.</p>
        <p>Suppose GDP grows while population grows rapidly, prices rise, population income distribution becomes more unequal, housing costs rise, or productivity gains accrue unevenly.</p>
        <p>
          The experience of individual households may therefore differ substantially from the headline GDP growth rate. This is one reason economists examine GDP alongside employment, real income, productivity, inflation, household consumption and distributional indicators.
        </p>
      </section>

      {/* SECTION 24 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Common GDP Calculation Mistakes
        </h2>
        <div className="space-y-2.5 text-xs sm:text-sm">
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">
            <strong>Subtracting exports instead of imports:</strong> The expenditure identity is C + I + G + X − M, not C + I + G − X + M.
          </div>
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">
            <strong>Forgetting that net exports can be negative:</strong> If imports exceed exports, X − M &lt; 0, which creates a negative contribution in the identity.
          </div>
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">
            <strong>Treating GDP and GNI as identical:</strong> GDP is geographically based on domestic production; GNI is based on income accruing to residents.
          </div>
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">
            <strong>Calling GDP per capita a person&apos;s income:</strong> GDP per capita is output per person, not a wage or disposable income measure.
          </div>
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">
            <strong>Confusing a deflator level with an inflation rate:</strong> A deflator of 124.5 does not automatically mean 24.5% annual inflation.
          </div>
          <div className="p-3 bg-slate-50 dark:bg-slate-800/80 rounded-lg border border-slate-200 dark:border-slate-700">
            <strong>Treating a two-quarter decline as an automatic U.S. recession declaration:</strong> Two consecutive quarters of declining real GDP are a widely used rule of thumb, but the NBER does not define U.S. recessions using that rule alone. Its Business Cycle Dating Committee evaluates a broader set of indicators.
          </div>
        </div>
      </section>

      {/* SECTION 25 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          What Is a Recession?
        </h2>
        <p>A recession is not simply synonymous with “GDP went down.”</p>
        <p>
          The NBER describes a recession as a significant decline in economic activity spread across the economy and lasting more than a few months. The committee examines multiple indicators rather than applying a fixed two-quarter GDP rule.
        </p>
        <p>
          Therefore, this calculator&apos;s growth calculation can identify a period of negative GDP growth, but it should not be used by itself to declare an official U.S. recession.
        </p>
      </section>

      {/* SECTION 26 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Why GDP Has Limitations
        </h2>
        <p>GDP is powerful because it summarizes an enormous amount of economic activity into a single aggregate measure.</p>
        <p>But no single number can describe an entire economy. GDP does not by itself tell you:</p>
        <ul className="list-disc pl-5 space-y-1 text-xs sm:text-sm">
          <li>who receives the income</li>
          <li>whether wealth is broadly distributed</li>
          <li>whether production is environmentally sustainable</li>
          <li>whether people are financially secure</li>
          <li>whether unpaid household work is increasing</li>
          <li>whether health or education outcomes are improving</li>
        </ul>
        <p>A more complete economic analysis combines GDP with complementary indicators.</p>
      </section>

      {/* SECTION 27 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          How to Use This GDP Calculator
        </h2>
        <p>Start with the economic quantity you want to investigate:</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs sm:text-sm">
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-blue-600 dark:text-blue-400 block font-bold">For expenditure GDP:</strong>
            Enter consumption, investment, government spending, exports, and imports to view GDP, net exports, and component shares.
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-blue-600 dark:text-blue-400 block font-bold">For the income approach:</strong>
            Enter the applicable income and production-cost components and inspect the resulting GDP calculation.
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-blue-600 dark:text-blue-400 block font-bold">For real GDP:</strong>
            Enter nominal raw GDP and the GDP deflator index.
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-blue-600 dark:text-blue-400 block font-bold">For growth:</strong>
            Enter previous GDP, current GDP and the time horizon in years.
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-blue-600 dark:text-blue-400 block font-bold">For production / GVA:</strong>
            Enter gross output, intermediate inputs and net product taxes.
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-blue-600 dark:text-blue-400 block font-bold">For GDP per capita:</strong>
            Enter total GDP and population using compatible units.
          </div>
        </div>
        <p className="text-xs text-slate-600 dark:text-slate-400">
          The most important practical step is unit consistency. A GDP entered in billions combined with a population entered in persons or millions requires correct scaling.
        </p>
      </section>

      {/* SECTION 28 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          A Simple GDP Analysis Workflow
        </h2>
        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 font-mono text-xs sm:text-sm text-center font-bold text-slate-700 dark:text-slate-300 leading-relaxed">
          Enter Economic Data → Choose GDP Method → Calculate Aggregate GDP → Check Components → Analyze Shares / Net Exports → Compare Nominal vs Real GDP → Calculate Growth → Calculate GDP per Capita → Interpret With Limitations
        </div>
        <p>
          The calculator is most useful when you treat each output as one part of a larger economic analysis rather than as a standalone statement about prosperity.
        </p>
      </section>

      {/* SECTION 29 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          When to Use Each GDP Calculation
        </h2>
        <div className="overflow-x-auto my-2">
          <table className="w-full text-left border-collapse text-xs sm:text-sm border border-slate-200 dark:border-slate-700">
            <thead className="bg-slate-100 dark:bg-slate-800 font-bold border-b border-slate-200 dark:border-slate-700">
              <tr>
                <th className="p-2.5">Question</th>
                <th className="p-2.5">Most Useful Calculation</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 dark:divide-slate-800">
              <tr>
                <td className="p-2.5">How much is being spent?</td>
                <td className="p-2.5 font-semibold text-blue-600 dark:text-blue-400">Expenditure approach</td>
              </tr>
              <tr>
                <td className="p-2.5">How is production income distributed?</td>
                <td className="p-2.5 font-semibold text-blue-600 dark:text-blue-400">Income approach</td>
              </tr>
              <tr>
                <td className="p-2.5">How much value is created by production?</td>
                <td className="p-2.5 font-semibold text-blue-600 dark:text-blue-400">Production / GVA approach</td>
              </tr>
              <tr>
                <td className="p-2.5">Has output changed after adjusting for prices?</td>
                <td className="p-2.5 font-semibold text-blue-600 dark:text-blue-400">Real GDP</td>
              </tr>
              <tr>
                <td className="p-2.5">How quickly is GDP changing?</td>
                <td className="p-2.5 font-semibold text-blue-600 dark:text-blue-400">Growth rate</td>
              </tr>
              <tr>
                <td className="p-2.5">What is the compound annual change?</td>
                <td className="p-2.5 font-semibold text-blue-600 dark:text-blue-400">CAGR</td>
              </tr>
              <tr>
                <td className="p-2.5">What is GDP relative to population?</td>
                <td className="p-2.5 font-semibold text-blue-600 dark:text-blue-400">GDP per capita</td>
              </tr>
              <tr>
                <td className="p-2.5">How important is each expenditure component?</td>
                <td className="p-2.5 font-semibold text-blue-600 dark:text-blue-400">Sector shares</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>This is why a multi-method calculator can be more useful than a page that only performs C + I + G + (X − M).</p>
      </section>

      {/* SECTION 30 */}
      <section className="space-y-3">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
          Calculator Scope and Limitations
        </h2>
        <p>This calculator is a calculation and educational analysis tool.</p>
        <p>It does not replace official national-statistics datasets or national-accounting compilation.</p>
        <ul className="list-disc pl-5 space-y-1 text-xs sm:text-sm">
          <li>The expenditure identity is a standard accounting relationship;</li>
          <li>The income and production sections simplify complex national-accounting systems into user-entered components;</li>
          <li>The real-GDP section uses the entered GDP-deflator relationship and should not automatically be treated as an official chain-dollar series;</li>
          <li>GDP per capita is output per population, not personal income;</li>
          <li>The illustrative income tiers are not the official World Bank classification;</li>
          <li>Economic results depend on the quality, period and units of the input data.</li>
        </ul>
        <p>
          For official economic reporting, use the relevant national statistical agency, international organization or source dataset for the jurisdiction and period being analyzed.
        </p>
      </section>

      {/* SECTION 31: 18 FAQS (UNFOLDED BY DEFAULT) */}
      <section className="space-y-4 pt-6 border-t border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2 mb-2">
          <HelpCircle className="h-5 w-5 text-blue-600 dark:text-blue-400" />
          <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
            Frequently Asked Questions
          </h2>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, idx) => {
            const isOpen = openFaqIndices.has(idx);
            return (
              <div
                key={idx}
                className="border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden bg-white dark:bg-slate-900 shadow-xs"
              >
                <button
                  type="button"
                  onClick={() => toggleFaq(idx)}
                  className="w-full p-4 text-left text-xs sm:text-sm font-semibold text-slate-900 dark:text-slate-100 flex items-center justify-between hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors cursor-pointer"
                >
                  <span className="flex items-center gap-2 pr-4">
                    <span className="text-blue-600 dark:text-blue-400 font-sans tabular-nums text-xs font-bold shrink-0">
                      Q{idx + 1}.
                    </span>
                    {faq.question}
                  </span>
                  <ChevronDown
                    className={`h-4 w-4 text-slate-400 shrink-0 transition-transform duration-200 ${
                      isOpen ? "rotate-180" : ""
                    }`}
                  />
                </button>
                {isOpen && (
                  <div className="p-4 pt-0 text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-relaxed bg-slate-50/50 dark:bg-slate-800/30 font-normal">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* SECTION 32: REFERENCES */}
      <section className="space-y-3 pt-6 border-t border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2 mb-2">
          <BookOpen className="h-5 w-5 text-blue-600 dark:text-blue-400" />
          <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
            Scientific and Economic References
          </h2>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-slate-900 dark:text-slate-100 block">U.S. Bureau of Economic Analysis — Expenditure Approach</strong>
            <p className="text-slate-600 dark:text-slate-400">
              BEA describes GDP&apos;s expenditure approach as consumption plus investment plus government spending plus exports less imports, and explains why imports are subtracted.
            </p>
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-slate-900 dark:text-slate-100 block">U.S. Bureau of Economic Analysis — Income Approach</strong>
            <p className="text-slate-600 dark:text-slate-400">
              BEA describes the income approach using compensation, production taxes less subsidies, operating surplus and consumption of fixed capital.
            </p>
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-slate-900 dark:text-slate-100 block">World Bank — Country Income Classification</strong>
            <p className="text-slate-600 dark:text-slate-400">
              The World Bank&apos;s official classifications use GNI per capita in U.S. dollars converted using the Atlas method, with annual classification updates.
            </p>
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-slate-900 dark:text-slate-100 block">World Bank — Current FY2027 Thresholds</strong>
            <p className="text-slate-600 dark:text-slate-400">
              The current FY2027 classification uses 2025 Atlas-method GNI per capita and the thresholds described above.
            </p>
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-slate-900 dark:text-slate-100 block">IMF — PPP GDP</strong>
            <p className="text-slate-600 dark:text-slate-400">
              The IMF explains PPP-valued GDP and the use of PPP conversion factors for international comparison.
            </p>
          </div>
          <div className="p-3.5 bg-slate-50 dark:bg-slate-800/80 rounded-xl border border-slate-200 dark:border-slate-700 space-y-1">
            <strong className="text-slate-900 dark:text-slate-100 block">NBER — U.S. Recession Dating</strong>
            <p className="text-slate-600 dark:text-slate-400">
              NBER explains that U.S. recession dating is based on a broad assessment of economic activity rather than a fixed two-quarter GDP rule.
            </p>
          </div>
        </div>
      </section>
    </article>
  );
}

export default GDPContent;
