import { CalculatorModuleDefinition } from "../../types";
import { calculateExpenditureGdp } from "@/lib/calculator-engine/formulas/gdp";

export const GDP_CALCULATOR: CalculatorModuleDefinition = {
  id: "gdp",
  title: "GDP Calculator",
  slug: "gdp-calculator",
  category: "Other",
  subcategory: "Science & Education",
  description:
    "Calculate GDP using the expenditure, income and production approaches, then analyze real GDP, growth, GDP per capita and economic composition.",
  iconName: "Globe",
  featured: true,
  tags: [
    "GDP calculator",
    "GDP calculation",
    "GDP formula",
    "how to calculate GDP",
    "expenditure approach GDP calculator",
    "C + I + G + (X - M)",
    "income approach GDP",
    "production approach GDP",
    "GVA calculator",
    "real GDP calculator",
    "GDP deflator calculator",
    "GDP growth calculator",
    "CAGR calculator",
    "GDP per capita calculator",
    "GDP per capita formula",
    "nominal GDP vs real GDP",
    "net exports GDP",
    "sector shares",
  ],
  formulaDescription:
    "Expenditure Approach: GDP = C + I + G + (X - M). Real GDP = (Nominal GDP / GDP Deflator) * 100.",
  relatedCalculators: [
    "inflation-calculator",
    "cagr-calculator",
    "currency-calculator",
  ],
  faqs: [
    {
      question: "What is GDP?",
      answer:
        "GDP is the market value of final goods and services produced within an economy over a specified period. It is a measure of economic production, not a complete measure of welfare.",
    },
    {
      question: "What is the formula for GDP?",
      answer:
        "The expenditure identity is GDP = C + I + G + (X - M), where C is personal consumption, I is gross investment, G is government spending, and (X - M) represents net exports.",
    },
    {
      question: "Why are imports subtracted from GDP?",
      answer:
        "Imports are subtracted in the expenditure approach so that spending on foreign-produced goods and services is not mistakenly counted as domestic production.",
    },
    {
      question: "What is net exports?",
      answer:
        "Net exports are NX = X - M. A positive value indicates a trade surplus (exports exceed imports), while a negative value represents a trade deficit (imports exceed exports).",
    },
    {
      question: "What are the three approaches to GDP?",
      answer:
        "The three broad approaches are the expenditure approach (what is purchased), income approach (who earns), and production approach (what is produced). They measure the same aggregate production from different accounting perspectives.",
    },
    {
      question: "What is GVA?",
      answer:
        "Gross Value Added (GVA) measures the economic value generated by producers after subtracting intermediate inputs from gross output: GVA = Gross Output - Intermediate Inputs.",
    },
    {
      question: "What is the difference between nominal GDP and real GDP?",
      answer:
        "Nominal GDP evaluates economic output using current market prices. Real GDP adjusts nominal output using a GDP price deflator to measure volume changes independent of inflation.",
    },
    {
      question: "How is real GDP calculated from the GDP deflator?",
      answer:
        "When the deflator uses a base index of 100, Real GDP = (Nominal GDP / GDP Deflator) * 100.",
    },
    {
      question: "What is GDP growth?",
      answer:
        "GDP growth measures the percentage change in GDP between periods: ((GDP_current - GDP_previous) / GDP_previous) * 100.",
    },
    {
      question: "What is CAGR for GDP?",
      answer:
        "Compound Annual Growth Rate (CAGR) computes the constant annualized rate connecting initial and final GDP values: CAGR = (GDP_final / GDP_initial)^(1/years) - 1.",
    },
    {
      question: "What is GDP per capita?",
      answer:
        "GDP per capita divides total GDP by resident population (GDP / Population). It represents average economic output per person, not an individual's salary or household income.",
    },
    {
      question: "Is GDP per capita the same as income per person?",
      answer:
        "No. GDP per capita measures economic output per resident. It does not measure wages, take-home pay, household wealth, or how income is distributed.",
    },
    {
      question: "What is the difference between GDP and GNI?",
      answer:
        "GDP measures production within a country's geographic borders. Gross National Income (GNI) measures income accruing to permanent residents, including net primary income received from abroad.",
    },
    {
      question: "What is PPP GDP?",
      answer:
        "Purchasing Power Parity (PPP) GDP adjusts nominal figures using standardized price-level baskets to eliminate currency exchange-rate distortions for international output comparisons.",
    },
    {
      question: "Does two consecutive quarters of falling GDP officially mean the United States is in recession?",
      answer:
        "Not automatically. Two consecutive quarters of declining real GDP are a widely used rule of thumb, but the NBER Business Cycle Dating Committee evaluates economy-wide depth, diffusion, and duration across payrolls, real income, consumption, and industrial output.",
    },
    {
      question: "Does the income tier in this calculator represent an official World Bank classification?",
      answer:
        "No. The tier is explicitly illustrative and based on GDP per capita. The official World Bank country income classification uses GNI per capita converted via the Atlas method and updates thresholds annually.",
    },
    {
      question: "What are the current World Bank income thresholds?",
      answer:
        "For the current FY2027 classification, the World Bank reports low income at $1,175 or less, lower-middle at $1,176–$4,635, upper-middle at $4,636–$14,375, and high income above $14,375 based on 2025 Atlas-method GNI per capita.",
    },
    {
      question: "Can GDP increase while people's living standards do not improve?",
      answer:
        "Yes. GDP can grow while population growth, inflation, rising inequality, increasing housing costs, or environmental degradation diminish the living standards of individual households.",
    },
  ],
  inputs: [
    {
      name: "personalConsumption",
      label: "Personal Consumption (C)",
      type: "currency",
      defaultValue: 19100,
      min: 0,
      max: 1000000,
      step: 100,
    },
    {
      name: "grossInvestment",
      label: "Gross Investment (I)",
      type: "currency",
      defaultValue: 5100,
      min: 0,
      max: 1000000,
      step: 100,
    },
    {
      name: "governmentSpending",
      label: "Government Spending (G)",
      type: "currency",
      defaultValue: 4850,
      min: 0,
      max: 1000000,
      step: 100,
    },
    {
      name: "exports",
      label: "Exports (X)",
      type: "currency",
      defaultValue: 3150,
      min: 0,
      max: 1000000,
      step: 100,
    },
    {
      name: "imports",
      label: "Imports (M)",
      type: "currency",
      defaultValue: 3820,
      min: 0,
      max: 1000000,
      step: 100,
    },
  ],
  outputs: [
    {
      name: "totalGdp",
      label: "Total Gross Domestic Product",
      format: "currency",
    },
    {
      name: "netExports",
      label: "Net Exports (X - M)",
      format: "currency",
    },
    {
      name: "gdpPerCapita",
      label: "GDP Per Capita",
      format: "currency",
    },
  ],
  calculate: (inputs: Record<string, any>) => {
    const res = calculateExpenditureGdp({
      personalConsumption: Number(inputs.personalConsumption) || 19100,
      grossInvestment: Number(inputs.grossInvestment) || 5100,
      governmentSpending: Number(inputs.governmentSpending) || 4850,
      exports: Number(inputs.exports) || 3150,
      imports: Number(inputs.imports) || 3820,
      population: 335000000,
    });

    return {
      totalGdp: res.totalGdp,
      netExports: res.netExports,
      gdpPerCapita: res.gdpPerCapita * 1000000000,
    };
  },
};

export default GDP_CALCULATOR;
