"use client";

import React from "react";

export function DepreciationContent() {
  const faqs = [
    {
      question: "1. What is asset depreciation in financial accounting?",
      answer:
        "Depreciation is the systematic allocation of a tangible asset's cost over its estimated useful economic life. In accordance with the GAAP and IFRS matching principle, depreciation matches the expense of acquiring a productive asset with the revenue generated by that asset across accounting periods.",
    },
    {
      question: "2. What is the difference between Straight-Line and Accelerated Depreciation?",
      answer:
        "Straight-Line distributes depreciation expense evenly in equal amounts across every year of useful life. Accelerated methods (such as Double Declining Balance and Sum-of-Years' Digits) recognize larger depreciation expenses in the earlier years of an asset's life when it is most productive and loses market value fastest.",
    },
    {
      question: "3. What is Salvage Value (Residual Value)?",
      answer:
        "Salvage value (scrap or residual value) is the estimated net realizable dollar amount an organization expects to receive when selling or disposing of an asset at the end of its useful life. Under GAAP, an asset cannot be depreciated below its salvage value.",
    },
    {
      question: "4. How is Double Declining Balance (DDB) calculated?",
      answer:
        "Double Declining Balance applies a depreciation rate equal to double the straight-line rate (200% ÷ Useful Life) against the asset's beginning Net Book Value each year. Unlike straight-line, salvage value is ignored in the annual rate calculation, but depreciation stops once book value drops to salvage value.",
    },
    {
      question: "5. What is the Sum-of-the-Years'-Digits (SYD) method?",
      answer:
        "SYD is an accelerated depreciation method that multiplies the depreciable base (Cost - Salvage) by a declining fraction. The denominator is the sum of digits from 1 to n (calculated as n(n+1)/2), and the numerator is the remaining years of useful life.",
    },
    {
      question: "6. When should a business use the Units of Production method?",
      answer:
        "Units of Production is ideal for assets whose wear-and-tear is directly tied to usage rather than time, such as manufacturing machinery (hours operated), vehicles (miles driven), or commercial printing presses (pages printed).",
    },
    {
      question: "7. What is MACRS (Modified Accelerated Cost Recovery System)?",
      answer:
        "MACRS is the mandatory tax depreciation system used in the United States for federal income tax returns under IRS Section 168. It assigns property to statutory recovery classes (e.g. 3-year, 5-year, 7-year) and ignores salvage value to maximize upfront tax deductions.",
    },
    {
      question: "8. How does partial-year depreciation work when an asset is bought mid-year?",
      answer:
        "When an asset is placed in service during a fiscal year, depreciation must be prorated based on an accounting convention. Common conventions include the Full-Month convention (prorated by months in service) and the Half-Year convention (treating all assets as placed in service at mid-year).",
    },
    {
      question: "9. What is Section 179 expensing and Bonus Depreciation?",
      answer:
        "Section 179 allows eligible businesses to deduct 100% of the purchase price of qualifying equipment and software up to statutory limits ($1.22 million in 2024–2025) in the year purchased, rather than capitalizing and depreciating over multiple years.",
    },
    {
      question: "10. Does depreciation involve an actual cash outflow?",
      answer:
        "No. Depreciation is a non-cash expense on the income statement. While it reduces reported net accounting income and corporate tax liabilities, actual cash was paid upfront during asset acquisition.",
    },
    {
      question: "11. What is Accumulated Depreciation and Net Book Value?",
      answer:
        "Accumulated Depreciation is a contra-asset account on the balance sheet tracking all depreciation recognized from purchase to date. Net Book Value equals the original Historical Cost minus Accumulated Depreciation.",
    },
    {
      question: "12. Can land be depreciated?",
      answer:
        "No. Land has an unlimited economic useful life and does not experience wear, decay, or obsolescence; therefore, accounting standards strictly prohibit depreciating the cost of land.",
    },
  ];

  return (
    <div className="space-y-3 text-black dark:text-zinc-100 font-sans leading-relaxed">
      {/* SECTION 1: WHAT IS DEPRECIATION */}
      <div className="border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-slate-900 p-3.5 shadow-xs space-y-2.5">
        <h2 className="text-sm font-extrabold text-black dark:text-zinc-100">
          What is Asset Depreciation? Financial Principles & Accounting Rules
        </h2>
        <p className="text-xs text-black dark:text-zinc-200">
          In accounting and tax finance, depreciation is the gradual expensing of a tangible fixed asset over its estimated useful economic life. Rather than expensing the full capital expenditure in year one, businesses distribute the cost across all accounting periods benefiting from the asset:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2 pt-1">
          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold text-[11px] uppercase text-black dark:text-zinc-100 block">Historical Cost Basis</span>
            <p className="text-[11px] text-black dark:text-zinc-300">
              Total purchase price including delivery freight, installation, sales taxes, and setup testing fees.
            </p>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold text-[11px] uppercase text-black dark:text-zinc-100 block">Salvage / Scrap Value</span>
            <p className="text-[11px] text-black dark:text-zinc-300">
              Estimated terminal trade-in or resale value at retirement. Assets cannot be depreciated below salvage value.
            </p>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold text-[11px] uppercase text-black dark:text-zinc-100 block">Useful Economic Life</span>
            <p className="text-[11px] text-black dark:text-zinc-300">
              The estimated number of years or production output units the asset is expected to remain functional.
            </p>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold text-[11px] uppercase text-black dark:text-zinc-100 block">Net Book Value</span>
            <p className="text-[11px] text-black dark:text-zinc-300">
              The carrying value on the balance sheet: Historical Cost Basis minus Total Accumulated Depreciation.
            </p>
          </div>
        </div>
      </div>

      {/* SECTION 2: MATHEMATICAL FORMULAS */}
      <div className="border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-slate-900 p-3.5 shadow-xs space-y-2.5">
        <h2 className="text-sm font-extrabold text-black dark:text-zinc-100">
          Core Depreciation Methods: Step-by-Step Mathematical Formulas
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2 font-mono text-[11px]">
          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold font-sans text-xs text-black dark:text-zinc-100 block">1. Straight-Line Method</span>
            <div>Depreciation per Year = (Cost - Salvage) ÷ Useful Life</div>
            <div className="text-[10px] text-slate-500 font-sans">Equal depreciation expense every year.</div>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold font-sans text-xs text-black dark:text-zinc-100 block">2. Double Declining Balance (DDB)</span>
            <div>Depreciation = Beginning Book Value × (2 ÷ Useful Life)</div>
            <div className="text-[10px] text-slate-500 font-sans">Accelerated rate applied to declining book value; capped at salvage.</div>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold font-sans text-xs text-black dark:text-zinc-100 block">3. Sum-of-Years&apos; Digits (SYD)</span>
            <div>Depreciation = (Cost - Salvage) × [Remaining Life ÷ (n(n+1)/2)]</div>
            <div className="text-[10px] text-slate-500 font-sans">Weighted accelerated depreciation based on digit fractions.</div>
          </div>

          <div className="p-2.5 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <span className="font-bold font-sans text-xs text-black dark:text-zinc-100 block">4. Units of Production Method</span>
            <div>Depreciation = (Cost - Salvage) × (Units This Year ÷ Total Lifetime Units)</div>
            <div className="text-[10px] text-slate-500 font-sans">Depreciation varies strictly based on operating output.</div>
          </div>
        </div>
      </div>

      {/* SECTION 3: WORKED MATHEMATICAL CASE STUDIES */}
      <div className="border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-slate-900 p-3.5 shadow-xs space-y-2.5">
        <h2 className="text-sm font-extrabold text-black dark:text-zinc-100">
          Worked Mathematical Example ($11,000 Asset Cost, $1,000 Salvage, 5-Year Useful Life)
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
          <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h3 className="font-bold text-xs uppercase text-black dark:text-zinc-100">Straight-Line Method</h3>
            <div className="font-mono text-[11px] text-black dark:text-zinc-300 space-y-0.5">
              <div>• Depreciable Base = $11,000 - $1,000 = $10,000.00</div>
              <div>• Annual Expense = $10,000 ÷ 5 = <strong>$2,000.00/year</strong></div>
              <div>• Year 1 Ending Book Value = $9,000.00</div>
              <div>• Year 3 Ending Book Value = $5,000.00</div>
              <div>• Year 5 Ending Book Value = $1,000.00 (Salvage)</div>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h3 className="font-bold text-xs uppercase text-black dark:text-zinc-100">Double Declining Balance (40% Rate)</h3>
            <div className="font-mono text-[11px] text-black dark:text-zinc-300 space-y-0.5">
              <div>• DDB Rate = 2 ÷ 5 = 40.0%</div>
              <div>• Year 1 Depreciation = $11,000 × 0.40 = <strong>$4,400.00</strong> (BV: $6,600)</div>
              <div>• Year 2 Depreciation = $6,600 × 0.40 = <strong>$2,640.00</strong> (BV: $3,960)</div>
              <div>• Year 3 Depreciation = $3,960 × 0.40 = <strong>$1,584.00</strong> (BV: $2,376)</div>
              <div>• Year 4 Depreciation = $2,376 × 0.40 = <strong>$950.40</strong> (BV: $1,425.60)</div>
              <div>• Year 5 Depreciation = $1,425.60 - $1,000 = <strong>$425.60</strong> (Hits Salvage)</div>
            </div>
          </div>
        </div>
      </div>

      {/* SECTION 4: 12 FAQS ALWAYS OPEN CARDS */}
      <div className="border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-slate-900 p-3.5 shadow-xs space-y-2.5">
        <h2 className="text-sm font-extrabold text-black dark:text-zinc-100">
          Frequently Asked Questions (12 Key Depreciation FAQs)
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="border border-slate-200 dark:border-slate-800 rounded-lg p-2.5 bg-slate-50 dark:bg-slate-800/50 space-y-1"
            >
              <h3 className="font-bold text-xs text-black dark:text-zinc-100">
                {faq.question}
              </h3>
              <p className="text-[11px] text-black dark:text-zinc-300 leading-relaxed">
                {faq.answer}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
