"use client";

import React from "react";

export function ReportFooter() {
  return (
    <div className="border-t border-zinc-300 pt-3 mt-6 text-[10px] text-zinc-500 font-mono flex items-center justify-between">
      <div>
        <span>Generated by </span>
        <span className="font-bold text-zinc-900">CalcPlatform</span>
        <span> — Professional Financial Analysis Engine</span>
      </div>
      <div>
        <span>Page 1 of 1</span>
      </div>
    </div>
  );
}

export default ReportFooter;
