import { CalculatorModuleDefinition } from "../../types";

export const COMMISSION_CALCULATOR: CalculatorModuleDefinition = {
  id: "commission",
  title: "Commission Calculator",
  slug: "commission-calculator",
  category: "Finance",
  subcategory: "Business",
  description: "Calculate sales commission payout, total earnings, and net revenue after commission.",
  iconName: "Briefcase",
  featured: false,
  tags: ["commission", "sales commission", "commission payout", "sales earnings"],
  formulaDescription: "Commission = Total Sales × (Commission Rate / 100). Total Earnings = Base Salary + Commission.",
  faqs: [
    {
      question: "How is sales commission calculated?",
      answer: "Sales commission is calculated by multiplying gross sales revenue generated by the agreed-upon commission percentage rate.",
    },
  ],
  inputs: [
    { name: "totalSalesAmount", label: "Total Sales Revenue", type: "currency", defaultValue: 50000, unit: "$", min: 100, max: 10000000, step: 1000 },
    { name: "commissionRate", label: "Commission Rate", type: "percentage", defaultValue: 8.5, unit: "%", min: 0.1, max: 50, step: 0.5 },
    { name: "baseSalary", label: "Base Monthly Salary (Optional)", type: "currency", defaultValue: 3000, unit: "$", min: 0, max: 100000, step: 250 },
  ],
  outputs: [
    { name: "commissionEarned", label: "Commission Earned", format: "currency", highlight: true },
    { name: "totalCompensation", label: "Total Monthly Compensation", format: "currency", highlight: true },
    { name: "netRevenueToCompany", label: "Company Net Revenue", format: "currency" },
  ],
  calculate: (inputs) => {
    const sales = Number(inputs.totalSalesAmount || 50000);
    const rate = Number(inputs.commissionRate || 8.5) / 100;
    const base = Number(inputs.baseSalary || 3000);

    const comm = sales * rate;
    const totalComp = base + comm;
    const netCompany = sales - comm;

    return {
      commissionEarned: Number(comm.toFixed(2)),
      totalCompensation: Number(totalComp.toFixed(2)),
      netRevenueToCompany: Number(netCompany.toFixed(2)),
    };
  },
};

export default COMMISSION_CALCULATOR;
