import {
  solveMolarityMass,
  solveStockDilution,
  solveMassPercent,
  solvePPMToMolarity,
  calculateMolarityCalculator,
} from "../src/app/calculators/molarity-calculator/calculator";
import { COMMON_CHEMICAL_COMPOUNDS } from "../src/app/calculators/molarity-calculator/compounds";
import { CalculatorReportData } from "../src/components/report/types";

console.log("=================================================");
console.log("TESTING LIVE PDF REPORT DATA GENERATION ACROSS MODES");
console.log("=================================================");

function buildTestReportData(params: {
  mode: "mass_solver" | "dilution" | "mass_percent" | "ppm_converter";
  solveVariable: "molarity" | "mass" | "volume" | "molar_mass";
  solveDilutionTarget: "v1" | "c1" | "v2" | "c2";
  selectedCompound: any;
  molarMassInput: number;
  hydrateWaters: number;
  molarityValue: number;
  molarityUnit: string;
  massValue: number;
  massUnit: string;
  volumeValue: number;
  volumeUnit: string;
  c1: number;
  v1: number;
  c2: number;
  v2: number;
  massPercent: number;
  reagentDensity: number;
  valence: number;
  ppmValue: number;
  solventDensity: number;
  result: any;
}): CalculatorReportData {
  const {
    mode,
    solveVariable,
    solveDilutionTarget,
    selectedCompound,
    molarMassInput,
    hydrateWaters,
    molarityValue,
    molarityUnit,
    massValue,
    massUnit,
    volumeValue,
    volumeUnit,
    c1,
    v1,
    c2,
    v2,
    massPercent,
    reagentDensity,
    valence,
    ppmValue,
    solventDensity,
    result,
  } = params;

  const now = new Date();
  const generatedDate = "September 13, 2026";
  const generatedTime = "11:30 AM";

  if (mode === "dilution") {
    const dil = result.dilutionResult;
    const targetLabel =
      solveDilutionTarget === "v1"
        ? `Stock Volume (V₁): ${dil?.v1.toFixed(2)} mL`
        : solveDilutionTarget === "c1"
        ? `Stock Concentration (C₁): ${dil?.c1.toFixed(4)} M`
        : solveDilutionTarget === "v2"
        ? `Final Volume (V₂): ${dil?.v2.toFixed(2)} mL`
        : `Target Concentration (C₂): ${dil?.c2.toFixed(4)} M`;

    return {
      meta: {
        calculatorName: "Molarity Calculator & Dilution Solver",
        reportTitle: "STOCK DILUTION PROTOCOL REPORT (C₁V₁ = C₂V₂)",
        generatedDate,
        generatedTime,
      },
      keyMetrics: [
        { label: "Solved Dilution Target", value: targetLabel, colorTheme: "emerald" },
        { label: "Solvent Required", value: `${dil?.solventVolumeNeeded.toFixed(2) || "0.00"} mL`, colorTheme: "blue" },
      ],
      sections: [
        {
          title: "DILUTION PARAMETERS",
          items: [
            { label: "Target Solved Variable", value: solveDilutionTarget.toUpperCase() },
            { label: "Stock Concentration (C₁)", value: `${dil?.c1.toFixed(4) || c1} M` },
            { label: "Stock Volume (V₁)", value: `${dil?.v1.toFixed(2) || v1} mL` },
            { label: "Target Concentration (C₂)", value: `${dil?.c2.toFixed(4) || c2} M` },
            { label: "Final Volume (V₂)", value: `${dil?.v2.toFixed(2) || v2} mL` },
            { label: "Solvent Volume to Add", value: `${dil?.solventVolumeNeeded.toFixed(2) || 0} mL` },
          ],
        },
        {
          title: "LABORATORY BENCH PROTOCOL",
          items: (result.benchProtocol || []).map((step: string, idx: number) => ({
            label: `Step ${idx + 1}`,
            value: step,
          })),
        },
      ],
      notes: [
        "Generated by CalcPlatform Molarity Calculator & Dilution Solver engine.",
        "Volumes assume ideal dilution additivity in aqueous solutions.",
      ],
    };
  }

  if (mode === "mass_percent") {
    const mp = result.massPercentResult;
    return {
      meta: {
        calculatorName: "Molarity Calculator & Dilution Solver",
        reportTitle: "MASS PERCENT & REAGENT DENSITY REPORT",
        generatedDate,
        generatedTime,
      },
      keyMetrics: [
        { label: "Calculated Molarity", value: `${mp?.molarityM ?? "0"} M`, colorTheme: "emerald" },
        { label: "Calculated Normality", value: `${mp?.normalityN ?? "0"} N`, colorTheme: "purple" },
      ],
      sections: [
        {
          title: "REAGENT SPECIFICATIONS",
          items: [
            { label: "Selected Compound", value: selectedCompound ? `${selectedCompound.name} (${selectedCompound.formula})` : "Custom" },
            { label: "Solute Molar Mass", value: `${molarMassInput} g/mol` },
            { label: "Mass Percentage", value: `${massPercent} % w/w` },
            { label: "Reagent Density", value: `${reagentDensity} g/mL` },
            { label: "Valence / Equivalence Factor (n)", value: `${valence}` },
          ],
        },
        {
          title: "CALCULATED PARAMETERS",
          items: [
            { label: "Molarity", value: `${mp?.molarityM ?? "0"} mol/L (M)`, highlight: true },
            { label: "Normality", value: `${mp?.normalityN ?? "0"} equiv/L (N)` },
            { label: "Moles per Liter", value: `${mp?.molesPerLiter ?? "0"} mol` },
          ],
        },
      ],
      notes: [
        "Generated by CalcPlatform Molarity Calculator engine.",
        "Normality accounts for reactive equivalence (N = M × n).",
      ],
    };
  }

  if (mode === "ppm_converter") {
    const ppmRes = result.ppmResult;
    return {
      meta: {
        calculatorName: "Molarity Calculator & Dilution Solver",
        reportTitle: "PARTS PER MILLION (PPM) CONVERSION REPORT",
        generatedDate,
        generatedTime,
      },
      keyMetrics: [
        { label: "Calculated Molarity", value: `${ppmRes?.molarityM ?? "0"} M`, colorTheme: "emerald" },
        { label: "Calculated Molality", value: `${ppmRes?.molalityM ?? "0"} mol/kg`, colorTheme: "teal" },
      ],
      sections: [
        {
          title: "CONCENTRATION INPUTS",
          items: [
            { label: "Selected Compound", value: selectedCompound ? `${selectedCompound.name} (${selectedCompound.formula})` : "Custom" },
            { label: "Solute Molar Mass", value: `${molarMassInput} g/mol` },
            { label: "Parts Per Million (PPM)", value: `${ppmValue} ppm (mg/L)` },
            { label: "Solvent Density", value: `${solventDensity} g/mL` },
          ],
        },
        {
          title: "CONVERTED SOLUTION CONCENTRATIONS",
          items: [
            { label: "Molarity", value: `${ppmRes?.molarityM ?? "0"} mol/L (M)`, highlight: true },
            { label: "Molality", value: `${ppmRes?.molalityM ?? "0"} mol/kg (m)` },
          ],
        },
      ],
      notes: [
        "Generated by CalcPlatform Molarity Calculator engine.",
        "Molality accounts for solute mass displacement in solution volume.",
      ],
    };
  }

  // Default: Mass Solver
  const hydrateLabels: Record<number, string> = {
    0: "Anhydrous (+0 g/mol)",
    1: "Monohydrate (+18.015 g/mol)",
    2: "Dihydrate (+36.030 g/mol)",
    3: "Trihydrate (+54.045 g/mol)",
    5: "Pentahydrate (+90.075 g/mol)",
    7: "Heptahydrate (+126.105 g/mol)",
  };

  const solvedLabel =
    solveVariable === "molarity"
      ? `Calculated Molarity: ${result.formattedSolvedValue} M`
      : solveVariable === "mass"
      ? `Calculated Solute Mass: ${result.formattedSolvedValue} g`
      : solveVariable === "volume"
      ? `Calculated Volume: ${result.formattedSolvedValue} L`
      : `Calculated Molar Mass: ${result.formattedSolvedValue} g/mol`;

  return {
    meta: {
      calculatorName: "Molarity Calculator & Dilution Solver",
      reportTitle: "SOLUTION PREPARATION ANALYSIS REPORT",
      generatedDate,
      generatedTime,
    },
    keyMetrics: [
      { label: `Solved ${solveVariable.replace("_", " ").toUpperCase()}`, value: solvedLabel, colorTheme: "emerald" },
      { label: "Effective Molar Mass", value: `${(result.molarMass || molarMassInput).toFixed(3)} g/mol`, colorTheme: "blue" },
    ],
    sections: [
      {
        title: "SOLUTION INPUT PARAMETERS",
        items: [
          { label: "Solute Compound", value: selectedCompound ? `${selectedCompound.name} (${selectedCompound.formula})` : "Custom" },
          { label: "Base Molar Mass", value: `${molarMassInput} g/mol` },
          { label: "Hydrate State", value: hydrateLabels[hydrateWaters] || `${hydrateWaters} H2O` },
          { label: "Effective Formula Weight", value: `${(result.molarMass || molarMassInput).toFixed(3)} g/mol` },
          { label: "Target Concentration", value: `${molarityValue} ${molarityUnit}` },
          { label: "Target Solute Mass", value: `${massValue} ${massUnit}` },
          { label: "Target Solution Volume", value: `${volumeValue} ${volumeUnit}` },
        ],
      },
      {
        title: "LABORATORY BENCH PREPARATION PROTOCOL",
        items: (result.benchProtocol || []).map((step: string, idx: number) => ({
          label: `Step ${idx + 1}`,
          value: step,
        })),
      },
    ],
    notes: [
      "Generated by CalcPlatform Molarity Calculator engine.",
      "Results calibrated for standard 20°C volumetric preparation in Class A glassware.",
    ],
  };
}

// TEST PDF-1: Mass Solver NaCl, M = 0.250, V = 0.500 L -> 7.305 g
const res1 = calculateMolarityCalculator({
  mode: "mass_solver",
  solveVariable: "mass",
  molarityM: 0.250,
  volumeLiters: 0.500,
  molarMass: 58.44,
  hydrateWaters: 0,
});
const report1 = buildTestReportData({
  mode: "mass_solver",
  solveVariable: "mass",
  solveDilutionTarget: "v1",
  selectedCompound: COMMON_CHEMICAL_COMPOUNDS[0],
  molarMassInput: 58.44,
  hydrateWaters: 0,
  molarityValue: 0.250,
  molarityUnit: "M",
  massValue: 0,
  massUnit: "g",
  volumeValue: 0.500,
  volumeUnit: "L",
  c1: 10, v1: 10, c2: 1, v2: 100,
  massPercent: 37, reagentDensity: 1.19, valence: 1,
  ppmValue: 500, solventDensity: 1.00,
  result: res1,
});

console.log("\n[TEST PDF-1] Checking 0.250 M, 0.500 L NaCl report data:");
const pdf1Value = report1.keyMetrics[0].value;
console.log("Metric Value:", pdf1Value);
if (pdf1Value.includes("7.305") && !pdf1Value.includes("58.44 g")) {
  console.log("PASS: Report accurately contains 7.305 g and NOT static 58.44 g!");
} else {
  console.error("FAIL: Report contains stale/default value!");
  process.exit(1);
}

// TEST PDF-2: Change input to M = 0.500, V = 1.000 L -> 29.220 g
const res2 = calculateMolarityCalculator({
  mode: "mass_solver",
  solveVariable: "mass",
  molarityM: 0.500,
  volumeLiters: 1.000,
  molarMass: 58.44,
  hydrateWaters: 0,
});
const report2 = buildTestReportData({
  mode: "mass_solver",
  solveVariable: "mass",
  solveDilutionTarget: "v1",
  selectedCompound: COMMON_CHEMICAL_COMPOUNDS[0],
  molarMassInput: 58.44,
  hydrateWaters: 0,
  molarityValue: 0.500,
  molarityUnit: "M",
  massValue: 0,
  massUnit: "g",
  volumeValue: 1.000,
  volumeUnit: "L",
  c1: 10, v1: 10, c2: 1, v2: 100,
  massPercent: 37, reagentDensity: 1.19, valence: 1,
  ppmValue: 500, solventDensity: 1.00,
  result: res2,
});
console.log("\n[TEST PDF-2] Checking 0.500 M, 1.000 L NaCl report data:");
const pdf2Value = report2.keyMetrics[0].value;
console.log("Metric Value:", pdf2Value);
if (pdf2Value.includes("29.220")) {
  console.log("PASS: Report accurately contains 29.220 g!");
} else {
  console.error("FAIL: Report failed to update to 29.220 g!");
  process.exit(1);
}

// TEST PDF-3: Dilution C1=10, C2=1, V2=100, solve V1 -> 10.00 mL
const res3 = calculateMolarityCalculator({
  mode: "dilution",
  c1: 10, v1: 0, c2: 1, v2: 100,
  solveTarget: "v1",
});
const report3 = buildTestReportData({
  mode: "dilution",
  solveVariable: "mass",
  solveDilutionTarget: "v1",
  selectedCompound: COMMON_CHEMICAL_COMPOUNDS[0],
  molarMassInput: 58.44, hydrateWaters: 0,
  molarityValue: 1, molarityUnit: "M", massValue: 58.44, massUnit: "g", volumeValue: 1, volumeUnit: "L",
  c1: 10, v1: 0, c2: 1, v2: 100,
  massPercent: 37, reagentDensity: 1.19, valence: 1,
  ppmValue: 500, solventDensity: 1.00,
  result: res3,
});
console.log("\n[TEST PDF-3] Checking dilution solve V1 report data:");
const pdf3Value = report3.keyMetrics[0].value;
console.log("Metric Value:", pdf3Value);
if (pdf3Value.includes("10.00 mL")) {
  console.log("PASS: Dilution report contains 10.00 mL!");
} else {
  console.error("FAIL: Dilution report does not contain 10.00 mL!");
  process.exit(1);
}

// TEST PDF-4: Dilution solve C2 -> C2 = 0.5000 M
const res4 = calculateMolarityCalculator({
  mode: "dilution",
  c1: 5, v1: 20, c2: 0, v2: 200,
  solveTarget: "c2",
});
const report4 = buildTestReportData({
  mode: "dilution",
  solveVariable: "mass",
  solveDilutionTarget: "c2",
  selectedCompound: COMMON_CHEMICAL_COMPOUNDS[0],
  molarMassInput: 58.44, hydrateWaters: 0,
  molarityValue: 1, molarityUnit: "M", massValue: 58.44, massUnit: "g", volumeValue: 1, volumeUnit: "L",
  c1: 5, v1: 20, c2: 0, v2: 200,
  massPercent: 37, reagentDensity: 1.19, valence: 1,
  ppmValue: 500, solventDensity: 1.00,
  result: res4,
});
console.log("\n[TEST PDF-4] Checking dilution solve C2 report data:");
const pdf4Value = report4.keyMetrics[0].value;
console.log("Metric Value:", pdf4Value);
if (pdf4Value.includes("C₂") && pdf4Value.includes("0.5000 M")) {
  console.log("PASS: Dilution report accurately reflects C2 = 0.5000 M!");
} else {
  console.error("FAIL: Dilution report does not reflect C2!");
  process.exit(1);
}

// TEST PDF-5: Mass percent 37% HCl -> ~12.0762 M
const res5 = calculateMolarityCalculator({
  mode: "mass_percent",
  massPercent: 37,
  densityGperML: 1.19,
  molarMass: 36.46,
  valence: 1,
});
const report5 = buildTestReportData({
  mode: "mass_percent",
  solveVariable: "mass",
  solveDilutionTarget: "v1",
  selectedCompound: COMMON_CHEMICAL_COMPOUNDS[5],
  molarMassInput: 36.46, hydrateWaters: 0,
  molarityValue: 1, molarityUnit: "M", massValue: 58.44, massUnit: "g", volumeValue: 1, volumeUnit: "L",
  c1: 10, v1: 10, c2: 1, v2: 100,
  massPercent: 37, reagentDensity: 1.19, valence: 1,
  ppmValue: 500, solventDensity: 1.00,
  result: res5,
});
console.log("\n[TEST PDF-5] Checking mass percent report data:");
const pdf5Value = report5.keyMetrics[0].value;
console.log("Metric Value:", pdf5Value);
if (pdf5Value.includes("12.0762 M")) {
  console.log("PASS: Mass percent report reflects 12.0762 M!");
} else {
  console.error("FAIL: Mass percent report does not reflect 12.0762 M!");
  process.exit(1);
}

// TEST PDF-6: PPM 500 ppm NaCl -> 0.008556 M
const res6 = calculateMolarityCalculator({
  mode: "ppm_converter",
  ppm: 500,
  densityGperML: 1.00,
  molarMass: 58.44,
});
const report6 = buildTestReportData({
  mode: "ppm_converter",
  solveVariable: "mass",
  solveDilutionTarget: "v1",
  selectedCompound: COMMON_CHEMICAL_COMPOUNDS[0],
  molarMassInput: 58.44, hydrateWaters: 0,
  molarityValue: 1, molarityUnit: "M", massValue: 58.44, massUnit: "g", volumeValue: 1, volumeUnit: "L",
  c1: 10, v1: 10, c2: 1, v2: 100,
  massPercent: 37, reagentDensity: 1.19, valence: 1,
  ppmValue: 500, solventDensity: 1.00,
  result: res6,
});
console.log("\n[TEST PDF-6] Checking PPM converter report data:");
const pdf6Value = report6.keyMetrics[0].value;
console.log("Metric Value:", pdf6Value);
if (pdf6Value.includes("0.008556 M")) {
  console.log("PASS: PPM report reflects 0.008556 M!");
} else {
  console.error("FAIL: PPM report does not reflect 0.008556 M!");
  process.exit(1);
}

console.log("\n=================================================");
console.log("ALL LIVE PDF REPORT TESTS PASSED WITH 100% ACCURACY!");
console.log("=================================================");
