import { CalculatorModuleDefinition } from "../../types";
import { calculateAutoLeaseFormula } from "@/lib/calculator-engine/formulas/auto-lease";
import { AUTO_LEASE_FAQS } from "./faq";

export const AUTO_LEASE_CALCULATOR: CalculatorModuleDefinition = {
  id: "auto-lease",
  title: "Auto Lease Calculator – Monthly Payment, Lease Cost & Money Factor",
  slug: "auto-lease-calculator",
  category: "Finance",
  subcategory: "Auto",
  description:
    "Use this Auto Lease Calculator to estimate monthly lease payments, depreciation, money factor, residual value, taxes, fees, mileage penalties, total lease cost, and lease vs. buy savings.",
  iconName: "Car",
  featured: true,
  tags: [
    "auto lease",
    "car lease calculator",
    "money factor",
    "residual value",
    "lease vs buy",
    "capitalized cost",
    "mileage penalty",
  ],
  formulaDescription:
    "Monthly Lease Payment = Monthly Depreciation [(Net Cap Cost - Residual) / Term] + Monthly Rent Charge [(Net Cap Cost + Residual) × Money Factor] + Monthly Tax",
  faqs: AUTO_LEASE_FAQS,
  inputs: [
    {
      name: "autoPrice",
      label: "Vehicle Negotiated Price (Cap Cost)",
      type: "currency",
      defaultValue: 35000,
      unit: "$",
      min: 5000,
      max: 300000,
      step: 500,
      tooltip: "Negotiated selling price of the leased vehicle",
    },
    {
      name: "vehicleMsrp",
      label: "Vehicle MSRP Sticker Price",
      type: "currency",
      defaultValue: 36000,
      unit: "$",
      min: 5000,
      max: 300000,
      step: 500,
      tooltip: "Manufacturer Suggested Retail Price (used for residual value %)",
    },
    {
      name: "downPayment",
      label: "Down Payment / Cap Reduction",
      type: "currency",
      defaultValue: 2500,
      unit: "$",
      min: 0,
      max: 50000,
      step: 250,
      tooltip: "Upfront cash payment to reduce capitalized cost",
    },
    {
      name: "tradeInValue",
      label: "Trade-In Value",
      type: "currency",
      defaultValue: 2000,
      unit: "$",
      min: 0,
      max: 100000,
      step: 250,
      tooltip: "Allowance offered for your trade-in vehicle",
    },
    {
      name: "leaseTermMonths",
      label: "Lease Term Duration",
      type: "slider",
      defaultValue: 36,
      unit: "months",
      min: 12,
      max: 60,
      step: 6,
      tooltip: "Duration of the auto lease in months",
    },
    {
      name: "residualPercent",
      label: "Residual Value %",
      type: "percentage",
      defaultValue: 55,
      unit: "%",
      min: 10,
      max: 90,
      step: 1,
      tooltip: "Estimated vehicle value at lease end as % of MSRP",
    },
    {
      name: "aprPercent",
      label: "Interest Rate (APR %)",
      type: "percentage",
      defaultValue: 6.0,
      unit: "%",
      min: 0,
      max: 20,
      step: 0.1,
      tooltip: "Annual interest rate (automatically converts to Money Factor)",
    },
    {
      name: "moneyFactor",
      label: "Money Factor (e.g. 0.0025)",
      type: "number",
      defaultValue: 0.0025,
      min: 0.0001,
      max: 0.01,
      step: 0.0001,
      tooltip: "Lease finance charge factor (APR / 2400)",
    },
    {
      name: "salesTaxRate",
      label: "Sales Tax Rate",
      type: "percentage",
      defaultValue: 7.0,
      unit: "%",
      min: 0,
      max: 15,
      step: 0.1,
      tooltip: "Combined state and local sales tax percentage",
    },
  ],
  outputs: [
    {
      name: "monthlyLeasePayment",
      label: "Total Monthly Lease Payment",
      format: "currency",
      highlight: true,
      description: "Estimated total monthly payment including depreciation, rent fee, and tax",
    },
    {
      name: "monthlyDepreciation",
      label: "Monthly Depreciation",
      format: "currency",
      description: "Monthly vehicle value decline portion",
    },
    {
      name: "monthlyFinanceFee",
      label: "Monthly Rent Charge (Finance Fee)",
      format: "currency",
      description: "Monthly financing fee paid to the lessor",
    },
    {
      name: "totalLeaseCost",
      label: "Total Out-of-Pocket Lease Cost",
      format: "currency",
      description: "Combined total of down payment, fees, and all monthly payments",
    },
    {
      name: "residualValue",
      label: "Lease-End Purchase Price (Residual Value)",
      format: "currency",
      description: "Contracted purchase buyout price at lease end",
    },
  ],
  calculate: (inputs) => {
    const res = calculateAutoLeaseFormula({
      autoPrice: Number(inputs.autoPrice || 35000),
      vehicleMsrp: Number(inputs.vehicleMsrp || 36000),
      downPayment: Number(inputs.downPayment || 2500),
      tradeInValue: Number(inputs.tradeInValue || 2000),
      leaseTermMonths: Number(inputs.leaseTermMonths || 36),
      residualPercent: Number(inputs.residualPercent || 55),
      aprPercent: Number(inputs.aprPercent || 6.0),
      moneyFactor: Number(inputs.moneyFactor || 0.0025),
      salesTaxRate: Number(inputs.salesTaxRate || 7.0),
    });
    return {
      monthlyLeasePayment: res.monthlyLeasePayment,
      monthlyDepreciation: res.monthlyDepreciation,
      monthlyFinanceFee: res.monthlyFinanceFee,
      totalLeaseCost: res.totalLeaseCost,
      residualValue: res.residualValue,
    };
  },
};

export default AUTO_LEASE_CALCULATOR;
