import { CalculatorModuleDefinition } from "@/calculators/types";
import { calculatePregnancyWeightGainCalculator } from "./calculator";
import { pregnancy_weight_gain_calculatorFaqs } from "./faq";
import { PregnancyWeightGainContent } from "@/components/calculator/pregnancy-weight-gain/PregnancyWeightGainContent";

export const pregnancy_weight_gain_calculatorConfig: CalculatorModuleDefinition = {
  id: "pregnancy-weight-gain-calculator",
  title: "Pregnancy Weight Gain Calculator",
  slug: "pregnancy-weight-gain-calculator",
  category: "Health",
  subcategory: "Pregnancy",
  description:
    "Calculate recommended pregnancy weight gain by pre-pregnancy BMI, pregnancy week and singleton or twin pregnancy. Compare your gain with IOM reference ranges and track a 40-week trajectory.",
  iconName: "TrendingUp",
  featured: true,
  keywords: [
    "pregnancy weight gain calculator",
    "pregnancy weight gain calculator by week",
    "pregnancy weight gain calculator by BMI",
    "how much weight should I gain during pregnancy",
    "pregnancy weight gain tracker",
    "pregnancy weight gain chart",
    "IOM pregnancy weight gain calculator",
    "pregnancy weight gain calculator twins",
    "how much weight should I gain each trimester",
    "pregnancy weight gain by pre-pregnancy BMI",
  ],
  priority: 1,
  relatedCalculators: [
    "bmi-calculator",
    "pregnancy-calculator",
    "calorie-calculator",
    "conception-calculator",
    "ovulation-calculator",
  ],
  formulaDescription:
    "Calculates maternal body mass index (BMI = kg/m²) and applies 2009 Institute of Medicine (IOM) and ACOG gestational weight gain ranges for singleton and twin pregnancies across all 40 weeks.",
  faqs: pregnancy_weight_gain_calculatorFaqs,
  ContentComponent: PregnancyWeightGainContent,
  inputs: [
    {
      name: "unitSystem",
      label: "Unit System",
      type: "select",
      defaultValue: "us",
      options: [
        { label: "US Units (lbs, ft/in)", value: "us" },
        { label: "Metric Units (kg, cm)", value: "metric" },
      ],
    },
    {
      name: "pregnancyType",
      label: "Pregnancy Type",
      type: "select",
      defaultValue: "single",
      options: [
        { label: "Single Baby", value: "single" },
        { label: "Twins / Multiples", value: "twins" },
      ],
    },
    {
      name: "week",
      label: "Current Pregnancy Stage (Week 1 – 40)",
      type: "number",
      defaultValue: 20,
      min: 1,
      max: 40,
      step: 1,
    },
    {
      name: "heightFeet",
      label: "Height (Feet)",
      type: "number",
      defaultValue: 5,
      min: 3,
      max: 7,
      step: 1,
    },
    {
      name: "heightInches",
      label: "Height (Inches)",
      type: "number",
      defaultValue: 6,
      min: 0,
      max: 11,
      step: 1,
    },
    {
      name: "heightCm",
      label: "Height (cm)",
      type: "number",
      defaultValue: 168,
      min: 100,
      max: 230,
      step: 1,
    },
    {
      name: "preWeightLbs",
      label: "Pre-Pregnancy Weight (lbs)",
      type: "number",
      defaultValue: 130,
      min: 66,
      max: 550,
      step: 0.5,
    },
    {
      name: "preWeightKg",
      label: "Pre-Pregnancy Weight (kg)",
      type: "number",
      defaultValue: 59,
      min: 30,
      max: 250,
      step: 0.5,
    },
    {
      name: "currentWeightLbs",
      label: "Current Weight (lbs)",
      type: "number",
      defaultValue: 142,
      min: 66,
      max: 550,
      step: 0.5,
    },
    {
      name: "currentWeightKg",
      label: "Current Weight (kg)",
      type: "number",
      defaultValue: 64.5,
      min: 30,
      max: 250,
      step: 0.5,
    },
  ],
  outputs: [
    {
      name: "preBmi",
      label: "Pre-Pregnancy BMI",
      format: "number",
    },
    {
      name: "bmiCategory",
      label: "BMI Category",
      format: "text",
    },
    {
      name: "recommendedGainTotalFormatted",
      label: "Total Recommended Weight Gain",
      format: "text",
      highlight: true,
    },
    {
      name: "targetGainWeekFormatted",
      label: "Target Weight Gain for Current Week",
      format: "text",
      highlight: true,
    },
    {
      name: "statusLabel",
      label: "Clinical Weight Status",
      format: "text",
    },
    {
      name: "weeklyRateFormatted",
      label: "Recommended Weekly Pace (T2 & T3)",
      format: "text",
    },
  ],
  calculate: calculatePregnancyWeightGainCalculator,
};

export default pregnancy_weight_gain_calculatorConfig;
