import { CalculatorModuleDefinition } from "@/calculators/types";
import { calculateScientificCalculator } from "./calculator";
import { scientific_calculatorFaqs } from "./faq";
import { ScientificCalculator } from "@/components/calculator/scientific/ScientificCalculator";
import { ScientificCalculatorContent } from "@/components/calculator/scientific/ScientificCalculatorContent";

export const scientific_calculatorConfig: CalculatorModuleDefinition = {
  id: "scientific-calculator",
  title: "Scientific Calculator",
  slug: "scientific-calculator",
  category: "Math",
  subcategory: "General Math",
  description:
    "Use a scientific calculator for trigonometry, logarithms, powers, roots, factorials, scientific notation and multi-step expressions with DEG, RAD and GRAD modes.",
  iconName: "Calculator",
  featured: true,
  keywords: [
    "scientific calculator",
    "online scientific calculator",
    "scientific calculator online",
    "scientific calculator how to use",
    "scientific calculator buttons",
    "scientific calculator functions",
    "scientific calculator trig",
    "scientific calculator degrees radians",
    "scientific calculator logarithms",
    "scientific calculator exponents",
    "scientific calculator roots",
    "scientific calculator factorial",
    "scientific calculator equation calculations",
    "algebra calculator",
    "engineering calculator",
    "scientific notation calculator",
  ],
  priority: 1,
  relatedCalculators: [
    "exponent-calculator",
    "log-calculator",
    "root-calculator",
    "fraction-calculator",
    "percentage-calculator",
    "triangle-calculator",
    "pythagorean-theorem-calculator",
  ],
  formulaDescription:
    "Evaluates trigonometric ratios, logarithmic base transforms, factorials, and exponential series.",
  faqs: scientific_calculatorFaqs,
  CustomComponent: ScientificCalculator,
  ContentComponent: ScientificCalculatorContent,
  inputs: [
    {
      name: "value1",
      label: "Primary Number (X)",
      type: "number",
      defaultValue: 45,
      min: -1000000000,
      max: 1000000000,
      step: 1,
    },
    {
      name: "operation",
      label: "Operation",
      type: "select",
      defaultValue: "sin",
      options: [
        { label: "Sine (sin X)", value: "sin" },
        { label: "Cosine (cos X)", value: "cos" },
        { label: "Tangent (tan X)", value: "tan" },
        { label: "ArcSine (arcsin X)", value: "asin" },
        { label: "ArcCosine (arccos X)", value: "acos" },
        { label: "ArcTangent (arctan X)", value: "atan" },
        { label: "Natural Log (ln X)", value: "ln" },
        { label: "Base-10 Log (log₁₀ X)", value: "log10" },
        { label: "Base-2 Log (log₂ X)", value: "log2" },
        { label: "Square (X²)", value: "sqr" },
        { label: "Cube (X³)", value: "cube" },
        { label: "X to Power Y (X^Y)", value: "pow" },
        { label: "Exponential (e^X)", value: "exp" },
        { label: "10 to Power X (10^X)", value: "pow10" },
        { label: "Square Root (√X)", value: "sqrt" },
        { label: "Cube Root (∛X)", value: "cbrt" },
        { label: "Y-th Root of X (ⁿ√X)", value: "yroot" },
        { label: "Factorial (X!)", value: "factorial" },
        { label: "Absolute Value (|X|)", value: "abs" },
        { label: "Reciprocal (1/X)", value: "recip" },
        { label: "Modulo (X mod Y)", value: "mod" },
      ],
    },
    {
      name: "value2",
      label: "Secondary Value (Y) — For X^Y, Y-th Root, Modulo",
      type: "number",
      defaultValue: 2,
      min: -1000000000,
      max: 1000000000,
      step: 1,
    },
    {
      name: "angleUnit",
      label: "Angle Unit (Trigonometry)",
      type: "select",
      defaultValue: "deg",
      options: [
        { label: "Degrees (°)", value: "deg" },
        { label: "Radians (rad)", value: "rad" },
        { label: "Gradians (grad)", value: "grad" },
      ],
    },
  ],
  outputs: [
    {
      name: "result",
      label: "Calculated Result",
      format: "text",
      highlight: true,
    },
    {
      name: "explanation",
      label: "Operation Summary & Step",
      format: "text",
    },
    {
      name: "domainNote",
      label: "Domain & Mathematical Boundary Note",
      format: "text",
    },
  ],
  calculate: calculateScientificCalculator,
};

export default scientific_calculatorConfig;
