"use client";

import React from "react";
import Link from "next/link";
import {
  EducationalSection,
  FormulaBox,
  EducationalGrid,
  EducationalCard,
  FAQSection,
  DisclaimerSection,
} from "@/components/calculator/educational";

export function InvestmentContent() {
  const faqs = [
    {
      question: "What is a good annual investment return to assume for long-term planning?",
      answer:
        "Historical long-term U.S. equity market returns (such as the S&P 500) have averaged approximately 8% to 10% annually before inflation over multi-decade periods, though future returns vary and past performance does not guarantee future results. Balanced portfolios incorporating fixed-income bonds generally model 5% to 7% nominal returns. Conservative planning models often adjust for a 2% to 3% annual inflation rate to reflect real purchasing power.",
    },
    {
      question: "How much should I invest each month to reach my goal?",
      answer:
        "There is no universal monthly amount. This calculator solves for the mathematically required contribution based on your specific financial target, starting principal, return assumption, duration, and selected timing parameters.",
    },
    {
      question: "What is dollar-cost averaging (DCA)?",
      answer:
        "Dollar-cost averaging is the disciplined investment strategy of allocating fixed dollar amounts at regular intervals (such as monthly) regardless of market fluctuations. This approach acquires more shares when prices are lower and fewer shares when prices are higher. DCA can reduce the risk of committing a lump sum immediately before a market decline, but it does not eliminate investment or sequence risk.",
    },
    {
      question: "Should contributions be invested monthly or annually?",
      answer:
        "Under the mathematical assumptions of compound growth, earlier periodic contributions (such as monthly deposits) provide capital with more time in the market to generate compound returns and dividend reinvestment compared to waiting for a single end-of-year lump sum deposit.",
    },
    {
      question: "How is the FIRE number calculated?",
      answer:
        "The FIRE target is commonly estimated as 25 times anticipated annual retirement living expenses. This heuristic is derived from a 4% initial annual withdrawal rate benchmark (1 / 0.04 = 25). For example, supporting $60,000 in annual retirement expenses suggests a portfolio target of approximately $1,500,000.",
    },
    {
      question: "How does an expense ratio affect total wealth accumulation?",
      answer:
        "An expense ratio is an ongoing annual management fee deducted from fund assets. Because fees reduce net compounding returns year after year, an expense ratio of 1.00% versus 0.05% in an index fund can reduce total potential portfolio accumulation by 20% to 25% or more in long-term compounding scenarios.",
    },
    {
      question: "What is the difference between nominal returns and real purchasing power?",
      answer:
        "Nominal return is the raw percentage gain generated by an investment portfolio before deductions. Real return adjusts nominal gains for the eroding effect of consumer price inflation. For example, an 8% nominal return in an environment with 3% annual inflation represents an approximate 4.85% to 5.0% real growth rate in purchasing power.",
    },
    {
      question: "How does compounding frequency impact investment returns?",
      answer:
        "Compounding frequency refers to how often earned interest or returns are added to the principal to generate subsequent earnings. More frequent compounding (such as monthly or daily versus annually) produces slightly higher effective annual yields (APY) due to intra-year growth on accumulated earnings.",
    },
    {
      question: "What is the 4% withdrawal benchmark for investment portfolios?",
      answer:
        "The 4% rule originated from empirical retirement research (including the 1998 Trinity Study), which found that an initial 4% withdrawal adjusted annually for inflation had a high historical success rate over 30-year horizons with balanced equity/bond portfolios. It is an illustrative planning benchmark, not an absolute guarantee.",
    },
    {
      question: "How do taxes impact taxable investment accounts versus tax-advantaged accounts?",
      answer:
        "In taxable brokerage accounts, dividends, interest, and realized capital gains are subject to annual income and capital gains taxes, creating tax drag that reduces net compounding. Tax-advantaged accounts like Traditional 401(k)s, Traditional IRAs, and Roth IRAs allow investments to compound tax-deferred or tax-free.",
    },
    {
      question: "What is asset allocation and why is it important?",
      answer:
        "Asset allocation is an important driver of an investment portfolio's risk and return characteristics. Dividing capital across asset categories (such as equities, bonds, cash, and real estate) helps manage market volatility and align portfolio growth with personal time horizons.",
    },
    {
      question: "How does step-up contribution growth affect long-term investing?",
      answer:
        "Step-up contributions involve increasing recurring monthly or annual deposits by a fixed percentage each year (for example, 3% to 5% to match salary raises). Step-up deposits significantly increase cumulative principal invested during peak earning years without requiring an unsustainable upfront contribution.",
    },
  ];

  return (
    <div className="space-y-10 py-2 text-slate-900 dark:text-slate-100">
      {/* SECTION 1: WHAT IS AN INVESTMENT CALCULATOR? */}
      <EducationalSection
        id="what-is-investment-calculator"
        title="1. What Is an Investment Calculator?"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          An <strong>investment calculator</strong> is a financial modeling tool designed to project prospective portfolio growth and
          solve reverse goal-planning equations under user-configured mathematical assumptions. Unlike static savings tables that only
          track linear bank deposits, an investment calculator models multi-asset accumulation driven by initial starting principal,
          recurring periodic contributions, compounding frequencies, cash-flow timing conventions, annual step-up contribution increases,
          fund expense ratios, consumer price inflation, and modeled tax drag.
        </p>

        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          In addition to forward future value projections, this platform integrates four reverse and benchmark analytical engines:
        </p>

        <EducationalGrid columns={2}>
          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h4 className="font-bold text-xs text-slate-900 dark:text-slate-100">
              Forward Growth &amp; Hurdle Solvers
            </h4>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
              Projects future wealth or solves for the required monthly deposit, hurdle rate of return, or initial capital needed to
              reach a specific portfolio milestone.
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h4 className="font-bold text-xs text-slate-900 dark:text-slate-100">
              Retirement &amp; FIRE Benchmarks
            </h4>
            <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
              Converts accumulated wealth into an illustrative 4% annual withdrawal benchmark and evaluates progress against the
              classic 25× financial independence heuristic.
            </p>
          </div>
        </EducationalGrid>

        <p className="text-xs text-slate-600 dark:text-slate-400 italic">
          Results are mathematical projections based on user-selected assumptions, not guaranteed investment outcomes.
        </p>
      </EducationalSection>

      {/* SECTION 2: HOW INVESTMENT GROWTH IS CALCULATED */}
      <EducationalSection
        id="how-growth-calculated"
        title="2. How Investment Growth Is Calculated"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          Portfolio accumulation over multi-year horizons is governed by the principles of the <strong>Time Value of Money (TVM)</strong> and{" "}
          <strong>discrete compound interest</strong>. When capital is invested in productive financial assets—such as equities, fixed-income
          bonds, and diversified index funds—growth is generated through asset price appreciation, periodic interest distributions, and
          reinvested dividends.
        </p>

        <FormulaBox
          title="Investment Future Value Formula (Discrete Compounding with Annuity Deposits):"
          badge="Discrete Compounding Model"
          formula="FV = PV \times (1 + r_{\text{period}})^{n \times t} + PMT \times \left[ \frac{(1 + r_{\text{period}})^{n \times t} - 1}{r_{\text{period}}} \right] \times (1 + r_{\text{period}} \times \text{timing})"
          variables={[
            { symbol: "FV", name: "Future Portfolio Value", description: "Projected total nominal portfolio balance at maturity" },
            { symbol: "PV", name: "Starting Principal", description: "Initial upfront lump-sum capital invested at time zero" },
            { symbol: "PMT", name: "Periodic Contribution", description: "Recurring deposit made at each interval (e.g., monthly)" },
            { symbol: "r_period", name: "Periodic Return Rate", description: "Effective return rate per period, net of expense ratios" },
            { symbol: "n", name: "Compounding Frequency", description: "Number of compounding conversion periods per year" },
            { symbol: "t", name: "Investment Horizon", description: "Total investment duration in years" },
            { symbol: "timing", name: "Timing Indicator", description: "0 for end-of-period ordinary annuity, 1 for beginning-of-period annuity due" },
          ]}
          notes={
            <div className="leading-relaxed">
              To explore isolated compounding curves or general Time Value of Money cash-flow discounting equations, consult our{" "}
              <Link
                href="/calculators/compound-interest-calculator"
                className="font-semibold text-blue-600 dark:text-blue-400 hover:underline"
              >
                compound interest calculator
              </Link>{" "}
              and{" "}
              <Link
                href="/calculators/future-value-calculator"
                className="font-semibold text-blue-600 dark:text-blue-400 hover:underline"
              >
                future value calculator
              </Link>
              .
            </div>
          }
        />
      </EducationalSection>

      {/* SECTION 3: MONTHLY CONTRIBUTIONS AND CASH-FLOW TIMING */}
      <EducationalSection
        id="monthly-contributions-timing"
        title="3. Monthly Contributions and Cash-Flow Timing"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          The frequency and timing of periodic contributions directly influence multi-decade wealth accumulation:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h4 className="font-bold text-slate-900 dark:text-slate-100">1. Ordinary Annuity (End of Period)</h4>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              Deposits are credited at the conclusion of each payment interval. Contributions made at the end of month earn compound
              returns starting in subsequent periods.
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h4 className="font-bold text-slate-900 dark:text-slate-100">2. Annuity Due (Beginning of Period)</h4>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              Deposits are credited at the start of each interval. Capital is exposed to compounding immediately for the full duration
              of the period. Under the calculator&apos;s assumptions, earlier contributions have more time to compound.
            </p>
          </div>
        </div>

        <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
          The step-up feature automatically increases recurring monthly deposits by a user-defined percentage (e.g., 3% annually) at
          the beginning of each investment year, modeling career salary increases over time. To model specialized recurring contribution
          schedules, explore our{" "}
          <Link
            href="/calculators/sip-calculator"
            className="font-semibold text-blue-600 dark:text-blue-400 hover:underline"
          >
            Systematic Investment Plan (SIP) calculator
          </Link>
          .
        </p>
      </EducationalSection>

      {/* SECTION 4: HOW MUCH SHOULD YOU INVEST TO REACH A TARGET? */}
      <EducationalSection
        id="target-contribution-solver"
        title="4. How Much Should You Invest to Reach a Target?"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          When planning for a major financial milestone, the <strong>Target Contribution Mode</strong> functions as a reverse sinking fund
          solver. It isolates the required modeled periodic deposit (PMT) by subtracting the future value of existing starting principal
          from the target goal and dividing by the unit annuity accumulation factor:
        </p>

        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 text-xs space-y-2">
          <h4 className="font-bold text-slate-900 dark:text-slate-100">Verified Sinking Fund Worked Examples:</h4>
          <p className="text-slate-600 dark:text-slate-400">
            <em>(Parameters: Starting Principal = $20,000, Gross Return = 8.00%, Expense Ratio = 0.10% &rarr; Net Return = 7.90%, Annual Compounding, 20-Year Horizon)</em>
          </p>
          <ul className="list-disc list-inside space-y-1 text-slate-700 dark:text-slate-300">
            <li>
              <strong>$500,000 Target Goal:</strong> Required modeled contribution is <strong>$726.22 per month</strong> (Total Contributed: $194,292.80; Forward Reconciled Balance: $500,001.78).
            </li>
            <li>
              <strong>$1,000,000 Target Goal:</strong> Required modeled contribution is <strong>$1,615.12 per month</strong> (Total Contributed: $387,628.80; Forward Reconciled Balance: $1,000,000.00).
            </li>
          </ul>
        </div>
      </EducationalSection>

      {/* SECTION 5: WHAT RETURN IS REQUIRED TO REACH YOUR GOAL? */}
      <EducationalSection
        id="required-return-solver"
        title="5. What Return Is Required to Reach Your Goal?"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          When starting capital, monthly contributions, and duration are fixed, investors often evaluate the hurdle rate of return needed
          to reach a target. A standard point-to-point CAGR formula is insufficient when periodic cash flows exist.
        </p>

        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          Our platform applies an 80-iteration <strong>numerical bisection root finder</strong> to solve for the mathematically required
          return such that the forward simulation balance matches the goal.
        </p>

        <div className="p-3.5 rounded-xl bg-blue-50/70 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-800 text-xs space-y-1">
          <h4 className="font-bold text-blue-900 dark:text-blue-200">Verified Hurdle Rate Example ($500,000 Goal):</h4>
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
            With Starting Principal = $20,000, Monthly Deposit = $500/month, 20 years, and 0.10% fee, the mathematically required gross return is{" "}
            <strong>10.1940% per year</strong> (Net: 10.0940%). Forward reconciliation yields exactly <strong>$500,000.00</strong>.
          </p>
        </div>

        <p className="text-xs text-slate-600 dark:text-slate-400">
          To evaluate historical point-to-point annualized portfolio performance, visit our{" "}
          <Link
            href="/calculators/cagr-calculator"
            className="font-semibold text-blue-600 dark:text-blue-400 hover:underline"
          >
            CAGR calculator
          </Link>
          .
        </p>
      </EducationalSection>

      {/* SECTION 6: HOW MUCH STARTING CAPITAL DO YOU NEED? */}
      <EducationalSection
        id="starting-capital-solver"
        title="6. How Much Starting Capital Do You Need?"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          The <strong>Starting Amount Mode</strong> calculates the upfront lump-sum principal required today to hit a future target when
          monthly contributions are constrained. It subtracts the future value of planned contributions from the target and discounts the
          remainder back across the time horizon:
        </p>

        <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 text-xs space-y-1">
          <h4 className="font-bold text-slate-900 dark:text-slate-100">Verified Starting Principal Example:</h4>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            To reach a $500,000 target in 20 years with $500/month deposits at 8.00% gross return (0.10% fee), the required starting
            principal is <strong>$47,810.79</strong>.
          </p>
        </div>

        <p className="text-xs text-slate-600 dark:text-slate-400">
          To compare fixed-yield bank deposit strategies and emergency cash accumulation, consult our{" "}
          <Link
            href="/calculators/savings-calculator"
            className="font-semibold text-blue-600 dark:text-blue-400 hover:underline"
          >
            dedicated savings calculator
          </Link>
          .
        </p>
      </EducationalSection>

      {/* SECTION 7: HOW INFLATION CHANGES FUTURE PURCHASING POWER */}
      <EducationalSection
        id="inflation-purchasing-power"
        title="7. How Inflation Changes Future Purchasing Power"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          Nominal balances represent raw dollars, whereas <strong>real purchasing power</strong> reflects the actual quantity of goods and
          services those dollars will purchase after accounting for inflation:
        </p>

        <FormulaBox
          title="Inflation Purchasing Power Discount Equation:"
          badge="Real Purchasing Power Model"
          formula="\text{Real Value} = \frac{\text{Nominal Ending Balance}}{(1 + \text{inflation})^t}"
          variables={[
            { symbol: "Real Value", name: "Inflation-Adjusted Value", description: "Ending wealth expressed in base-year purchasing power" },
            { symbol: "Nominal Balance", name: "Future Nominal Value", description: "Raw dollar balance projected by the compounding engine" },
            { symbol: "inflation", name: "Annual Inflation Rate", description: "Assumed constant annual consumer price inflation rate" },
            { symbol: "t", name: "Horizon", description: "Investment duration in years" },
          ]}
        />

        <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 text-xs space-y-1">
          <h4 className="font-bold text-slate-900 dark:text-slate-100">20-Year Inflation Erosion Example:</h4>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            In our baseline projection (Starting Principal = $20,000, Monthly Deposit = $500/month, Gross Return = 8.00%, Fee = 0.10%), the nominal
            ending balance is <strong>$372,754.57</strong>. Under a constant 3.00% annual inflation assumption, the real purchasing power is{" "}
            <strong>$206,386.63</strong>—a reduction of approximately <strong>44.63%</strong> in real purchasing power over 20 years.
          </p>
        </div>
      </EducationalSection>

      {/* SECTION 8: HOW INVESTMENT FEES AFFECT LONG-TERM GROWTH */}
      <EducationalSection
        id="investment-fee-drag"
        title="8. How Investment Fees Affect Long-Term Growth"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          Fund operating costs and management fees—expressed as an annual <strong>expense ratio</strong>—are deducted continuously from
          portfolio assets. The calculator applies the user-entered expense ratio once within its modeled net-return calculation:
        </p>

        <p className="text-xs font-mono font-bold text-slate-800 dark:text-slate-200 bg-slate-100 dark:bg-slate-800 p-2.5 rounded-lg text-center">
          Gross Expected Return − Expense Ratio = Modeled Net Return
        </p>

        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 text-xs space-y-2">
          <h4 className="font-bold text-slate-900 dark:text-slate-100">30-Year Comparative Fee Case Study:</h4>
          <p className="text-slate-600 dark:text-slate-400">
            <em>(Assumptions: Principal = $20,000, Monthly Deposit = $500/month, Gross Return = 8.00%, Duration = 30 years)</em>
          </p>
          <ul className="list-disc list-inside space-y-1 text-slate-700 dark:text-slate-300">
            <li><strong>Low-Cost Index Fund (0.05% Fee):</strong> Final ending balance is approximately <strong>$886,527</strong> (Net Return: 7.95%).</li>
            <li><strong>Actively Managed Fund (1.00% Fee):</strong> Final ending balance is approximately <strong>$709,829</strong> (Net Return: 7.00%).</li>
            <li><strong>Modeled Wealth Variance:</strong> In this modeled scenario, the 0.95% fee differential erases approximately <strong>$176,698</strong> (or ~19.93%) of total wealth.</li>
          </ul>
        </div>
      </EducationalSection>

      {/* SECTION 9: TAX DRAG IN INVESTMENT PROJECTIONS */}
      <EducationalSection
        id="tax-drag-projections"
        title="9. Tax Drag in Investment Projections"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          In taxable brokerage accounts, returns are subject to annual income and capital gains taxes, creating <strong>tax drag</strong>.
          The calculator models a simplified tax drag parameter by deducting the selected tax rate from periodic interest generated in the
          simulation.
        </p>

        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          Actual tax liabilities vary based on account classification, holding periods, and individual tax brackets:
        </p>

        <EducationalGrid columns={3}>
          <EducationalCard title="1. Taxable Accounts">
            Dividends, interest, and realized capital gains incur annual tax liability, creating continuous compounding drag.
          </EducationalCard>

          <EducationalCard title="2. Traditional Accounts">
            Contributions may be pre-tax, and earnings compound tax-deferred until withdrawal in retirement.
          </EducationalCard>

          <EducationalCard title="3. Roth Accounts">
            Contributions are made with post-tax funds, and qualified withdrawals in retirement are generally tax-free.
          </EducationalCard>
        </EducationalGrid>

        <p className="text-xs text-slate-600 dark:text-slate-400">
          To model tax-advantaged workplace retirement plans and employer matching schedules, explore our{" "}
          <Link
            href="/calculators/401k-calculator"
            className="font-semibold text-blue-600 dark:text-blue-400 hover:underline"
          >
            401(k) retirement calculator
          </Link>
          .
        </p>
      </EducationalSection>

      {/* SECTION 10: ASSET ALLOCATION, DIVERSIFICATION, AND RISK */}
      <EducationalSection
        id="asset-allocation-risk"
        title="10. Asset Allocation, Diversification, and Risk"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          Asset allocation is an important driver of an investment portfolio&apos;s risk and return characteristics across market cycles:
        </p>

        <EducationalGrid columns={3}>
          <EducationalCard title="1. Equities & Stocks">
            Fractional ownership in public companies offering long-term growth potential accompanied by market price volatility.
          </EducationalCard>

          <EducationalCard title="2. Fixed-Income Bonds">
            Debt instruments providing interest coupons. U.S. Treasuries carry low credit risk as sovereign debt, though prices fluctuate with interest rates.
          </EducationalCard>

          <EducationalCard title="3. Bank CDs & Cash">
            Fixed-term savings products. In the U.S., FDIC-insured deposits are protected up to $250,000 per depositor, per insured bank, per ownership category.
          </EducationalCard>

          <EducationalCard title="4. Real Estate (REITs)">
            Liquid securities providing income-property exposure, subject to real estate market and interest-rate risks.
          </EducationalCard>

          <EducationalCard title="5. Broad Index Funds & ETFs">
            Pooled vehicles tracking benchmark indexes, providing broad diversification to mitigate single-company concentration risk.
          </EducationalCard>

          <EducationalCard title="6. Commodities & Gold">
            Tangible real assets historically utilized as portfolio diversifiers and inflation hedges during geopolitical shifts.
          </EducationalCard>
        </EducationalGrid>
      </EducationalSection>

      {/* SECTION 11: DOLLAR-COST AVERAGING VS. LUMP-SUM INVESTING */}
      <EducationalSection
        id="dca-vs-lump-sum"
        title="11. Dollar-Cost Averaging vs. Lump-Sum Investing"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          Two primary methods exist for deploying capital into financial markets:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h4 className="font-bold text-slate-900 dark:text-slate-100">Dollar-Cost Averaging (DCA)</h4>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              Allocating fixed amounts at regular intervals. DCA can reduce the risk of committing a lump sum immediately before a market
              decline, but it does not eliminate investment or sequence risk.
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-1">
            <h4 className="font-bold text-slate-900 dark:text-slate-100">Lump-Sum Investing</h4>
            <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
              Deploying available capital immediately. Because markets have historically trended upward over long timeframes, immediate
              deployment gives capital more time to compound under the model, though outcomes depend on market path and cash availability.
            </p>
          </div>
        </div>
      </EducationalSection>

      {/* SECTION 12: THE 4% WITHDRAWAL BENCHMARK */}
      <EducationalSection
        id="four-percent-benchmark"
        title="12. The 4% Withdrawal Benchmark"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          Empirical retirement research (including William Bengen&apos;s 1994 study and the 1998 Trinity Study) analyzed historical sustainable
          withdrawal rates from balanced portfolios over 30-year horizons.
        </p>

        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          The <strong>Illustrative 4% Withdrawal Benchmark</strong> converts projected ending wealth into an estimated annual and monthly
          cash-flow reference:
        </p>

        <div className="p-3.5 rounded-xl bg-emerald-50/70 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-800 text-xs space-y-1">
          <h4 className="font-bold text-emerald-900 dark:text-emerald-200">Baseline 4% Benchmark (Ending Balance = $372,754.57):</h4>
          <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
            Annual Benchmark: $372,754.57 &times; 0.04 = <strong>$14,910.18/year</strong> | Monthly Benchmark: <strong>$1,242.52/month</strong>.
          </p>
        </div>

        <p className="text-xs text-slate-600 dark:text-slate-400">
          This is an illustrative planning benchmark, not a guaranteed lifetime payout. For comprehensive retirement planning
          incorporating salary replacement ratios and Social Security offsets, consult our{" "}
          <Link
            href="/calculators/retirement-calculator"
            className="font-semibold text-blue-600 dark:text-blue-400 hover:underline"
          >
            comprehensive retirement calculator
          </Link>
          .
        </p>
      </EducationalSection>

      {/* SECTION 13: THE FIRE NUMBER AND 25X HEURISTIC */}
      <EducationalSection
        id="fire-number-heuristic"
        title="13. The FIRE Number and 25× Heuristic"
      >
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          In Financial Independence, Retire Early (FIRE) models, a target portfolio is commonly estimated as 25 times annual living
          expenses, derived from the 4% initial withdrawal framework (1 / 0.04 = 25).
        </p>

        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 text-xs space-y-2">
          <h4 className="font-bold text-slate-900 dark:text-slate-100">FIRE Mode Implementation Disclosure:</h4>
          <p className="text-slate-600 dark:text-slate-400 leading-relaxed">
            The FIRE mode applies a 25× heuristic to the annual amount used by the calculator&apos;s model (Annual Contribution &times; 25).
            This is a rule-of-thumb benchmark, not a personalized FIRE expense calculation.
          </p>
          <ul className="list-disc list-inside space-y-1 text-slate-700 dark:text-slate-300">
            <li><strong>FIRE Target Benchmark:</strong> $500/month &times; 12 &times; 25 = <strong>$150,000.00</strong>.</li>
            <li><strong>Projected Balance:</strong> <strong>$372,754.57</strong> (Progress: <strong>248.5%</strong> — <em>FIRE Target Reached</em>).</li>
          </ul>
        </div>
      </EducationalSection>

      {/* SECTION 14: FREQUENTLY ASKED QUESTIONS */}
      <FAQSection faqs={faqs} />

      {/* SECTION 15: CALCULATION METHODOLOGY & FINANCIAL DISCLAIMER */}
      <DisclaimerSection
        title="15. Calculation Methodology & Financial Disclaimer"
        methodology="Future portfolio value simulations apply discrete compound interest annuity equations with monthly discrete simulation steps. Cash-flow timing conventions account for ordinary annuities (end of month) and annuities due (beginning of month). Annual step-up deposits increase monthly contributions by the configured escalation rate every 12 months. Expense ratios are modeled as a single net-return deduction (r_net = r_gross - expense ratio). Reverse target contribution and starting principal solvers utilize exact linear decomposition, while the required return rate is solved using an 80-iteration numerical bisection root finder. Inflation purchasing power is discounted using the compound price index formula Real = Nominal / (1 + i)^t."
        disclaimer="The calculator provides mathematical projections based on user-entered assumptions. Investment returns, inflation, taxes, fees, and actual market performance can differ substantially from modeled values. Past performance is no guarantee of future results. Market investments are subject to risk, including the possible loss of principal. Tax and inflation treatments represent generalized modeling assumptions. This platform does not provide personalized legal, accounting, tax, or investment advice. Consult a registered investment advisor (RIA) or certified financial planner (CFP) for personalized financial advisory guidance."
      />
    </div>
  );
}

export default InvestmentContent;
