export interface FaqItem {
  question: string;
  answer: string;
}

export const annuityPayoutFaqs: FaqItem[] = [
  {
    question: "How much does a $500,000 annuity pay per month?",
    answer:
      "The answer depends on the interest rate, payout period and payment frequency. Using this calculator's reference case of $500,000 at 6% over 10 years with monthly payments produces a modeled payout of $5,551.03 per month.",
  },
  {
    question: "How much will $500,000 pay for 10 years at 6%?",
    answer:
      "Using monthly payments and a 6% annual rate, the calculator produces approximately $5,551.03 per month, or $666,123.01 in total modeled payments over 120 months.",
  },
  {
    question: "How long will $500,000 last if I withdraw $5,000 a month?",
    answer:
      "At a modeled 6% annual return, the calculator estimates approximately 11.6 years, or 139 months, before the balance is depleted under the fixed-payment model.",
  },
  {
    question: "What happens if my withdrawal is too small to reduce the principal?",
    answer:
      "If the requested periodic payment is no greater than the interest generated by the account during that period, the model may never deplete the principal. The calculator recognizes this boundary instead of producing a negative or invalid payoff period.",
  },
  {
    question: "What is the difference between a fixed-length and fixed-payment annuity calculation?",
    answer:
      "A fixed-length calculation starts with the desired payout period and solves for the payment. A fixed-payment calculation starts with the desired payment and solves for how long the money can last.",
  },
  {
    question: "How is an annuity payment calculated?",
    answer:
      "For a standard fixed payment stream, the calculator uses the annuity formula PMT = P × r × (1+r)ⁿ / [(1+r)ⁿ − 1], using the appropriate periodic interest rate and total number of payment periods.",
  },
  {
    question: "Does a higher interest rate increase the monthly annuity payout?",
    answer:
      "Generally, yes, within a fixed-term mathematical model, because more investment growth is available to support the payment stream. The precise effect depends on the principal, payment frequency and payout term.",
  },
  {
    question: "How does inflation affect retirement income?",
    answer:
      "Inflation reduces purchasing power over time. A fixed nominal monthly payment can buy fewer goods and services in the future. The calculator allows an inflation assumption in its life-expectancy planning model to illustrate this effect.",
  },
  {
    question: "What is the difference between an immediate and deferred annuity?",
    answer:
      "An immediate annuity begins payments shortly after purchase, while a deferred annuity delays income until a future date. During the deferral period, the underlying balance may accumulate according to the applicable contract or investment assumptions.",
  },
  {
    question: "Is a joint-life annuity better than a single-life annuity?",
    answer:
      "Not necessarily. A joint-life structure can provide income protection for two people, but the initial payment can differ from a single-life option. The better choice depends on household longevity, income needs and survivor objectives.",
  },
  {
    question: "What does a life-expectancy annuity payout mean?",
    answer:
      "It is a planning estimate of the income that could be supported over a selected longevity horizon under the calculator's return and inflation assumptions. It is not a prediction of when an individual will die.",
  },
  {
    question: "What is a 1035 exchange for an annuity?",
    answer:
      "A qualifying Section 1035 exchange can allow certain annuity and insurance contracts to be exchanged without immediate recognition of gain or loss under the applicable tax rules. The transaction must satisfy the statutory requirements, and exchanging contracts can introduce new fees or surrender periods.",
  },
  {
    question: "Are annuity payments taxable?",
    answer:
      "Potentially. Tax treatment depends on factors such as whether the annuity is qualified or nonqualified, the owner's basis and the type of distribution. The calculator does not determine an individual's final tax liability.",
  },
  {
    question: "Does an annuity guarantee that I will receive the calculator's payment?",
    answer:
      "No. The calculator's payment is a mathematical estimate under the entered assumptions. An actual annuity guarantee comes from the insurance contract and the issuing insurer, not from a calculator. FINRA also emphasizes the importance of the financial strength of the issuing insurer when evaluating annuities.",
  },
  {
    question: "Why can a deferred annuity have a higher monthly payment than an immediate annuity?",
    answer:
      "A deferred model allows the starting balance to grow before payments begin. If the assumed return is positive, the later payout can therefore be larger. The calculation must be evaluated alongside the income sacrificed during the deferral period.",
  },
];
